### ISSUE TITLE
10.0版本后一直提示"插件资源包已损坏"

### ISSUE THREAD

**Issue by farmerluo** [LuRenJiasWorld/WP-Editor.md#277]
10.0版本后一直提示：

插件资源包已损坏，请在下面提示链接中重新下载！

检验到插件资源包已过时，请根据下面提示下载最新资源包。

**Comment by angelochong** [comment]
我的也是这样，而且我的代码块还不能正常显示了，希望作者能早日解决，感激不尽！

**Comment by xiyt** [comment]
我的也是这个问题啊，希望作者尽快解决。wordpress版本是4.9.8–zh_CN

**Comment by xiaoyaoyuxin** [comment]
我也遇到这个问题了，貌似出在静态编辑器那里，提示：

> 状态：资源过时，请升级！

**Comment by JaxsonWang** [comment]
@farmerluo @angelochong @xiyt @xiaoyaoyuxin 

最近比较忙，文档没来得及处理，解决先看这：https://github.com/JaxsonWang/WP-Editor.md/wiki/08.-%E2%80%9C%E8%B5%84%E6%BA%90%E8%BF%87%E6%97%B6%E2%80%9D%E8%A7%A3%E5%86%B3

**Comment by paulloo** [comment]
https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.2.1/assets/MindMap/mindMap.min.js
这个地址我们访问不到？提示有风险

![image](https://user-images.githubusercontent.com/32083925/146743215-a477d75e-449e-4e68-a28e-0af46f5eac6e.png)
是因为 思维导图这边需要用到 这个文件
但是 ssl过期了，还是没配置啊？

**Comment by LuRenJiasWorld** [comment]
你好，由于 JSDelivr 在国内的运营商节点被封禁

> https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.2.1/assets/MindMap/mindMap.min.js 这个地址我们访问不到？提示有风险
> 
> ![image](https://user-images.githubusercontent.com/32083925/146743215-a477d75e-449e-4e68-a28e-0af46f5eac6e.png) 是因为 思维导图这边需要用到 这个文件 但是 ssl过期了，还是没配置啊？

你好，因为 JSDelivr 在大陆的运营商暂时被封禁，导致无法正常访问，JSDelivr 团队正在试图使用中国周边的节点保证大陆区域访问正常，但需要等一段时间。暂时可以在设置中将资源地址修改为服务器本地地址~

**Comment by flyher** [comment]
@LuRenJiasWorld  这个bug依然存在，不知道有没有修复的计划。

复现方式-> 插件：编辑器设置->编辑器静态资源地址->使用本地资源->保存更改
（注：使用CDN资源不存在这个提示，version.json 本地和 CDN 下的内容一致）

刷新页面后，在后端所有页面顶部均显示一下2行提示且无法关闭😂

```log
插件资源包已损坏，请在下面提示链接中重新下载！
检验到插件资源包已过时，请在设置页面中进行配置！
```

该插件的错误会导致机器收到自己的DDOS，每分钟多次请求这个`json`文件，瑟瑟发抖。

```log
HTTP 版本 HTTP/2
方法 GET
路径 /wp-content/plugins/wp-editormd/assets/version.json
查询字符串 空查询字符串
```

**Comment by Zhou-Shilin** [comment]
@LuRenJiasWorld 此问题仍然存在
