### ISSUE TITLE
10.0.5版本，代码块中带`<?php`标签会解析错误

### ISSUE THREAD

**Issue by xiebruce** [LuRenJiasWorld/WP-Editor.md#356]
如下图所示：
![image](https://user-images.githubusercontent.com/13575500/65210426-bf0d9500-dacd-11e9-9d4c-aaa7b6d4ebc6.png)

按道理，代码块中这些字符都应该要原样输出的吧，但现在是解析出错，这个错误必须解决呀，不然我所有带php代码的页面都会受到影响。

我不知道10.0.6版本是否已经解决问题，但是10.0.6版本wp中并没有收到更新。

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/WP-Editor.md/issues/342

**Comment by xiebruce** [comment]
是要打开这个吗？
![image](https://user-images.githubusercontent.com/13575500/65214145-7361e800-dadb-11e9-97e5-a108c175256f.png)

我找半天没找到呀，是不是更新后没有了？我只找到这个：
![image](https://user-images.githubusercontent.com/13575500/65214141-6d6c0700-dadb-11e9-807b-be8984fbae62.png)

**Comment by JaxsonWang** [comment]
然后点开文章 更新一下就行了

**Comment by xiebruce** [comment]
不行，现在的问题是，并不是所有包括`<?php`标签的代码码都有问题，在我目前知道的一篇文章中，只有一个有问题，而其它都没问题，你说奇怪不奇怪，这个地址：[https://www.xiebruce.top/1103.html](https://www.xiebruce.top/1103.html)你搜索“类里的代码如下”就可以定位到那里。

**Comment by JaxsonWang** [comment]
这个10.0.5的确存在这个问题，建议更新10.0.6再试试 https://github.com/JaxsonWang/WP-Editor.md/releases/tag/v10.0.6

**Comment by xiebruce** [comment]
哦，这个不发到wp那边让我们能在网页中点更新吗？

**Comment by xiebruce** [comment]
更新到10.0.6了，刚那个问题是没问题了，但现在又有新问题，代码中的反斜杠你也给解析了啊，windows的路径都是反斜杠啊，现在都被解析了：
![image](https://user-images.githubusercontent.com/13575500/65217592-1b30e300-dae7-11e9-93c6-5278e60aec3c.png)

看，反斜杠全没了：
![image](https://user-images.githubusercontent.com/13575500/65217684-5c28f780-dae7-11e9-8d16-60ee0d531380.png)

**Comment by xiebruce** [comment]
大佬，这个问题会解决吧？

**Comment by LuRenJiasWorld** [comment]
> 大佬，这个问题会解决吧？D和冒号之间的距离也有点怪，感觉D后面的字号都变小了

这个似乎是代码高亮插件的问题，你如果F12之后去Inspect一下会发现这一行代码被拆分为了三个Token。我有空看看这个问题是否可以解决。如果无法解决的话，建议你在WP Editor.md中换一个代码高亮的主题，或使用WordPress的自定义功能统一一下字号。

我测试的时候使用的是Dark代码高亮主题，实际效果如图所示，可供你参考：
![QQ20191122-005000](https://user-images.githubusercontent.com/29622423/69358613-17296900-0cc2-11ea-9baf-9e2e648fea3a.png)

**Comment by LuRenJiasWorld** [comment]
> 更新到10.0.6了，刚那个问题是没问题了，但现在又有新问题，代码中的反斜杠你也给解析了啊，windows的路径都是反斜杠啊，现在都被解析了：
> ![image](https://user-images.githubusercontent.com/13575500/65217592-1b30e300-dae7-11e9-93c6-5278e60aec3c.png)
> 
> 看，反斜杠全没了：
> ![image](https://user-images.githubusercontent.com/13575500/65217684-5c28f780-dae7-11e9-8d16-60ee0d531380.png)

目前应该已经没有这个问题了？
