### ISSUE TITLE
使用该插件后后台页面TTFB时间显著增加

### ISSUE THREAD

**Issue by seahurt** [LuRenJiasWorld/WP-Editor.md#358]
未启动该插件时，wp-admin页面加载的TTFB时间在200ms以内，启动该插件后，时间增长到1s以上，最长达到过5s。

希望可以改进一下，谢谢！

10.0.5版本， wordpress 5.2.3  Chrome浏览器76.0.3809.132

网络为内部局域网， 主机为KVM虚拟机， Centos7.5,  4 CPU， 4G内存, wordpress运行在docker中

**Comment by LuRenJiasWorld** [comment]
这可能是因为在使用了该插件后网页体积增大导致的。

经过本地测试，开启插件前后的页面体积为：

开启插件前：53次请求 / 352KB(After Gzip) / 1.1MB(Before Gzip)
开启插件后：83次请求 / 788KB(After Gzip) / 2.5MB(Before Gzip)

可以看到开启插件后网页体积是之前的约220%，在这个过程中，该插件也存在大量的钩子注入。

我本地的环境为双核2G内存，性能在可容忍范围内，通常加载wp-admin首页时间在1.2s左右。

性能的确可以继续提升，但这可能需要足够的时间进行优化。请等待更新。
