### ISSUE TITLE
10.0.5版本代码格式错误。

### ISSUE THREAD

**Issue by it404p** [LuRenJiasWorld/WP-Editor.md#364]
编辑时，预览正确，如下图：
![image](https://user-images.githubusercontent.com/54975297/66025608-79b78180-e529-11e9-8deb-073793ac2054.png)

但是发布完成之后，到文章页面再看代码，就是这种格式了：
![image](https://user-images.githubusercontent.com/54975297/66025650-9358c900-e529-11e9-8ded-e9a0c3c858ce.png)

**Comment by LuRenJiasWorld** [comment]
你好，可以给一个你这篇文章的预览链接吗，我看一下相关JS加载与HTML渲染是否正确。
