### ISSUE TITLE
https网站无法加载MindMap.min.js

### ISSUE THREAD

**Issue by cj96248** [LuRenJiasWorld/WP-Editor.md#368]
升级到10.0.7版本以后，突然发现无法编辑了。也可能是我将网站升级到了https导致的。观察了控制台，谷歌浏览器给的错误是`(blocked:mixed-content)`。
静态资源可以在后台配置`编辑器静态资源地址`，但是亲测修改无效，在数据库表`wp_options`中看到了`editor_mindmap`用的是http请求的，而谷歌浏览器禁止https网站加载http数据。
于是手动修改了数据值：
`update wp_options set option_value='a:4:{s:11:"theme_style";s:7:"default";s:10:"code_style";s:7:"default";s:13:"editor_addres";s:50:"https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.7";s:17:"customize_mindmap";s:80:"https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.7/assets/MindMap/mindMap.min.js";}' where option_name='editor_mindmap';`

希望作者注意到之前用的值为`10.0.5`而且schema为**http**.

**Comment by Nicr0n** [comment]
我也是碰到了同样的问题，折腾了一天才发现问题

**Comment by LuRenJiasWorld** [comment]
Fixed in #385
