### ISSUE TITLE
开启了让编辑器粘贴图像，但是直接从浏览器选择复制图片，到编辑粘贴无反应

### ISSUE THREAD

**Issue by somta** [LuRenJiasWorld/WP-Editor.md#369]

**Comment by LuRenJiasWorld** [comment]
请提供一下你的操作系统与浏览器环境信息，方便进行排查。

**Comment by somta** [comment]
直接使用谷歌浏览器，选一个图片复制，然后到编辑器粘贴就无法粘贴，如果是别人通过微信发过来的图片复制粘贴就可以------------------ 原始邮件 ------------------
发件人: "Benjamin Chris"<notifications@github.com>
发送时间: 2019年11月26日(星期二) 下午5:35
收件人: "LuRenJiasWorld/WP-Editor.md"<WP-Editor.md@noreply.github.com>;
抄送: "somta"<305123882@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [LuRenJiasWorld/WP-Editor.md] 开启了让编辑器粘贴图像，但是直接从浏览器选择复制图片，到编辑粘贴无反应 (#369)



请提供一下你的操作系统与浏览器环境信息，方便进行排查。
 
&mdash;

**Comment by LuRenJiasWorld** [comment]
是Windows+Chrome吗？

**Comment by somta** [comment]
是的------------------ 原始邮件 ------------------
发件人: "Benjamin Chris"<notifications@github.com>
发送时间: 2019年11月26日(星期二) 下午5:40
收件人: "LuRenJiasWorld/WP-Editor.md"<WP-Editor.md@noreply.github.com>;
抄送: "somta"<305123882@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [LuRenJiasWorld/WP-Editor.md] 开启了让编辑器粘贴图像，但是直接从浏览器选择复制图片，到编辑粘贴无反应 (#369)



是Windows+Chrome吗？
 
&mdash;

**Comment by LuRenJiasWorld** [comment]
请参考此篇Pull Request：#386 ，该功能限于浏览器的具体实现，无法保证所有平台上可以使用，很抱歉带来不便。

我将会密切跟进相关API与Hacking策略，尽快解决这一问题。

**Comment by somta** [comment]
后来找到一款非常类似的功能的编辑器实现了该功能你可以参考一下WP Githuber MD------------------ 原始邮件 ------------------
发件人: "Benjamin Chris"<notifications@github.com>
发送时间: 2019年11月26日(星期二) 下午5:43
收件人: "LuRenJiasWorld/WP-Editor.md"<WP-Editor.md@noreply.github.com>;
抄送: "somta"<305123882@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [LuRenJiasWorld/WP-Editor.md] 开启了让编辑器粘贴图像，但是直接从浏览器选择复制图片，到编辑粘贴无反应 (#369)



请参考此篇Pull Request：#386 ，该功能限于浏览器的具体实现，无法保证所有平台上可以使用，很抱歉带来不便。
 
我将会密切跟进相关API与Hacking策略，尽快解决这一问题。
 
&mdash;

**Comment by LuRenJiasWorld** [comment]
感谢，我有空了会参考一下的！
