### ISSUE TITLE
使用编辑器发布文档，未生效

### ISSUE THREAD

**Issue by meibin08** [LuRenJiasWorld/WP-Editor.md#373]
文档插件使用的wedocs,

编写后发布，内容未正常展示，如下图：
![image](https://user-images.githubusercontent.com/18324563/67343839-ffe34880-f568-11e9-928f-2d2015ab4975.png)

## 求解：
使用[WP Githuber MD](https://github.com/terrylinooo/githuber-md),则又正常，
但没有这插件好用，所以请教一下，是否能兼容？

## 补充：
在发布之前，点预览内容，又是正常的～

**Comment by LuRenJiasWorld** [comment]
你好，有尝试过检查插件/主题兼容性吗？或更新到最新版后重试。

**Comment by pincman** [comment]
@meibin08 请问此问题解决了吗？遇到了同样的问题
