### ISSUE TITLE
第二次编辑文章编辑器区之前编辑的所有markdown都变成了html代码

### ISSUE THREAD

**Issue by frinck** [LuRenJiasWorld/WP-Editor.md#374]
![image](https://user-images.githubusercontent.com/22429114/67570920-266dd300-f765-11e9-9b7f-55cdcfb10837.png)

**Comment by LuRenJiasWorld** [comment]
你好，可以提供一个可复现的Demo账号，或者相信描述一下你的操作过程吗？我没有能复现出你所说的问题，在我的测试环境与全新安装的WordPress环境中，编辑功能是正常的。

**Comment by dogifyc** [comment]
我把所有插件都禁用了，然后挨个启用，发现没这个问题了。。可能是jetpack或其他插件的问题。。

**Comment by LuRenJiasWorld** [comment]
好的，如果有其他问题欢迎继续反馈。我先关闭掉这个Issue。
