### ISSUE TITLE
LaTeX 有锅

### ISSUE THREAD

**Issue by xht37** [LuRenJiasWorld/WP-Editor.md#375]
LaTeX 似乎有不少锅，比如上下标无法正常显示之类的，之前都没有这些问题......

**Comment by LuRenJiasWorld** [comment]
可以给一篇包含你所述LaTeX问题的示例Markdown文本吗？这样对于问题复现会有帮助。

**Comment by xht37** [comment]
https://www.xht37.com/cf566c-logistical-questions-%e9%a2%98%e8%a7%a3/

这篇博客「题解」部分倒数第二段公式为 $\sum_{j=1}^k p_j – 2p_i$ 但并没有正常显示上下标

**Comment by LuRenJiasWorld** [comment]
请换一个前台主题试试看？我这边没有遇到问题。LaTeX功能的实现原理是将LaTeX变成HTML，然后套用一个CSS将其格式化。如果你前台主题覆盖了部分CSS样式，就很容易出现这样的情况。

我后面尝试参考一下知乎的LaTeX生成方案，做成直接生成图片的方式，这样应该会解决这个兼容性问题。[参考](https://www.zhihu.com/equation?tex=%5Cfrac%7B2%5En%7D%7Bn+%5Clog+e%7D-%5Cfrac%7B2%5E%7Bn-1%7D%7D%7B%28n-1%29+%5Clog+e%7D%5Capprox%5Cfrac%7B%28n-1%292%5En-%5Cfrac%7Bn%7D%7B2%7D2%5En%7D%7Bn%28n-1%29+%5Clog+e%7D%3D%5Cfrac%7Bn-2%7D%7Bn%28n-1%29+%5Clog+e%7D2%5E%7Bn-1%7D)

**Comment by LuRenJiasWorld** [comment]
对了，还有一种情况：你可能在设置中选择了MathJax。MathJax目前有不少的BUG，不推荐使用，如果是这样的话，你换用Katex看看？可能就能解决你的问题了。

**Comment by xht37** [comment]
换成 Katex 就好了，感谢

**Comment by xht37** [comment]
但是 KaTeX 似乎不能显示

$$
\begin{aligned}
\sum_{n \ge 0} [n = 0] x^n &= 1 \\\\
\sum_{n \ge 0} [n = m] x^n &= x^m \\\\
\end{aligned}
$$

这样的东西？

**Comment by LuRenJiasWorld** [comment]
是这样的吗？似乎没有问题。
<img width="1410" alt="QQ20191127-165133@2x" src="https://user-images.githubusercontent.com/29622423/69708263-3c8cfb80-1136-11ea-8570-7fd92641f16c.png">

**Comment by LuRenJiasWorld** [comment]
你可以截图一下你这边的结果，我看看什么情况。

**Comment by xht37** [comment]
[链接](https://www.xht37.com/%e6%99%ae%e9%80%9a%e5%9e%8b%e7%94%9f%e6%88%90%e5%87%bd%e6%95%b0-%e5%ad%a6%e4%b9%a0%e7%ac%94%e8%ae%b0/#OGF1)

KaTeX 效果：

![_U_GOX5_RUA1____DJI_4IG.png](https://i.loli.net/2019/11/27/eh7z8yBtbUI6DH3.png)

md 代码：

```md
### 常见 OGF

常见的 OGF 通常可以用一个更加简单的式子代替。

#### $x^m$

$$
\begin{aligned}
\sum_{n \ge 0} [n = 0] x^n &= 1 \\\\
\sum_{n \ge 0} [n = m] x^n &= x^m \\\\
\end{aligned}
$$

#### $(1 + x)^m$

$$
\begin{aligned}
\sum_{n \ge 0} x^n &= \frac 1{1 - x} \\\\
\sum_{n \ge 0} nx^n &= \frac 1{(1 - x)^2} \\\\
\sum_{n \ge 0} (-1)^n x^n &= \frac 1{1 + x} \\\\
\sum_{n \ge 0} \binom mn x^n &= (1 + x)^m \\\\
\sum_{n \ge 0} \binom {n+m-1}n x^n &= (1 - x)^{-m} \\\\
\end{aligned}
$$

#### $e$ 相关

$$
\begin{aligned}
\sum_{n > 0} \frac{1}{n} x^n &= \ln\frac1{1-x} \\\\
\sum_{n > 0} \frac{-(-1)^n}{n} x^n &= \ln(1+x) \\\\
\sum_{n \ge 0} \frac{1}{n!} x^n &= e^x \\\\
\end{aligned}
$$
```

**Comment by xht37** [comment]
（现在已经换成 MathJax）

**Comment by LuRenJiasWorld** [comment]
> （现在已经换成 MathJax）

好的，不过MathJax有一点小BUG，我争取圣诞节前修复完毕，发布MathJax与KaTeX均工作正常的版本。

**Comment by xht37** [comment]
好的，感谢
