### ISSUE TITLE
图床无法返回正确的内容

### ISSUE THREAD

**Issue by qiudaozhang** [LuRenJiasWorld/WP-Editor.md#377]
粘贴图片，上传sm.ms，返回如下图

![image](https://user-images.githubusercontent.com/34365540/68557816-f7987200-0471-11ea-9a7e-e4a2ccff0c29.png)

返回状态信息：

![image](https://user-images.githubusercontent.com/34365540/68557844-11d25000-0472-11ea-8d51-193bf078308a.png)

但是无法正确回写。

**Comment by LuRenJiasWorld** [comment]
请问可以补充一下返回的body吗？
