### ISSUE TITLE
toc有时候生效有时候不生效。

### ISSUE THREAD

**Issue by qiudaozhang** [LuRenJiasWorld/WP-Editor.md#378]
添加代码`[toc]`，有时候无效果，比如。
![image](https://user-images.githubusercontent.com/34365540/68601733-e38b5980-04df-11ea-94dc-7672b2cb4efc.png)
有时候you又有效，比如：

![image](https://user-images.githubusercontent.com/34365540/68601775-fe5dce00-04df-11ea-896f-dd27ea231fa0.png)

**Comment by LuRenJiasWorld** [comment]
确认已经安装Table of Contents Plus插件了吗？该功能是通过第三方插件提供的，你可以切换到原生编辑器，再使用toc功能看看是否工作正常，如果依旧存在你所遇到的情况，那么可能与该插件无关。

如果经过核实发现该问题只在使用该编辑器的时候出现，请详细描述一下你的环境配置与对应的插件版本，便于问题复现。
