### ISSUE TITLE
「此插件与您的WordPress版本的兼容性没有被测试」

### ISSUE THREAD

**Issue by xht37** [LuRenJiasWorld/WP-Editor.md#379]
与最新版 WordPress 不兼容

**Comment by LuRenJiasWorld** [comment]
你可以先使用wp-downgrade插件降级到WordPress 5.2版本，然后静候开发者更新。

根据报错信息分析，可能是因为WordPress5.3不再暴露jQuery的`$`函数。

**Comment by LuRenJiasWorld** [comment]
Update：请参阅https://github.com/JaxsonWang/WP-Editor.md/pull/383，对代码进行修改。修改后兼容性问题将会得到解决，但可能会依旧提示不兼容。

目前尚未针对该问题发布更新，请稍等后续更新彻底解决该问题。

**Comment by LuRenJiasWorld** [comment]
你好，目前已经发布了`v10.0.8`版本对该问题进行解决，请自行更新到最新版即可解决该Issue的问题。
