### ISSUE TITLE
使用过程中发现的bug，希望更新

### ISSUE THREAD

**Issue by geekcat99** [LuRenJiasWorld/WP-Editor.md#384]
1. markdown 语法表格 无法在网页端显示成表格，网页解析不对。
2. 代码块
···
!= 
···
在网页端不能正确解析
3. markdown 制作的目录索引 如：[介绍](#介绍)，在网页端无法跳转。

**Comment by LuRenJiasWorld** [comment]
可以针对你所提到的三个问题，给出相关的代码/示例页面吗？你所提到的三个功能应该都是工作正常的。

**Comment by geekcat99** [comment]
> 可以针对你所提到的三个问题，给出相关的代码/示例页面吗？你所提到的三个功能应该都是工作正常的。
markdown 代码块如下：
```HTML
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
</body>
</html>
```
网页端显示
![image](https://user-images.githubusercontent.com/44596384/69314788-f6d0be80-0c6f-11ea-903d-f1a32904967f.png)

**Comment by LuRenJiasWorld** [comment]
> > 可以针对你所提到的三个问题，给出相关的代码/示例页面吗？你所提到的三个功能应该都是工作正常的。
> > markdown 代码块如下：
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
> 	<title></title>
> </head>
> <body>
> </body>
> </html>
> ```
> 
> 网页端显示
> ![image](https://user-images.githubusercontent.com/44596384/69314788-f6d0be80-0c6f-11ea-903d-f1a32904967f.png)

你的markdown代码块格式前后有没有使用反引号包起来？
如果是要显示高亮代码块，正确的方式应该如图所示：

![QQ20191122-002504](https://user-images.githubusercontent.com/29622423/69356563-9ddc4700-0cbe-11ea-909b-a2888cb5cd5b.png)
![QQ20191122-002514](https://user-images.githubusercontent.com/29622423/69356577-a59beb80-0cbe-11ea-81a9-73ccfb1c7a4c.png)

此外，看你的截图是代码被转义成了html entities了，可能是使用的主题/插件在输出文本时候为避免XSS攻击，对相关的字符进行了转义处理（使用`htmlspecialchars()`函数）。

如果你一定要在markdown文档中插入html，请注意以下两点，可能会帮助你解决你遇到的问题：
1. 在WP Editor.md的设置中启用`支持HTML`功能
2. 尝试对你所启用的插件和主题进行排除检查

如果还有什么其他问题，欢迎继续反馈。

**Comment by geekcat99** [comment]
![image](https://user-images.githubusercontent.com/44596384/69523995-1c2b3880-0fa0-11ea-9886-e6a1815b6e25.png)
![image](https://user-images.githubusercontent.com/44596384/69524024-29482780-0fa0-11ea-8e11-ff2fb54e1f94.png)
![image](https://user-images.githubusercontent.com/44596384/69524037-2d744500-0fa0-11ea-8714-e4391567cfad.png)
显示不正常，上次截图没有截取完整

**Comment by LuRenJiasWorld** [comment]
你好，符号用错了，不是单引号，是反引号，数字1左边的、esc下面的。

**Comment by geekcat99** [comment]
> 你好，符号用错了，不是单引号，是反引号，数字1左边的、esc下面的。

你好，那个不是单引号，是Esc下面的符号

**Comment by LuRenJiasWorld** [comment]
> > 你好，符号用错了，不是单引号，是反引号，数字1左边的、esc下面的。
> 
> 你好，那个不是单引号，是Esc下面的符号

有尝试过换用其他主题吗，比如WordPress自带的？

**Comment by geekcat99** [comment]
> > > 你好，符号用错了，不是单引号，是反引号，数字1左边的、esc下面的。
> > 
> > 
> > 你好，那个不是单引号，是Esc下面的符号
> 
> 有尝试过换用其他主题吗，比如WordPress自带的？

![image](https://user-images.githubusercontent.com/44596384/69526710-c8bbe900-0fa5-11ea-87df-d5b8f6cef5be.png)


尝试了很多主题，都解析不了

**Comment by LuRenJiasWorld** [comment]
> > > > 你好，符号用错了，不是单引号，是反引号，数字1左边的、esc下面的。
> > > 
> > > 
> > > 你好，那个不是单引号，是Esc下面的符号
> > 
> > 
> > 有尝试过换用其他主题吗，比如WordPress自带的？
> 
> ![image](https://user-images.githubusercontent.com/44596384/69526710-c8bbe900-0fa5-11ea-87df-d5b8f6cef5be.png)
> 
> 尝试了很多主题，都解析不了

[这就很奇怪了，因为我这边实在无法复现，而且最近其他用户没有反馈这个问题。但可以肯定的是特殊符号被转义了，问题大概率可能出在与其他插件、主题的兼容性上，你可以再试试看。如果还是不行，给你一个简单的处理方法：在你模板的`single.php`中使用[htmlspecialchars_decode()](https://www.php.net/manual/zh/function.htmlspecialchars-decode.php)函数对被转义的字符进行反转义。

如果还是无法解决，你可以考虑用子目录的方式开一个新的WordPress，安装好对应环境与插件，然后将账号密码发至我的email：loli@lurenjia.in，我来协助处理一下。

**Comment by geekcat99** [comment]
我是用的主题: Tusi版本：1.0.7

**Comment by geekcat99** [comment]
不好意思找到问题了，该插件  Crayon Syntax Highlighter （Crayon语法显示）引起显示乱码

**Comment by LuRenJiasWorld** [comment]
> 不好意思找到问题了，该插件 Crayon Syntax Highlighter （Crayon语法显示）引起显示乱码

没关系，WordPress插件的相互兼容性一直是个大问题，互相干扰的事情时常发生。如果遇到了奇怪的问题，通常可以关闭所有插件，换用官方主题，然后一个一个打开并检查来排障。
