### ISSUE TITLE
WordPress 5.3 点击选项卡无反应

### ISSUE THREAD

**Issue by DeEpinGh0st** [LuRenJiasWorld/WP-Editor.md#387]
### 点击选项卡只显示捐助页面  
![20191122151706](https://user-images.githubusercontent.com/34375573/69406136-48467f80-0d3c-11ea-97db-98f83774a312.png)

**Comment by LuRenJiasWorld** [comment]
请打开开发者工具的Console面板，查看一下是否有报错信息。如果有报错信息，请截图发一下。

**Comment by Abreto** [comment]
同样的问题，似乎没有报错
![image](https://user-images.githubusercontent.com/1196941/69493641-ff352d80-0eeb-11ea-931e-cc807d9faeea.png)

**Comment by Abreto** [comment]
喔，似乎是这个问题 https://github.com/JaxsonWang/WP-Editor.md/issues/380

**Comment by LuRenJiasWorld** [comment]
> 喔，似乎是这个问题 #380

好的，解决方法请参考 https://github.com/JaxsonWang/WP-Editor.md/pull/383
目前作者尚未发布更新，请手动解决

**Comment by DeEpinGh0st** [comment]
暂时缓解措施博主们可安装jQuery-WP53-Fix插件解决
https://github.com/LuRenJiasWorld/jQuery-WP53-Fix
