### ISSUE TITLE
添加一个新页面“说说”，markdonw语法直接原样输出

### ISSUE THREAD

**Issue by moshanghan** [LuRenJiasWorld/WP-Editor.md#388]
![image](https://user-images.githubusercontent.com/30591457/69493851-f42fcc80-0eee-11ea-81fe-b324e4a87878.png)
在wordpress中开了一个新功能-说说
编辑文章输入md语法后，直接以md语法输出了如图
用wordpress自带编辑器没问题，
需要什么额外配置吗？
救助

**Comment by LuRenJiasWorld** [comment]
可以具体描述一下你这个新功能的实现机制吗？

**Comment by moshanghan** [comment]
就是加了一个模板，把文章内容放进去
```php
      <section id="main" class='<?php echo ($page_side_bar == 'single') ? 'col-md-12' : 'col-md-8'; ?>'>
        <div class="shuoshuo">
          <ul class="archives-monthlisting">
            <?php query_posts("post_type=shuoshuo&post_status=publish&posts_per_page=-1");
            if (have_posts()) : while (have_posts()) : the_post(); ?>
                <li><span class="tt"><?php the_time('Y年n月j日G:i'); ?></span>
                  <div class="shuoshuo-content"><?php the_title(); ?>
                  <?php the_content(); ?>
                  </div><?php endwhile;
                        endif; ?>
                </li>
          </ul>
        </div>
      </section>
```

**Comment by LuRenJiasWorld** [comment]
请查一下数据库中post表，查看一下`post_content`与`post_content_filtered`字段。

通常来说，前者会存储渲染后的HTML，后者会存储Markdown原文本，你可以查看一下情况是否如此。

- 如果情况并非如此，请重新安装本插件，或者检查与其他插件是否存在功能冲突。

- 如果情况如此，但该问题仍未得到解决，我的建议是使用如下代码自定义`the_content()`函数的行为，让其指向`post_content`字段：

```php
echo apply_filters('the_content', get_post_field('post_content', get_the_ID()));
```

> 代码可能根据你模板实现与上下文的不同存在不适配的情况，仅作为建议，希望能给你思路。

但你所反馈的Issue似乎与本插件无关，目前没有在其他Issue中遇到过这个情况。

如果尝试后还未解决，并且确定是本插件引起的兼容性问题，欢迎继续反馈。

**Comment by moshanghan** [comment]
post_content这里是md
post_content_filtered是空的

我删除再次安装
![image](https://user-images.githubusercontent.com/30591457/70391953-6e933d00-1a15-11ea-83c1-91a798ab4340.png)

**Comment by LuRenJiasWorld** [comment]
> post_content这里是md
> post_content_filtered是空的
> 
> 我删除再次安装
> ![image](https://user-images.githubusercontent.com/30591457/70391953-6e933d00-1a15-11ea-83c1-91a798ab4340.png)

难怪，post_content_filtered里面应该是md，post_content应该是渲染出来的html才对。

504错误是因为你服务器所处网络环境连接WordPress服务器不通畅导致的，你可以尝试直接在GitHub上下载Release包然后手动上传，或考虑配置php/php-fpm延长脚本超时时间。

**Comment by moshanghan** [comment]
您好，我通过github重新完成了安装，
需要怎么做才能处理上面的问题呢？

**Comment by LuRenJiasWorld** [comment]
> 您好，我通过github重新完成了安装，
> 需要怎么做才能处理上面的问题呢？

只能手动修正。你尝试一下在数据库中把post_content的md复制到post_content_filtered，然后进入WordPress后台，手动更新每一篇文章触发markdown渲染试试看。或者你也可以直接复制每篇文章在数据库中的md文本，逐一新建。

目前我没有获取到足够的信息，无法确认这是BUG还是兼容性问题，建议你先手动处理一下，将来如果有类似的问题出现，我会尽量给予修复。
