### ISSUE TITLE
未解析数学公式

### ISSUE THREAD

**Issue by Abreto** [LuRenJiasWorld/WP-Editor.md#389]
升级5.3后，数学公式都没有解析了，全是原样输出
![image](https://user-images.githubusercontent.com/1196941/69493998-28a48800-0ef1-11ea-897a-176b27054554.png)

**Comment by LuRenJiasWorld** [comment]
请打开开发者工具的console，查看是否有报错，有的话请截图反馈

**Comment by Abreto** [comment]
![image](https://user-images.githubusercontent.com/1196941/69494100-81c0eb80-0ef2-11ea-8035-64d516456bb7.png)

**Comment by LuRenJiasWorld** [comment]
请参考 https://github.com/JaxsonWang/WP-Editor.md/pull/383 对你的插件进行修改，新版本将于不久后发布。如果修改后还有问题，请继续反馈。

**Comment by Abreto** [comment]
这是已经修改后的样子了

**Comment by LuRenJiasWorld** [comment]
> 这是已经修改后的样子了

请排查一下是否是其他插件引发的报错，5.3版本做了比较大的改动，导致大量插件出现问题。本插件似乎没有使用到报错中所述的js文件。

此外，请检查一下是否在设置中启动了对LaTeX的支持，需要注意的是目前仅支持Katex插件，mathjax暂不受支持。

如果需要近一步排查问题，请下载https://github.com/JaxsonWang/WP-Editor.md/issues/381 中的代码，然后截图输出结果发上来看看。

**Comment by Abreto** [comment]
禁用其他所有插件后无报错了（还剩一个Warning），但仍然没有解析数学公式

**Comment by Abreto** [comment]
哦不好意思，估计是升级导致设置变了，重新开启后好了
