### ISSUE TITLE
内容包含`$`就会没有输出

### ISSUE THREAD

**Issue by Abreto** [LuRenJiasWorld/WP-Editor.md#390]
如果内容包括 \`$\` （我想显示`$`），那么整个页面将没有输出

![image](https://user-images.githubusercontent.com/1196941/69737426-57c82d00-116f-11ea-92c4-62f33ca7890a.png)

![image](https://user-images.githubusercontent.com/1196941/69737521-7c240980-116f-11ea-84f0-5354cb51750d.png)

控制台无关于此插件的输出

**Comment by LuRenJiasWorld** [comment]
请参考 #359 ，很抱歉是代码逻辑的错误导致此问题，将在下一个版本予以修复。临时解决方法是关闭LaTeX功能。

**Comment by LuRenJiasWorld** [comment]
或者你可以暂时参考 https://github.com/LuRenJiasWorld/WP-Editor.md/commit/0f06731bfda364225dea74bac55c9d5d6114fc37 对你本地插件进行修改。
