### ISSUE TITLE
在List中嵌套的代码块退化为行内代码的问题

### ISSUE THREAD

**Issue by Creling** [LuRenJiasWorld/WP-Editor.md#392]
插件版本：10.0.8

![图片](https://user-images.githubusercontent.com/43109504/69910864-605d8380-144d-11ea-90dc-52c615b44f31.png)
红框内部分，希望被解析为：
```html
<pre><code class="language-shell line-numbers">vi /etc/grub.conf
</code></pre>
```
实际上被解析为：
![图片](https://user-images.githubusercontent.com/43109504/69910868-78350780-144d-11ea-90be-ccf8864468ab.png)
这就使得这一部分的最终渲染效果变成了行内代码而非是代码块。
![图片](https://user-images.githubusercontent.com/43109504/69910854-2db38b00-144d-11ea-89fd-b35b6ca8d02a.png)
希望作者大大能够修复
另外，在编辑器中的渲染是正确的：
![图片](https://user-images.githubusercontent.com/43109504/69910858-3f952e00-144d-11ea-9747-ba3326aff570.png)

**Comment by LuRenJiasWorld** [comment]
好的，问题可以重现，我最近解决一下，然后月底发布新版本。

解决后我会更新此Issue，附带相关Commit，这样你可以提前使用到该功能修复后的本插件。

**Comment by LuRenJiasWorld** [comment]
非常抱歉，由于私人原因，修复拖到了现在，你可以参考 https://github.com/LuRenJiasWorld/WP-Editor.md/commit/c485d936f311d06d313ef616e1fbc6ba20b5380e 解决你所提出的问题，或等待下一版本更新。
