### ISSUE TITLE
博客长公式显示bug？？？

### ISSUE THREAD

**Issue by SadAngelF** [LuRenJiasWorld/WP-Editor.md#393]
一些短小的公式没有问题，但是涉及到比较长的公式，我会编辑出错，例如下图这种情况；
同样，似乎\begin{aligned}这个没有被识别出来，从而无法换行

![image](https://user-images.githubusercontent.com/30397250/70117729-1bca2600-16a1-11ea-9852-cd08f9f3d495.png)

**Comment by SadAngelF** [comment]
附上原始的md代码部分：同样，即使没有使用aligned，一些相对长一点的公式也不能被正确显示

<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({ tex2jax: {inlineMath: [['$', '$']]}, messageStyle: "none" });
</script>

$$
\begin{aligned}
I^2&=\int^{2\pi}_0\int^{\infty}_0{exp(-\frac{r^2}{2\sigma^2})}rdrd\theta \\\
&=2\pi\int^{\infty}_{0}exp(-\frac{r^2}{2\sigma^2})(-\sigma^2)d(-\frac{r^2}{2\sigma^2})\\\
&=-2\pi\sigma^2\int^{-\infty}_{0}{e^t}dt \\\
&=2\pi\sigma^2
\end{aligned}
$$

**Comment by LuRenJiasWorld** [comment]
你好，请问你的LaTeX配置是？使用的是Katex还是Mathjax？

**Comment by SadAngelF** [comment]
哈哈哈哈，谢谢你啦，好像是因为我之前没有开启这个功能，现在我选择了Katex之后，公式显示正常了
