### ISSUE TITLE
如何使得编辑器默认为unwatch选项(即显示markdown文本，不显示富文本界面)

### ISSUE THREAD

**Issue by shengqiangzhang** [LuRenJiasWorld/WP-Editor.md#394]
![image](https://user-images.githubusercontent.com/28225826/70505933-364e4480-1b64-11ea-9e26-688a49d7e77f.png)

如上图所示，如何使得编辑器默认为纯markdown界面，而不是markdown界面和富文本界面？
如果可以，麻烦说一下需要更改哪个文件？谢谢！

**Comment by LuRenJiasWorld** [comment]
请查看设置页面。关闭实时预览选项。

**Comment by shengqiangzhang** [comment]
谢谢，已解决。

**Comment by yomige** [comment]
此选项是不是不起作用了？取消勾选后，默认还是显示预览
![image](https://user-images.githubusercontent.com/4659346/95155001-bade1380-07c5-11eb-9c3d-42ea0c0d0958.png)

![image](https://user-images.githubusercontent.com/4659346/95155034-cd584d00-07c5-11eb-9bfb-412a4c4a67b8.png)

![image](https://user-images.githubusercontent.com/4659346/95155054-da753c00-07c5-11eb-9f3b-6bf3588986cd.png)

**Comment by LuRenJiasWorld** [comment]
> 此选项是不是不起作用了？取消勾选后，默认还是显示预览
> ![image](https://user-images.githubusercontent.com/4659346/95155001-bade1380-07c5-11eb-9c3d-42ea0c0d0958.png)
> 
> ![image](https://user-images.githubusercontent.com/4659346/95155034-cd584d00-07c5-11eb-9bfb-412a4c4a67b8.png)
> 
> ![image](https://user-images.githubusercontent.com/4659346/95155054-da753c00-07c5-11eb-9f3b-6bf3588986cd.png)

经检查，该选项的确出现了问题，我先看看是什么因素导致的。

**Comment by LuRenJiasWorld** [comment]
@winbertw 你好，该问题已于 https://github.com/LuRenJiasWorld/WP-Editor.md/commit/9448d24d79b92d2ec8b9352741713d1676a477f6 解决，将会在11月初的10.3.0版本发布相关修复，届时更新到最新版即可解决此问题。非常抱歉带来不便。
