### ISSUE TITLE
您好，怎样使得 bbpress 也可以使用您的插件？

### ISSUE THREAD

**Issue by leonzai** [LuRenJiasWorld/WP-Editor.md#396]

**Comment by LuRenJiasWorld** [comment]
你好，本插件暂未兼容bbpress插件。

我粗略看了一下bbpress的开发文档，发现其并未直接调用WordPress原生文章管理/显示组件，而本插件的核心功能依赖之，这意味着如果要兼容bbpress，可能要做很多改动。目前我的精力有限，需要将大部分时间花在性能优化与兼容性改善上，可能抽不出这么多时间，很抱歉带来不便。

如果你有足够的开发能力，可以对该插件进行二次开发以适配你的需求，届时欢迎提交Pull Request。如果有较多用户提出这一需求，我可能会考虑增加该功能，但目前无能为力。
