### ISSUE TITLE
10.0.8 一直提示资源过时

### ISSUE THREAD

**Issue by LiuDanK** [LuRenJiasWorld/WP-Editor.md#398]
删除重新安装亦是如此

**Comment by LuRenJiasWorld** [comment]
你好，请截图让我看一下你的这一页配置情况：

<img width="904" alt="QQ20191225-162933@2x" src="https://user-images.githubusercontent.com/29622423/71439235-c4652600-2733-11ea-9d97-0d1396773cce.png">

**Comment by LiuDanK** [comment]
Benjamin Chris
        您好！我已收到您的邮件。
        


你好,问题已解决,升级PHP版本后问题消失
        有什么问题随时与我联系和沟通，祝好！


2019-12-26
| |
劉亞坤
|
|
13140659949@163.com
|
签名由网易邮箱大师定制
在2019年12月25日 16:29，Benjamin Chris<notifications@github.com> 写道：

你好，请截图让我看一下你的这一页配置情况：

**Comment by LuRenJiasWorld** [comment]
好的，后续有问题欢迎继续反馈！
