### ISSUE TITLE
php7.4报错

### ISSUE THREAD

**Issue by TouiSoraHe** [LuRenJiasWorld/WP-Editor.md#399]
PHP 7.4: The array and string offset access syntax using curly braces is deprecated  in /www/wwwroot/xxxxxxxx/wp-content/plugins/wp-editormd/src/App/WPMarkdownParser.php on line 388

**Comment by LuRenJiasWorld** [comment]
感谢你的报告，我自己目前用的还是PHP7.2，没有看到这个信息。

针对这个问题的修复将于下个版本发布，目前你可以先关闭php.ini中的Deprecation Warning，临时解决一下。

问题解决后我会更新此Issue。

**Comment by TouiSoraHe** [comment]
> 感谢你的报告，我自己目前用的还是PHP7.2，没有看到这个信息。
> 
> 针对这个问题的修复将于下个版本发布，目前你可以先关闭php.ini中的Deprecation Warning，临时解决一下。
> 
> 问题解决后我会更新此Issue。

好哒！我已经将php版本降到7.3了！

**Comment by LuRenJiasWorld** [comment]
你好，该问题在 https://github.com/LuRenJiasWorld/WP-Editor.md/commit/6370aae7c4512714c2e823033b4a344c95ca43d4 中已得到修复，再次感谢反馈！
