### ISSUE TITLE
思维导图mindMap.min.js打不开了

### ISSUE THREAD

**Issue by NoBackward** [LuRenJiasWorld/WP-Editor.md#401]
//cdn.jsdelivr.net/wp/wp-editormd/trunk/assets/Editormd/lib/mindMap.min.js

**Comment by LuRenJiasWorld** [comment]
地址已更换为`//cdn.jsdelivr.net/wp/wp-editormd/trunk/assets/MindMap/mindMap.min.js`，请更换。
