### ISSUE TITLE
网页显示问题

### ISSUE THREAD

**Issue by Helpayment** [LuRenJiasWorld/WP-Editor.md#402]
HTML标签在makedown中显示正常，发布到博客上面直接成了效果
![9Z{X{QUJ296VK 1C$T2TP)P](https://user-images.githubusercontent.com/32597550/71576291-20142280-2b2b-11ea-967b-449f303b9709.png)

![BAW@IVA0HOF{0 ANF%_ )F5](https://user-images.githubusercontent.com/32597550/71576293-20142280-2b2b-11ea-97bd-acc3afc78b1c.png)

**Comment by LuRenJiasWorld** [comment]
按道理说不应该是这样的，你有尝试过更换其他前台主题吗？没有的话可以先试试看。

此外，请检查一下你的插件兼容性，尝试只开启本插件，检查一下问题是否依旧存在。

如果问题依旧存在，麻烦把Markdown全文和你的配置截图发一下，我这边看看能不能复现。
