### ISSUE TITLE
为什么有的时候公式不渲染呢？

### ISSUE THREAD

**Issue by suzhc** [LuRenJiasWorld/WP-Editor.md#403]
![image](https://user-images.githubusercontent.com/35687481/71624437-8da07b80-2c1d-11ea-9663-02a420e2fc25.png)

**Comment by LuRenJiasWorld** [comment]
请问你在设置中启用的是MathJax模式还是Katex模式？

**Comment by suzhc** [comment]
两种模式都试过了，一个或者两个$也都试过了，简单的公式是没有问题的。个人猜会不会因为把公式里的_ _之类的作为markdown语句了呢？

**Comment by LuRenJiasWorld** [comment]
应该是不会的，你尝试一下使用代码的格式，也就是三个反引号后面带katex，如图所示：
<img width="79" alt="QQ20200101-134248@2x" src="https://user-images.githubusercontent.com/29622423/71638490-a734d800-2c9c-11ea-9cad-db41d8bb7a6c.png">
如果还是不行的话，麻烦发一下你的LaTeX原文，我这边看看是什么情况。

**Comment by LuRenJiasWorld** [comment]
<img width="967" alt="QQ20200101-134739@2x" src="https://user-images.githubusercontent.com/29622423/71638528-4bb71a00-2c9d-11ea-95bf-0cefeb48acf1.png">

**Comment by suzhc** [comment]
![image](https://user-images.githubusercontent.com/35687481/71638564-62aa3c00-2c9e-11ea-9d60-767bc67e5513.png)
在Typora中可以正常渲染
![image](https://user-images.githubusercontent.com/35687481/71638576-9c7b4280-2c9e-11ea-9ff8-9d26f57a11b8.png)
latex原文
```katex
\left\{\begin{array}{ll}
{u_{t t}=a^{2} u_{x x},} & {(t>0,0<x<l)} \\
{\left.u\right|_{x=0}=\left.u\right|_{x=l}=0,} & {(t \geq 0)} \\
{\left.u\right|_{t=0}=\varphi(x),\left.u_{t}\right|_{t=0}=\psi(x),} & {(0 \leq x \leq l)}
\end{array}\right.
```

**Comment by LuRenJiasWorld** [comment]
排查后发现是你所提供原文第二行`{(t>0,0<x<l)}`导致的报错，报错内容为：`Uncaught ParseError: KaTeX parse error: Expected '}', got 'EOF' at end of input: …x},} & {(t>0, 0`。

去掉这部分后即可正常显示。

<img width="852" alt="截屏2020-01-01下午2 13 22" src="https://user-images.githubusercontent.com/29622423/71638667-00066f80-2ca1-11ea-8bec-915e740365cb.png">

因为LaTeX解析是依靠第三方库实现的，我这边处理起来需要时间，你可以先修改掉这一行的内容应该就可以临时解决。问题根本解决后我会更新此Issue。

**Comment by suzhc** [comment]
非常感谢！另，新年快乐^_^

**Comment by LuRenJiasWorld** [comment]
好的:)，新年快乐！
