### ISSUE TITLE
文章评论框无法显示

### ISSUE THREAD

**Issue by 66Leo66** [LuRenJiasWorld/WP-Editor.md#404]
文章的评论框一直转圈加载，Console报错。
![image](https://i.loli.net/2020/01/01/OZS86kcqpf7bVT9.png)

**Comment by LuRenJiasWorld** [comment]
请尝试换用其他主题看看是否报错，目前本功能只在WordPress的官方主题下测试通过。

**Comment by 66Leo66** [comment]
官方二〇一九主题仍无法加载，报错如下：
![Console Message](https://i.loli.net/2020/01/01/T12SgKthcmrXG39.png)

**Comment by LuRenJiasWorld** [comment]
好的，我先记录一下，后续解决。

看样子是之前的某次修改导致这个功能失效，因为使用它的用户不是很多，没有注意到。

解决后我会更新此Issue。
