### ISSUE TITLE
预览窗口滚动条不同步

### ISSUE THREAD

**Issue by youralmight** [LuRenJiasWorld/WP-Editor.md#405]
总是要自己往下拖太麻烦了

**Comment by LuRenJiasWorld** [comment]
默认行为应该是左右两边的窗口同步滚动的，你遇到的情况是无法同步滚动吗？

麻烦给出相关截图方便分析。

**Comment by youralmight** [comment]
![image](https://user-images.githubusercontent.com/42952005/71783815-faa18000-3026-11ea-880e-51353427a068.png)
刚开始使用wordpress,暂时只启用了这一个插件

**Comment by LuRenJiasWorld** [comment]
似乎没能复现你的问题。请检查一下设置面板中的滚动同步预览功能是否启用？
<img width="1517" alt="QQ20200106-020044@2x" src="https://user-images.githubusercontent.com/29622423/71783924-70f2b200-3028-11ea-92a2-60c5c95a850c.png">

**Comment by youralmight** [comment]
我开启了这项设置，问题解决了
![image](https://user-images.githubusercontent.com/42952005/71783947-d8a8fd00-3028-11ea-823b-c26deb389af1.png)

**Comment by LuRenJiasWorld** [comment]
好的: )

**Comment by youralmight** [comment]
感谢你快速的回复！
