### ISSUE TITLE
您好，关于https后台访问时，10.0.8无法加载

### ISSUE THREAD

**Issue by MEZboy** [LuRenJiasWorld/WP-Editor.md#408]
chrome提示错误如下：
`editormd.min.js?ver=2.0.1:2 Mixed Content: The page at 'https://maenze.com/wp-admin/post-new.php' was loaded over HTTPS, but requested an insecure script 'http://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.3/assets/MindMap/mindMap.min.js'. This request has been blocked; the content must be served over HTTPS.`

请教怎么解决呢，还有就是现在wordpress插件普遍在国内无法自动更新插件了吗，只能手动进行上传了……

辛苦！

**Comment by LuRenJiasWorld** [comment]
你好，请查看一下插件设置页面中的『编辑器静态资源地址』是否为HTTPS开头，具体参考以下图片：
<img width="819" alt="QQ20200118-110749@2x" src="https://user-images.githubusercontent.com/29622423/72657751-d78dad80-39e2-11ea-80f1-92ea878fdbc0.png">

**Comment by LuRenJiasWorld** [comment]
此外，WordPress目前在国内的使用存在障碍，除非在服务器端安装v2ray/ss等VPN软件，否则基本无解。

**Comment by MEZboy** [comment]
感谢您的回复，确实感觉现在墙的障碍越来越高了。
另外，后台看了是HTTPS的设置
![image](https://user-images.githubusercontent.com/5998050/72706507-29783400-3b99-11ea-932f-7032d0998843.png)

**Comment by MEZboy** [comment]
我把这个的也改成https的（虽然没开启），现在可以正常使用了，希望能帮助到有同样问题的人，感谢！
![image](https://user-images.githubusercontent.com/5998050/72706934-321d3a00-3b9a-11ea-8759-8157d4bd9586.png)

![image](https://user-images.githubusercontent.com/5998050/72706961-4103ec80-3b9a-11ea-876d-0cf36c09cdb4.png)

**Comment by LuRenJiasWorld** [comment]
好的，能帮到你就好，新年快乐 : )
