### ISSUE TITLE
思维导图前台不显示

### ISSUE THREAD

**Issue by BingChunMoLi** [LuRenJiasWorld/WP-Editor.md#409]
思维导图后台编辑时，即时预览可正常显示而前台访问无法显示。
实际地址https://sakura.bingchunmoli.com/bilibili%e6%8b%9c%e5%b9%b4%e7%a5%adsp%ef%bc%88%e9%93%81%e5%bf%83%e5%8d%9a%e5%bc%88%ef%bc%89%ef%bc%88%e4%b8%a5%e9%87%8d%e5%89%a7%e9%80%8f%ef%bc%89/

**Comment by LuRenJiasWorld** [comment]
看样子mindmap.js已经成功加载，控制台也没有看到报错。可以提供一下你的思维导图源码吗？我这边看能不能复现。

**Comment by BingChunMoLi** [comment]
-拜年祭SP
    -这不好说
        -你应该与他为荣
            -覆巢之下，岂有完卵
                -节哀
                -他只是个AI
                -不选择
            -放了老婆和孩子
            -不选择
        -你不该恨他
            -覆巢之下，岂有完卵
            -放了老婆和孩子
            -不选择
                -节哀
                    -笼中蝶
                -他只是个AI
                -不选择
        -不选择
    -我
        -你应该与他为荣
            -覆巢之下，岂有完卵
                -节哀
                -他只是个AI
                -不选择
            -放了老婆和孩子
            -不选择
        -你不该恨他
            -覆巢之下，岂有完卵
            -放了老婆和孩子
            -不选择
                -节哀
                -他只是个AI
                    -结局：end2 simulieren
                -不选择
                    -结局：end2 simulieren
        -不选择
            -覆巢之下，岂有完卵
            -放了老婆和孩子
            -不选择
                -节哀
                -他只是个AI
                -不选择
                    -结局：end2 simulieren
    -不选择（）
        -你应该与他为荣
        -你不该恨他
        -不选择
            -覆巢之下，岂有完卵
            -放了老婆和孩子
            -不选择
                -节哀
                -他只是个AI
                -不选择
                    -先保住他们
                    -摧毁钥匙
                    -不选择
                        -先保住他们
                        -摧毁钥匙
                        -不选择
                            -先保住他们
                            -摧毁钥匙
                            -不选择
                                -先保住他们
                                -摧毁钥匙
                                -不选择
                                    -大千世界

**Comment by BingChunMoLi** [comment]
原文实际可以访问我提供的网址通过控制台查看，在canvas便签下方的DIV中，直接发送换行丢失了

**Comment by LuRenJiasWorld** [comment]
好的，我尝试一下能否复现

**Comment by BingChunMoLi** [comment]
感谢

**Comment by LuRenJiasWorld** [comment]
<img width="1320" alt="QQ20200130-155245@2x" src="https://user-images.githubusercontent.com/29622423/73430287-a1ecab00-4378-11ea-81ae-8ce699f36be5.png">

我这边测试是没有问题的。不过我发现你这边引用MindMap.js的地址有点问题，尝试在设置菜单里修改为 `//cdn.jsdelivr.net/wp/wp-editormd/trunk/assets/MindMap/mindMap.min.js` 后再试试看呢？

**Comment by BingChunMoLi** [comment]
这个是否带https: 我尝试了下都不显示，我试试清楚下缓存，

**Comment by BingChunMoLi** [comment]
![image](https://user-images.githubusercontent.com/44092516/73431173-c3e72d00-437a-11ea-9da1-b142f4fd9e79.png)这个是否正确?，，尝试了更换后实际观察地址https://cdn.jsdelivr.net/wp/wp-editormd/trunk/assets/MindMap/mindMap.min.js?ver=10.0.8
请求成功了，但是仍然未显示

**Comment by LuRenJiasWorld** [comment]
我觉得可能是插件/主题兼容性导致的。你可以尝试换用其他主题或关闭其他插件再试试看吗？

**Comment by LuRenJiasWorld** [comment]
> 这个是否带https: 我尝试了下都不显示，我试试清楚下缓存，

前面不需要带前缀的，浏览器会根据当前的协议自动选择加http还是https

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/73431982-a87d2180-437c-11ea-8889-02c552b05f6d.png)
渲染成功后应该会显示这个canvas的宽度和高度，你这边没有的话就是没渲染成功。请排查一下与其他主题/插件的兼容性问题。

**Comment by BingChunMoLi** [comment]
OK,我试试，

**Comment by LuRenJiasWorld** [comment]
好的，WordPress插件的兼容性问题一直比较头疼，推荐你使用最小系统法排除，即只开启本插件的情况下，逐个开启其他插件直到遇到存在兼容性问题的插件为止。

**Comment by BingChunMoLi** [comment]
这个插件依赖的jquery，应该不会多次声明冲突把，主题里好像有声明

**Comment by LuRenJiasWorld** [comment]
> 这个插件依赖的jquery，应该不会多次声明冲突把，主题里好像有声明

一般不会有冲突，但也不一定，可以在高级设置中打开兼容模式试试看。

**Comment by BingChunMoLi** [comment]
editormd.min.js?ver=2.0.1:2 Uncaught TypeError: Cannot read property 'replace' of undefined
    at Function.i.loadScript (editormd.min.js?ver=2.0.1:2)
    at r (editormd.min.js?ver=2.0.1:2)
    at editormd.min.js?ver=2.0.1:2
    at HTMLScriptElement.i.isIE8.r.onload (editormd.min.js?ver=2.0.1:2)
控制台这个是无关的吗

**Comment by LuRenJiasWorld** [comment]
不是，这个属于报错。你有排查插件兼容性吗？没有的话可以先尝试重新安装本插件。

**Comment by BingChunMoLi** [comment]
插件已全部停用，仍然不显示，现在尝试手动调用JS文件

**Comment by LuRenJiasWorld** [comment]
好的，看来不是插件的问题。你换个主题试试看呢？

**Comment by LuRenJiasWorld** [comment]
手动调用也是个办法，虽然不是很推荐（后续版本更新可能会破坏你的fix）

**Comment by BingChunMoLi** [comment]
https://www.bingchunmoli.run/2020/01/bilibili%e6%8b%9c%e5%b9%b4%e7%a5%adsp%ef%bc%88%e9%93%81%e5%bf%83%e5%8d%9a%e5%bc%88%ef%bc%89%ef%bc%88%e4%b8%a5%e9%87%8d%e5%89%a7%e9%80%8f%ef%bc%89/ 主题不兼容导致的，更换主题OK，

**Comment by LuRenJiasWorld** [comment]
好的，你可以自己排查一下是什么原因不兼容，然后通过修改主题的方式fix该问题，或直接更换主题。: )

**Comment by LuRenJiasWorld** [comment]
我先关闭此issue，如果有其他问题可以在下面继续留言。祝新年快乐。

**Comment by BingChunMoLi** [comment]
感谢

**Comment by BingChunMoLi** [comment]
现在主题显示解决了，但是经过上次更改后，再更改回来，访问页面极大概率会先输出
![image](https://user-images.githubusercontent.com/44092516/73561225-993cc780-4493-11ea-8684-8945e43653d0.png)
![image](https://user-images.githubusercontent.com/44092516/73561267-a954a700-4493-11ea-8ce7-e4ce69cc2f24.png)
![image](https://user-images.githubusercontent.com/44092516/73561300-b4a7d280-4493-11ea-820c-21b24298af4e.png)，之后需要再次是刷新，才可，然后是linux，chrome可以正常显示，windows 火狐，星愿正常，chrome间歇性正常，edge和edge新版总是不显示。是否是markdown思维导图库的问题，我再确认下这个库和PJAX的兼容性
