### ISSUE TITLE
关于新版本插件设置路径

### ISSUE THREAD

**Issue by BingChunMoLi** [LuRenJiasWorld/WP-Editor.md#414]
插件在我的插件中点击插件的设置会出现【抱歉，您不能访问此页面。】具体链接为：站点/wp-admin/plugins.php?page=wp-editormd-settings
另更改了设置的路径在 worpdress下子目录，原目录丢失，新安装（友好提示位置错误）和升级（没有友好提示）。

**Comment by LuRenJiasWorld** [comment]
你好，最新的版本将插件设置面板修改到了设置菜单，如果访问的依旧是`plugins.php`会找不到对应页面。

请问你指的是设置菜单里没有`WP Editor.md`选项吗？

> 另更改了设置的路径在 worpdress下子目录，原目录丢失，新安装（友好提示位置错误）和升级（没有友好提示）。

这句话我不太理解，可以进一步描述一下吗？

**Comment by BingChunMoLi** [comment]
刚升级没有，后来重新安装后有了，但是没有友好提示，自己也没有看见，然后再原本位置找了很长时间，因为新安装提示的设置位置不对，且插件中心中设置连接失效

**Comment by BingChunMoLi** [comment]
原本设置实在插件一栏下，现不在插件一栏，但新安装提示设置还在插件一栏。

**Comment by LuRenJiasWorld** [comment]
> 原本设置实在插件一栏下，现不在插件一栏，但新安装提示设置还在插件一栏。

这样说比较清楚一些，我看看能否复现这个情况。

**Comment by LuRenJiasWorld** [comment]
抱歉，我这边无论是正常升级还是重新安装都未能复现这个情况。

请问移除插件后重新安装依旧会出现这个问题吗？可以的话最好给一个相关的截图便于理解，因为根据 https://github.com/LuRenJiasWorld/WP-Editor.md/commit/d2d04bcdf663116829b65a07cacc7b38aee209d7 和 https://github.com/LuRenJiasWorld/WP-Editor.md/commit/80e73632726f2bec22a0c59a62665069d4693530 ， 这个变更应该是即时生效的。

**Comment by BingChunMoLi** [comment]
只是新用户体验的问题，新安装再左边有个小框提示，在插件栏处，实际设置位置在设置栏处，只是用户体验问题。 不是大问题，只是新用户可能不会立刻找到设置的位置。

**Comment by LuRenJiasWorld** [comment]
> 只是新用户体验的问题，新安装再左边有个小框提示，在插件栏处，实际设置位置在设置栏处，只是用户体验问题。 不是大问题，只是新用户可能不会立刻找到设置的位置。

好的，我再排查一下，如果这个问题的确存在的话，确实对用户的体验不太好。

感谢反馈: )
