### ISSUE TITLE
和代码高亮插件冲突

### ISSUE THREAD

**Issue by gongel** [LuRenJiasWorld/WP-Editor.md#415]
代码高亮插件：Crayon Syntax Highlighter
代码框无法左右滑动了

**Comment by LuRenJiasWorld** [comment]
Markdown原生支持代码块语法，本插件也支持对应的代码高亮，一般来说没有使用其他高亮插件的必要。

不过可以麻烦给一个出现故障的文章地址吗？我看看是哪里冲突了，能解决的话还是解决下。

**Comment by gongel** [comment]
可以查看这篇 https://gongel.cn/?p=3847

**Comment by LuRenJiasWorld** [comment]
> 可以查看这篇 https://gongel.cn/?p=3847

好的，我现在看看

**Comment by LuRenJiasWorld** [comment]
排查后发现似乎问题与本插件无关。具体问题是代码高亮插件的纯代码部分覆盖了高亮代码部分，但由于纯代码部分的透明度为0（完全透明），无法看到，导致高亮代码的控件无法正常点击/选择。

我的建议解决方法是使用WordPress的自定义功能，添加如下css：

```css
.crayon-plain-wrap { display: none; }
```

详细原因见截图，希望能帮到你。感谢对本插件的支持: )

![image](https://user-images.githubusercontent.com/29622423/74815215-c9a9b000-5333-11ea-94ac-1ba28efde7c3.png)

**Comment by gongel** [comment]
感谢，已解决。
