### ISSUE TITLE
代码块换行问题询问

### ISSUE THREAD

**Issue by BingChunMoLi** [LuRenJiasWorld/WP-Editor.md#416]
![image](https://user-images.githubusercontent.com/44092516/74915767-bcf28e00-53ff-11ea-9f9d-3135d181407b.png)
![image](https://user-images.githubusercontent.com/44092516/74915777-c11eab80-53ff-11ea-87b7-1a0ce911c54a.png)
有时可以换行，有时加<br /> 每一行后加换行或空格仍然不能换行,这个是主题兼容性还是什么,而且有时候是一次访问可以换行，一次不可以。页面刚加载时换行的 加载完毕后就不换行了

**Comment by LuRenJiasWorld** [comment]
可以给一个可复现的地址吗？我看看是什么情况

**Comment by BingChunMoLi** [comment]
https://sakura.bingchunmoli.com/spring%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6/

**Comment by BingChunMoLi** [comment]
![image](https://user-images.githubusercontent.com/44092516/74967981-015c4900-5455-11ea-88ee-28ea7250d8e6.png)

**Comment by LuRenJiasWorld** [comment]
> https://sakura.bingchunmoli.com/spring%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6/

好的，我稍后看看

**Comment by LuRenJiasWorld** [comment]
没有看到明显的CSS问题，但是发现本插件相关的CSS配置基本上被主题配置全部覆盖了，不知道是不是主题自带了高亮的功能。

此外，在禁止`sakura.bingchunmoli.com/wp-content/themes/Sakura/cdn/js/lib.js?ver=3.3.60.1.96`加载后，代码高亮样式恢复正常。

请问更换其他主题后问题是否能复现呢？

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/75004789-427d4900-54a7-11ea-8e86-64777215c498.png)

这是禁用了上文所述JS脚本后的情况，因为该文件被压缩混淆，不太方便看到底是哪一步造成的问题。

**Comment by BingChunMoLi** [comment]
好的，我自己做兼容。
