### ISSUE TITLE
[建议] 加入与Enlighter代码高亮插件的兼容

### ISSUE THREAD

**Issue by Makiras** [LuRenJiasWorld/WP-Editor.md#417]
[Enlighter 插件地址](https://cn.wordpress.org/plugins/enlighter/advanced/)

通过实验发现Enlighter插件在文章中插入的HTML代码格式如下
```html
<pre class="EnlighterJSRAW" data-enlighter-language="cpp">
.......
</pre>
```
而目前的编辑器插入格式如下
```html
<pre><code class="language-cpp" line-number>
.......
</code></pre>
```

通过修改插入标签来实现对`Enlighter`插件的兼容似乎成本可接受？感谢阅读

**Comment by Makiras** [comment]
相关代码在`src/APP/WPMarkdownPaser:450`附近，目前我尝试进行的修改似乎没有影响到其他部分的工作。
看起来替换插入标签即可完成兼容？（不过测试语言很少，可能仍有疏漏）

**Comment by LuRenJiasWorld** [comment]
请问你的意思是希望新增一个关闭本插件高亮功能的选项吗？

**Comment by Makiras** [comment]
我觉得如果只关闭应该做不到这件事情？
Enlighter在原版编辑器中会加入一个插入代码块的选项，然后这个插入代码块功能就会直接以HTML的方式插入到原文当中。但是因为Enlighter无法给这个editor增加选项，所以就没有一个入口（而且好像也没法处理编辑器中的渲染）。
然后这个Editor处理markdown的codeblocks时的语法解析正好可以替代enlighter直接以HTML插入的功能，变相解决了问题。

大概就是把`src/APP/WPMarkdownPaser:450`
```php
//添加Prism相关的类名
$classes[] = $this->get_option('line_numbers', 'syntax_highlighting') == 'on' ? 'line-numbers' : '';
//更新语言标识符
if ($langname !== '') {
           dataLanguage = ' data-language=' . $langname;
} else {
           $dataLanguage = '';
}
$attr_str = $this->doExtraAttributes($this->code_attr_on_pre ? "pre" : "code", $attrs, null, $classes);
$pre_attr_str = $this->code_attr_on_pre ? $attr_str : $dataLanguage;
$code_attr_str = $this->code_attr_on_pre ? '' : $attr_str;
$codeblock = "<pre$pre_attr_str><code$code_attr_str>$codeblock</code></pre>";
```

直接替换成（啊代码很脏还求轻喷）
```html
$codeblock = "<pre class=\"EnlighterJSRAW\" data-enlighter-language=$langname>$codeblock</pre>";
```

**Comment by LuRenJiasWorld** [comment]
明白了，那这个你可以自己修改下，因为第三方代码高亮插件实在是太多了。不太方便逐一适配。不过自行修改的话要注意更新的问题，可能每次更新都会覆盖一下你的配置。建议还是使用自带的代码高亮功能: )

我这边了解到的大部分用户还是会使用自带的prism.js，因为后台编辑器预览使用的也是这个，但不是所有第三方代码高亮插件都能在后台编辑器支持高亮显示。

请问有什么必须要使用第三方代码高亮插件的原因吗？

**Comment by Makiras** [comment]
啊，倒也没有必须使用第三方插件的原因，原版工作的还行只是和主题不太搭调，只是单纯个人审美罢了（
漂亮的~~小姐姐~~代码高亮谁不爱呢
那如果有时间我大概会给这个需求提交一个PR？（咕咕咕咕咕咕）

**Comment by LuRenJiasWorld** [comment]
> 啊，倒也没有必须使用第三方插件的原因，原版工作的还行只是和主题不太搭调，只是单纯个人审美罢了（
> 漂亮的~小姐姐~代码高亮谁不爱呢
> 那如果有时间我大概会给这个需求提交一个PR？（咕咕咕咕咕咕）

这个在插件设置里有各种主题可供选择，如果觉得不好看的话可以引入自己的高亮样式（遵守prism.js规范即可）。默认的我也觉得不太好看，可能后面会选一个最好看的作为默认主题。

**Comment by LuRenJiasWorld** [comment]
> 那如果有时间我大概会给这个需求提交一个PR？（咕咕咕咕咕咕）

非常欢迎: )

**Comment by LuRenJiasWorld** [comment]
https://github.com/PrismJS/prism-themes/tree/master/themes 这里有Prism.js的所有官方主题，可选择的还是比较多的。
