### ISSUE TITLE
安装插件后，新增文章页面响应异常的慢，安装前800ms，安装后四十多秒

### ISSUE THREAD

**Issue by wangerzi** [LuRenJiasWorld/WP-Editor.md#418]
![image](https://user-images.githubusercontent.com/22190579/75103610-f4e41600-5637-11ea-8842-6244bd6f0f47.png)

正在尝试以注释插件代码的形式进行调试，但是目前还没有找到具体问题在哪儿

调试信息如下：
![image](https://user-images.githubusercontent.com/22190579/75103613-0d543080-5638-11ea-9dd0-b7dee57ab585.png)
![image](https://user-images.githubusercontent.com/22190579/75103616-19d88900-5638-11ea-8781-0ce991daf477.png)

**Comment by wangerzi** [comment]
目前找到的是`src/Admin/Controller`中`add_filter('use_block_editor_for_post', '__return_false', 5);`这一段代码注释后，速度正常，但是使用的是wordpress自带的编辑器

![image](https://user-images.githubusercontent.com/22190579/75103660-ab47fb00-5638-11ea-9e2c-010fc36ac29e.png)

![image](https://user-images.githubusercontent.com/22190579/75103662-be5acb00-5638-11ea-962f-506bb20bb2d5.png)

**Comment by LuRenJiasWorld** [comment]
40s确实不正常，初步考虑可能是插件冲突的原因导致这个问题，你可以先试试看关闭其他插件逐一测试吗？

**Comment by wangerzi** [comment]
> 40s确实不正常，初步考虑可能是插件冲突的原因导致这个问题，你可以先试试看关闭其他插件逐一测试吗？

感谢~尝试了下，WP Product Review Lite 禁用就好了
![image](https://user-images.githubusercontent.com/22190579/75103746-fc0c2380-5639-11ea-9c09-456b6f78f9cf.png)

**Comment by LuRenJiasWorld** [comment]
> > 40s确实不正常，初步考虑可能是插件冲突的原因导致这个问题，你可以先试试看关闭其他插件逐一测试吗？
> 
> 感谢~尝试了下，WP Product Review Lite 禁用就好了
> ![image](https://user-images.githubusercontent.com/22190579/75103746-fc0c2380-5639-11ea-9c09-456b6f78f9cf.png)

没关系: )，很高兴能帮到你。
