### ISSUE TITLE
md文档不能正常显示

### ISSUE THREAD

**Issue by chenh2663** [LuRenJiasWorld/WP-Editor.md#421]
我用typora写的MD文档 复制到editor中右侧预览是正确的，但是发布出来就会出现问题。如图
![KWFZJ3GHMRZL_J@NO7P{X@X](https://user-images.githubusercontent.com/48430535/75474228-90c3a800-59d1-11ea-8722-4a696d65aadc.png)
文章地址：http://118.89.228.91/2020/02/28/c%e5%b0%8f%e7%9f%a5%e8%af%86%e7%82%b9/

**Comment by LuRenJiasWorld** [comment]
你好，C++语言的高亮提示符为`cpp`，不是`c++`。
