### ISSUE TITLE
能否增加是否将远程图片下载到本地的选项

### ISSUE THREAD

**Issue by hanlhan** [LuRenJiasWorld/WP-Editor.md#423]

**Comment by LuRenJiasWorld** [comment]
你好，请问是在什么情况下需要使用该功能呢？

我记得WordPress应该有一些支持该功能的插件，不知道是否能与本插件兼容。你可以先试试看现有的插件，如果无法正常工作，我这边再看看如何解决，或者实现一下这个功能。

**Comment by hanlhan** [comment]
你好，我是在本地写作，使用了七牛云作为图床，上传到博客后七牛云的流量可能会超标。我试过一款将远程图片下载到本地的插件，叫做 Sync Remote Images，但是这款插件可以与本插件有所冲突，具体来说就是提交或保存草稿之后，图片是下载到本地了，但是Markdown都没了，左右框（编辑框和预览框）都变成了HTML代码。类似下面。
![Snipaste_2020-03-02_00-04-35](https://user-images.githubusercontent.com/32872034/75629019-78de6500-5c19-11ea-942c-ccbc29659503.png)

WordPress版本:WordPress 5.3.2
Php版本：7.1
Sync Remote Images版本：0.01（警告：此插件与您的WordPress版本的兼容性没有被测试。）
WP Editor.md版本：10.1.0

尝试过自己实现，但没有成功。
十分感谢。

**Comment by hanlhan** [comment]
你好，刚又发现和插件 Simple Post Series 有些冲突，同时启用后在博客内容页系列专题不能折叠起来。

**Comment by LuRenJiasWorld** [comment]
> 你好，我是在本地写作，使用了七牛云作为图床，上传到博客后七牛云的流量可能会超标。我试过一款将远程图片下载到本地的插件，叫做 Sync Remote Images，但是这款插件可以与本插件有所冲突，具体来说就是提交或保存草稿之后，图片是下载到本地了，但是Markdown都没了，左右框（编辑框和预览框）都变成了HTML代码。类似下面。
> ![Snipaste_2020-03-02_00-04-35](https://user-images.githubusercontent.com/32872034/75629019-78de6500-5c19-11ea-942c-ccbc29659503.png)
> 
> WordPress版本:WordPress 5.3.2
> Php版本：7.1
> Sync Remote Images版本：0.01（警告：此插件与您的WordPress版本的兼容性没有被测试。）
> WP Editor.md版本：10.1.0
> 
> 尝试过自己实现，但没有成功。
> 十分感谢。

嗯，冲突的原因应该是Sync Remote Images插件去掉了wp_posts表中的markdown原文，这个没有办法。本插件会在该表中分别存储原文和解析后的html，每次更新文章的时候将原文转换为html。

至于这个下载远程图片的功能，我思考一下如何实现吧，之前的确没有了解过这方面的需求。

**Comment by LuRenJiasWorld** [comment]
> 你好，刚又发现和插件 Simple Post Series 有些冲突，同时启用后在博客内容页系列专题不能折叠起来。

可以提供更多相关的信息吗？这个插件我没有使用过。

**Comment by hanlhan** [comment]
> > 你好，刚又发现和插件 Simple Post Series 有些冲突，同时启用后在博客内容页系列专题不能折叠起来。
> 
> 可以提供更多相关的信息吗？这个插件我没有使用过。

Simple Post Series 版本：2.4.4，这个插件可以把一个专题系列的文章的链接放在文章开头，如下图：
![](https://user-images.githubusercontent.com/32872034/75690151-544bc100-5cdd-11ea-95f9-3bc6b66ddd54.png)
![](https://user-images.githubusercontent.com/32872034/75690407-c02e2980-5cdd-11ea-8ad2-77103aaaf1d5.png)

在启用 WP Editor.md 插件之后，文章开头的链接不能折叠起来，+号按钮没有反应：
![](https://user-images.githubusercontent.com/32872034/75690332-9b39b680-5cdd-11ea-8d0b-4051408521c1.png)
禁用MD插件之后就回复正常了，因此确定可能有冲突。

还需要别的什么信息吗？

**Comment by LuRenJiasWorld** [comment]
> > > 你好，刚又发现和插件 Simple Post Series 有些冲突，同时启用后在博客内容页系列专题不能折叠起来。
> > 
> > 
> > 可以提供更多相关的信息吗？这个插件我没有使用过。
> 
> Simple Post Series 版本：2.4.4，这个插件可以把一个专题系列的文章的链接放在文章开头，如下图：
> ![](https://user-images.githubusercontent.com/32872034/75690151-544bc100-5cdd-11ea-95f9-3bc6b66ddd54.png)
> ![](https://user-images.githubusercontent.com/32872034/75690407-c02e2980-5cdd-11ea-8ad2-77103aaaf1d5.png)
> 
> 在启用 WP Editor.md 插件之后，文章开头的链接不能折叠起来，+号按钮没有反应：
> ![](https://user-images.githubusercontent.com/32872034/75690332-9b39b680-5cdd-11ea-8d0b-4051408521c1.png)
> 禁用MD插件之后就回复正常了，因此确定可能有冲突。
> 
> 还需要别的什么信息吗？

嗯，可以再提供一个出现故障的文章链接吗？

**Comment by hanlhan** [comment]
> > > > 你好，刚又发现和插件 Simple Post Series 有些冲突，同时启用后在博客内容页系列专题不能折叠起来。
> > > 
> > > 
> > > 可以提供更多相关的信息吗？这个插件我没有使用过。
> > 
> > 
> > Simple Post Series 版本：2.4.4，这个插件可以把一个专题系列的文章的链接放在文章开头，如下图：
> > ![](https://user-images.githubusercontent.com/32872034/75690151-544bc100-5cdd-11ea-95f9-3bc6b66ddd54.png)
> > ![](https://user-images.githubusercontent.com/32872034/75690407-c02e2980-5cdd-11ea-8ad2-77103aaaf1d5.png)
> > 在启用 WP Editor.md 插件之后，文章开头的链接不能折叠起来，+号按钮没有反应：
> > ![](https://user-images.githubusercontent.com/32872034/75690332-9b39b680-5cdd-11ea-8d0b-4051408521c1.png)
> > 禁用MD插件之后就回复正常了，因此确定可能有冲突。
> > 还需要别的什么信息吗？
> 
> 嗯，可以再提供一个出现故障的文章链接吗？

https://panchuang.net/2020/03/01/opencv-python-%e7%b3%bb%e5%88%97-%e5%8d%81%e4%b8%83-%e5%9b%be%e5%83%8f%e6%a2%af%e5%ba%a6/

**Comment by LuRenJiasWorld** [comment]
> > > > > 你好，刚又发现和插件 Simple Post Series 有些冲突，同时启用后在博客内容页系列专题不能折叠起来。
> > > > 
> > > > 
> > > > 可以提供更多相关的信息吗？这个插件我没有使用过。
> > > 
> > > 
> > > Simple Post Series 版本：2.4.4，这个插件可以把一个专题系列的文章的链接放在文章开头，如下图：
> > > ![](https://user-images.githubusercontent.com/32872034/75690151-544bc100-5cdd-11ea-95f9-3bc6b66ddd54.png)
> > > ![](https://user-images.githubusercontent.com/32872034/75690407-c02e2980-5cdd-11ea-8ad2-77103aaaf1d5.png)
> > > 在启用 WP Editor.md 插件之后，文章开头的链接不能折叠起来，+号按钮没有反应：
> > > ![](https://user-images.githubusercontent.com/32872034/75690332-9b39b680-5cdd-11ea-8d0b-4051408521c1.png)
> > > 禁用MD插件之后就回复正常了，因此确定可能有冲突。
> > > 还需要别的什么信息吗？
> > 
> > 
> > 嗯，可以再提供一个出现故障的文章链接吗？
> 
> https://panchuang.net/2020/03/01/opencv-python-%e7%b3%bb%e5%88%97-%e5%8d%81%e4%b8%83-%e5%9b%be%e5%83%8f%e6%a2%af%e5%ba%a6/

好的，你需要进行以下操作：打开WP Editor.md设置，在高级设置中勾选『兼容模式』，然后点击保存，即可生效。

**Comment by hanlhan** [comment]
> > > > > > 你好，刚又发现和插件 Simple Post Series 有些冲突，同时启用后在博客内容页系列专题不能折叠起来。
> > > > > 
> > > > > 
> > > > > 可以提供更多相关的信息吗？这个插件我没有使用过。
> > > > 
> > > > 
> > > > Simple Post Series 版本：2.4.4，这个插件可以把一个专题系列的文章的链接放在文章开头，如下图：
> > > > ![](https://user-images.githubusercontent.com/32872034/75690151-544bc100-5cdd-11ea-95f9-3bc6b66ddd54.png)
> > > > ![](https://user-images.githubusercontent.com/32872034/75690407-c02e2980-5cdd-11ea-8ad2-77103aaaf1d5.png)
> > > > 在启用 WP Editor.md 插件之后，文章开头的链接不能折叠起来，+号按钮没有反应：
> > > > ![](https://user-images.githubusercontent.com/32872034/75690332-9b39b680-5cdd-11ea-8d0b-4051408521c1.png)
> > > > 禁用MD插件之后就回复正常了，因此确定可能有冲突。
> > > > 还需要别的什么信息吗？
> > > 
> > > 
> > > 嗯，可以再提供一个出现故障的文章链接吗？
> > 
> > 
> > https://panchuang.net/2020/03/01/opencv-python-%e7%b3%bb%e5%88%97-%e5%8d%81%e4%b8%83-%e5%9b%be%e5%83%8f%e6%a2%af%e5%ba%a6/
> 
> 好的，你需要进行以下操作：打开WP Editor.md设置，在高级设置中勾选『兼容模式』，然后点击保存，即可生效。

谢谢，这个问题成功解决了

**Comment by LuRenJiasWorld** [comment]
> > > > > > > 你好，刚又发现和插件 Simple Post Series 有些冲突，同时启用后在博客内容页系列专题不能折叠起来。
> > > > > > 
> > > > > > 
> > > > > > 可以提供更多相关的信息吗？这个插件我没有使用过。
> > > > > 
> > > > > 
> > > > > Simple Post Series 版本：2.4.4，这个插件可以把一个专题系列的文章的链接放在文章开头，如下图：
> > > > > ![](https://user-images.githubusercontent.com/32872034/75690151-544bc100-5cdd-11ea-95f9-3bc6b66ddd54.png)
> > > > > ![](https://user-images.githubusercontent.com/32872034/75690407-c02e2980-5cdd-11ea-8ad2-77103aaaf1d5.png)
> > > > > 在启用 WP Editor.md 插件之后，文章开头的链接不能折叠起来，+号按钮没有反应：
> > > > > ![](https://user-images.githubusercontent.com/32872034/75690332-9b39b680-5cdd-11ea-8d0b-4051408521c1.png)
> > > > > 禁用MD插件之后就回复正常了，因此确定可能有冲突。
> > > > > 还需要别的什么信息吗？
> > > > 
> > > > 
> > > > 嗯，可以再提供一个出现故障的文章链接吗？
> > > 
> > > 
> > > https://panchuang.net/2020/03/01/opencv-python-%e7%b3%bb%e5%88%97-%e5%8d%81%e4%b8%83-%e5%9b%be%e5%83%8f%e6%a2%af%e5%ba%a6/
> > 
> > 
> > 好的，你需要进行以下操作：打开WP Editor.md设置，在高级设置中勾选『兼容模式』，然后点击保存，即可生效。
> 
> 谢谢，这个问题成功解决了

没关系，很高兴可以帮到你。我会认真思考一下如何实现下载远程图片的这个功能。
