### ISSUE TITLE
How to use Customize Style Library

### ISSUE THREAD

**Issue by sho-v00** [LuRenJiasWorld/WP-Editor.md#425]
Hi.

I'm happy to use this awesome markdown editor on WP.

I'm trying to set up Syntax highlight but I couldn't find how to set the Custom highlight in "Customize Style Library" section.

<img width="626" alt="Screen Shot 2020-03-02 at 0 15 12" src="https://user-images.githubusercontent.com/41004390/75628483-b2fd3600-5c1c-11ea-95a1-637ceca66c2b.png">

Are there any references to setup custom syntax?
Apparently there's a repository you created.

https://github.com/JaxsonWang/Prism.js-Style

Thanks.

**Comment by LuRenJiasWorld** [comment]
If you want to use them, just copy the style's css link.

For example, if you like the style Duotone Earth，just copy the link in the README.md：`https://github.com/JaxsonWang/Prism.js-Style/blob/master/DuotoneEarth/prism-duotone-earth.min.css`， and paste it to the `Customize Style Library` section.

Then you can use the theme you want to.

![image](https://user-images.githubusercontent.com/29622423/75662434-0ff2fd80-5caa-11ea-9239-5f9bc9d0f091.png)

**Comment by sho-v00** [comment]
Thanks for the reply!

I tried to copy and paste the link but Syntax doesn't change🤔

<img width="626" alt="Screen Shot 2020-03-02 at 18 46 30" src="https://user-images.githubusercontent.com/41004390/75664785-65350c00-5cb6-11ea-94a8-30d2f4385b50.png">
<img width="915" alt="Screen Shot 2020-03-02 at 18 46 40" src="https://user-images.githubusercontent.com/41004390/75664794-66fecf80-5cb6-11ea-8d74-7ba0c2728f92.png">

Any ideas?

**Comment by LuRenJiasWorld** [comment]
Oh sorry, It's my fault. You have to click the link you want to use, and copy the raw link.

![image](https://user-images.githubusercontent.com/29622423/75666062-2439f900-5cb0-11ea-8d0c-f961a79a608a.png)

**Comment by LuRenJiasWorld** [comment]
Oh sorry, It's my fault. You have to click the link you want to use, and click the raw button, then copy the link in your browser's address bar.

![image](https://user-images.githubusercontent.com/29622423/75666062-2439f900-5cb0-11ea-8d0c-f961a79a608a.png)

**Comment by LuRenJiasWorld** [comment]
Sorry for the inconvenience.

It seems that modern browser refuse to load the css stylesheet with the `text/plain` MIME type.

![image](https://user-images.githubusercontent.com/29622423/75666613-120c8a80-5cb1-11ea-9c27-63744de6f039.png)

So you have to download the stylesheet you want directly onto your server, and set the `Customize Style Library` section to the url you have uploaded to.

I will fix this issue in the next version.

**Comment by sho-v00** [comment]
That's alright.

Ah it's understandable.
Ok, I'll try the suggestion anyway, Thanks.

I look forward to the next update :)

**Comment by LuRenJiasWorld** [comment]
It's okay, and I'll close this issue.

Feel free to provide other feedback if you have any difficulty with this plugin.

**Comment by LuRenJiasWorld** [comment]
Hello, I'm trying to resolve this issue now.

The new repository is https://github.com/LuRenJiasWorld/Prism.js-style .

Instructions about how to use them is written in README.md of that repository.

Feel free to ask me if you have any further questions, and I will continue adding more highlighting styles into the repositoty.

**Comment by sho-v00** [comment]
Hi.

Thanks for the resolution!
I’m going to check it up.

Sorry for the late reply.


Thanks.
