### ISSUE TITLE
图床功能无法使用，无法粘贴上传到图床

### ISSUE THREAD

**Issue by okhttps-web** [LuRenJiasWorld/WP-Editor.md#427]
![QQ截图20200304215341](https://user-images.githubusercontent.com/48914442/75886179-d0234600-5e62-11ea-9937-859e70c1c706.png)

在编辑器中复制图片然后粘贴，一直显示  上传图片 的状态。功能使用不了。

**Comment by okhttps-web** [comment]
![上传图片中..](https://user-images.githubusercontent.com/48914442/75886380-15e00e80-5e63-11ea-95f4-15f202ee2fbb.png)

**Comment by okhttps-web** [comment]
![image](https://user-images.githubusercontent.com/48914442/75886459-360fcd80-5e63-11ea-9438-896efa9ca75d.png)

**Comment by LuRenJiasWorld** [comment]
你好，经核实，`sm.ms`图床不再接受无条件免费图片托管服务，API进行了一些升级。

目前你需要在设置中取消上传到图床的选项，以将图片上传到你的服务器。

下一版本我将先取消该选项支持，优化后重新开放。此外会新增更多图床选择与自定义选项。

抱歉带来不便。

**Comment by LuRenJiasWorld** [comment]
你好，相关功能正在开发中，开发完成后我会继续更新此Issue，感谢反馈。

![image](https://user-images.githubusercontent.com/29622423/76158231-a57d0a00-614e-11ea-9c83-9a5ee48465d8.png)

**Comment by LuRenJiasWorld** [comment]
你好，相关功能已经初步开发完成，适配了新的API。具体请参考 https://github.com/LuRenJiasWorld/WP-Editor.md/commit/b613548ca69cdb006b34912fe6060029f08be4c1 。相关更新将于本月底发布，版本号为10.1.1。

考虑到sm.ms图床商业化后支持图片管理API，接下来的10.2.0版本我会为图床新增一个独立面板以进行适配，除此之外还会增加图片压缩参数、独立图片上传面板等功能。功能实现后我会继续更新此Issue。 

再度感谢你的反馈。

**Comment by LuRenJiasWorld** [comment]
你好，相关问题已于最新发布的10.1.1版本修复，发行注记详见 https://github.com/LuRenJiasWorld/WP-Editor.md/releases/tag/v10.1.1 。

感谢对本插件的支持，祝你使用愉快，如有更多问题欢迎继续反馈。
