### ISSUE TITLE
页面无法评论

### ISSUE THREAD

**Issue by ghost** [LuRenJiasWorld/WP-Editor.md#432]
使用wp-editor编辑器，新建页面评论功能默认关闭，且没有可以开启评论的按钮！请尽快修复，谢谢🙏

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/76499416-a331ed00-6479-11ea-81b6-5e6b3a1e21e7.png)

应该不会吧，评论按钮在页面编辑面板的下方，这个是WordPress自带的，你找找看。

**Comment by LuRenJiasWorld** [comment]
页面应该默认就是禁止评论的，如果你找不到这个面板，点击这里，勾选讨论面板。

![image](https://user-images.githubusercontent.com/29622423/76499519-d4aab880-6479-11ea-8aa0-55dc2e03ab76.png)

**Comment by ghost** [comment]
已解决，谢谢dalao

Benjamin Chris <notifications@github.com> 于2020年3月12日周四 下午3:54写道：
