### ISSUE TITLE
在编辑器上添加一个按钮

### ISSUE THREAD

**Issue by cj96248** [LuRenJiasWorld/WP-Editor.md#433]
添加如下的代码到 functions.php 中，但是添加的按钮并不能生效。
```php
    function appthemes_add_quicktags() {
    ?>
    <script type="text/javascript">QTags.addButton( '按钮名', '按钮名', '<div class="ask">', '</div>' ); 
    </script>
       <?php
       }
      add_action('admin_print_footer_scripts', 'appthemes_add_quicktags' );
```

**Comment by LuRenJiasWorld** [comment]
你好。QTags是WordPress中HTML编辑器的API，与本插件无关，如图所示：

![image](https://user-images.githubusercontent.com/29622423/76673506-c62ae100-65e0-11ea-8636-4cd492346f2d.png)

本插件目前暂不支持相关按钮定制，但是如果有需求，我会在将来版本加入自定义按钮支持。

如果你需要添加按钮，建议使用`media_buttons`的钩子，这里是相关教学，希望能帮到你：

https://www.sitepoint.com/adding-a-media-button-to-the-content-editor/

**Comment by cj96248** [comment]
@LuRenJiasWorld 感谢回复。

实际上我尝试过用media的button，但是发现了一个小遗憾。

![Snipaste_20200314_11-33-25](https://user-images.githubusercontent.com/14250751/76674229-e90cc380-65e7-11ea-8b8b-92527068b0f4.png)

 图中的 addHtml 按钮是我用来添加固定的html片段的，利用了shortcode 的形式。

`wp.media.editor.insert("[addHtml][/addHtml]");`

但是插入后的效果，会把我的 方括号转义：

`\[addHtml\]\[/addHtml\]`

通过查看源码，发现在config/editormd.js中有一段逻辑：
```js
        // WP Media module支持
        if (typeof wp !== 'undefined' && typeof wp.media !== 'undefined') {
            var original_wp_media_editor_insert = wp.media.editor.insert;
            var turndownService = new TurndownService();
            wp.media.editor.insert = function (html) {
                var markdown = turndownService.turndown(html);
                original_wp_media_editor_insert(markdown);
                wpEditormd.insertValue(markdown);
            };
        }
```
问题就出在 ` turndownService.turndown(html);`，经过 turndown 以后，`[addHtml][/addHtml]`就变成了 `\[addHtml\]\[/addHtml\]`.

对了，最近升级到了插件的最新版，发现点击addHtml这个按钮以后，会出来一个全屏的mask，导致编写体验不太好。

![GIF 2020-03-14 11-45-55](https://user-images.githubusercontent.com/14250751/76674355-8e746700-65e9-11ea-8b0a-8fdb0b4d4bc6.gif)

旧版的点击按钮以后，是直接上屏，不mask。特别是我用黑色主题，很晃眼。

**Comment by LuRenJiasWorld** [comment]
> @LuRenJiasWorld 感谢回复。
> 
> 实际上我尝试过用media的button，但是发现了一个小遗憾。
> 
> ![Snipaste_20200314_11-33-25](https://user-images.githubusercontent.com/14250751/76674229-e90cc380-65e7-11ea-8b8b-92527068b0f4.png)
> 
> 图中的 addHtml 按钮是我用来添加固定的html片段的，利用了shortcode 的形式。
> 
> `wp.media.editor.insert("[addHtml][/addHtml]");`
> 
> 但是插入后的效果，会把我的 方括号转义：
> 
> `\[addHtml\]\[/addHtml\]`
> 
> 通过查看源码，发现在config/editormd.js中有一段逻辑：
> 
> ```js
>         // WP Media module支持
>         if (typeof wp !== 'undefined' && typeof wp.media !== 'undefined') {
>             var original_wp_media_editor_insert = wp.media.editor.insert;
>             var turndownService = new TurndownService();
>             wp.media.editor.insert = function (html) {
>                 var markdown = turndownService.turndown(html);
>                 original_wp_media_editor_insert(markdown);
>                 wpEditormd.insertValue(markdown);
>             };
>         }
> ```
> 
> 问题就出在 ` turndownService.turndown(html);`，经过 turndown 以后，`[addHtml][/addHtml]`就变成了 `\[addHtml\]\[/addHtml\]`.

你好，这部分当时只考虑到了插入图片的需求，所以说会将WordPress『插入媒体』功能的img标签转换为对应的Markdown文本。

这个的确是我考虑不周到，会在将来的版本进行区分，现在可能无法通过这种方式来插入自定义文本。

> 
> 对了，最近升级到了插件的最新版，发现点击addHtml这个按钮以后，会出来一个全屏的mask，导致编写体验不太好。
> 
> ![GIF 2020-03-14 11-45-55](https://user-images.githubusercontent.com/14250751/76674355-8e746700-65e9-11ea-8b0a-8fdb0b4d4bc6.gif)
> 
> 旧版的点击按钮以后，是直接上屏，不mask。特别是我用黑色主题，很晃眼。

这个是因为之前有用户反馈在添加媒体页面点击插入之后，等待五秒钟才会将图片插入到编辑器，因此设计了一个Loading动画。我思考一下如何针对暗色主题进行定制吧，不然确实比较刺眼。

以上两个问题修复后我会更新此Issue，感谢反馈。

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/76826965-b289af80-6858-11ea-9794-0e23f3924907.png)


![image](https://user-images.githubusercontent.com/29622423/76827271-65f2a400-6859-11ea-8f56-2962ced6997d.png)

你好，你所提到的暗色主题下Loading对话框太刺眼的问题已经在解决了。目前我想到的解决方法是使用无色半透明遮罩替换之前的白色纯色遮罩，效果如图所示。

再次感谢反馈，另一个问题解决后我会继续更新此Issue。

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/77141836-380b9a80-6ab9-11ea-9004-060339ea5ff7.png)

![image](https://user-images.githubusercontent.com/29622423/77141848-3d68e500-6ab9-11ea-93ff-665e88098de4.png)

你好，另一个问题（媒体插入的方式输入shortcode被转义）也已经在解决了。这两个修复都会在月底发布的10.1.1版本加入。

**Comment by LuRenJiasWorld** [comment]
你好，相关问题已于最新发布的10.1.1版本修复，发行注记详见 https://github.com/LuRenJiasWorld/WP-Editor.md/releases/tag/v10.1.1 。

感谢对本插件的支持，祝你使用愉快，如有更多问题欢迎继续反馈。
