### ISSUE TITLE
能否禁止首页加载 Prism.js 相关资源？

### ISSUE THREAD

**Issue by zry98** [LuRenJiasWorld/WP-Editor.md#436]
安装插件后 wordpress 首页会加载 Prism.js 相关 JS 与 CSS 资源，导致页面加载缓慢

**Comment by LuRenJiasWorld** [comment]
你好，Prism.js是代码高亮的核心组件，如果导致加载缓慢有两种方式可以解决：

1. 使用CDN，也就是在设置页面中，将静态资源地址设置为`https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.1.0`（以版本号结尾，不含assets），这样子的话，加载静态资源就不会消耗你的服务器资源了
2. 关闭代码高亮功能，也可以避免加载Prism.js

**Comment by cj96248** [comment]
作者给的建议并不是好办法，我在使用该插件以后，也发现首页太慢了，于是禁用了首页的js加载：

在`functions.php`中加入如下代码：
```php
add_action('wp_print_scripts', 'mapull_deregister_scripts', 999);
function mapull_deregister_scripts()
{
	if(!is_home()){
		wp_deregister_script('prism-core-js');
		wp_deregister_script('prism-plugin-autoloader');
		wp_deregister_script('prism-plugin-toolbar');
		wp_deregister_script('prism-plugin-show-language');
		wp_deregister_script('copy-clipboard');
		wp_deregister_script('prism-plugin-copy-to-clipboard');
		wp_deregister_script('prism-plugin-line-numbers');
	}
}
```
这样把插件的所有js屏蔽了，如果你的首页会使用到插件里的部分js，需要按需处理。
这样其他页面功能不受影响，也不需要关闭代码高亮。

**Comment by LuRenJiasWorld** [comment]
> 作者给的建议并不是好办法，我在使用该插件以后，也发现首页太慢了，于是禁用了首页的js加载：
> 
> 在`functions.php`中加入如下代码：
> 
> ```
> add_action('wp_print_scripts', 'mapull_deregister_scripts', 999);
> function mapull_deregister_scripts()
> {
> 	if(!is_home()){
> 		wp_deregister_script('prism-core-js');
> 		wp_deregister_script('prism-plugin-autoloader');
> 		wp_deregister_script('prism-plugin-toolbar');
> 		wp_deregister_script('prism-plugin-show-language');
> 		wp_deregister_script('copy-clipboard');
> 		wp_deregister_script('prism-plugin-copy-to-clipboard');
> 		wp_deregister_script('prism-plugin-line-numbers');
> 	}
> }
> ```
> 
> 这样把插件的所有js屏蔽了，如果你的首页会使用到插件里的部分js，需要按需处理。
> 这样其他页面功能不受影响，也不需要关闭代码高亮。

这也是一种比较好的方法，只要能解决问题即可。

首页需要加载脚本的原因主要是考虑到部分主题会在首页也显示全文，如果直接关闭首页的脚本加载，可能对这些主题会造成影响。这个东西就是进难、退也难，只能采取默认加载的策略。

@zry98 你可以按照这个建议进行操作，或者使用CDN的方式加载静态资源。

我后面会考虑新增一个开关以便有需求的用户在首页关闭Prism.js加载。

**Comment by zry98** [comment]
非常感谢两位的帮助！
