### ISSUE TITLE
支持更换字体

### ISSUE THREAD

**Issue by not-know** [LuRenJiasWorld/WP-Editor.md#437]
要是能增加更换字体支持就好了，非常感谢

**Comment by LuRenJiasWorld** [comment]
指的是代码高亮字体、前台文本字体还是后台编辑器字体呢？

**Comment by not-know** [comment]
前台显示的字体，

**Comment by not-know** [comment]
因为我用这款插件之后会覆盖我另一个用来换字体的插件，所以每次改字体还要关掉插件去改字体，觉得有点麻烦，如果大佬您的插件支持改字体的话，我就可以把其他所有编辑器都删掉了，这个插件已经能满足我所有需求了。感谢大佬

**Comment by LuRenJiasWorld** [comment]
目前没有相关计划，因为不是所有的前台主题都可以被覆盖样式。但是你可以在WordPress主题的自定义设置中定义CSS，也能实现修改前台字体。

我之前写过一篇文章，可供你参考：https://untitled.pw/programming/programming-html/564.html ，将`font-family`那一段加上你所需的字体，可以实现你所需要的效果，而且一般是不会有兼容性问题的（通常优先级高于所有插件）。

**Comment by not-know** [comment]
嗯嗯，好的，麻烦大佬了

**Comment by LuRenJiasWorld** [comment]
好，你先试一下。此外本插件转换出来的文本样式（比如标题、代码段等）也是可以通过这个方法定制的。

**Comment by not-know** [comment]
我日，这效果也太神奇了

**Comment by not-know** [comment]
有点东西   滑稽.jpg

**Comment by LuRenJiasWorld** [comment]
好的，能解决问题就OK : )

**Comment by not-know** [comment]
嗯嗯，多谢

**Comment by LuRenJiasWorld** [comment]
好，我先关闭这个Issue了。如果后面有其他问题欢迎继续反馈。

**Comment by not-know** [comment]
嗯嗯
