### ISSUE TITLE
打开设置发生错误

### ISSUE THREAD

**Issue by fansuregrin** [LuRenJiasWorld/WP-Editor.md#438]
打开插件的设置，报错：抱歉，您不能访问此页面。

请问是插件的问题还是我的问题，插件文件夹需要重命名吗，我的插件文件夹名字是WP-Editor.md。

**Comment by fansuregrin** [comment]
换成上一个版本就没有错误了

**Comment by LuRenJiasWorld** [comment]
你好，这的确是一个BUG，具体可以参考 https://github.com/LuRenJiasWorld/WP-Editor.md/pull/429 。

**Comment by fansuregrin** [comment]
好的，谢谢！
