### ISSUE TITLE
不能访问插件设置页面：抱歉，您不能访问此页面

### ISSUE THREAD

**Issue by huahuayu** [LuRenJiasWorld/WP-Editor.md#440]
## 问题描述
启用wp-editor插件后点击设置，进入`https://mydomain.com/wp-admin/plugins.php?page=wp-editormd-settings`，报错`抱歉，您不能访问此页面。`

## 环境信息
wordpress 5.3.2
wp-editor.md 10.1.0
站点启用了https

## 补充信息
把插件disable再enable，没有效果  
文章编辑不受影响

**Comment by LuRenJiasWorld** [comment]
你好，这是当前版本的一个BUG，具体请参考 https://github.com/LuRenJiasWorld/WP-Editor.md/issues/438 。

抱歉带来不便。
