### ISSUE TITLE
支持Enlighter插件做markdown代码语法高亮吗

### ISSUE THREAD

**Issue by huahuayu** [LuRenJiasWorld/WP-Editor.md#441]
## 问题描述
WP-Editor自带的语法高亮样式我不太喜欢，而且在开启行号后，比如说代码有100行，最后面大概6-7却没有行号。

请问可以支持[Enlighter](https://wordpress.org/plugins/enlighter/)做代码高亮吗？

**Comment by LuRenJiasWorld** [comment]
你好，目前不支持。

你提到的没有行号的问题应该是主题字体覆盖了代码高亮的字体，方便的话可以给个示例链接，我帮你排查一下问题。

如果不喜欢自带的语法高亮样式，可以在 https://github.com/LuRenJiasWorld/Prism.js-style 找到更多的样式。此外只要是兼容Prism.js的样式都可以通过这个方法加载进去，Prism.js的生态还是非常庞大的。

**Comment by LuRenJiasWorld** [comment]
http://k88hudson.github.io/syntax-highlighting-theme-generator/www/
如果还是觉得不太满意的话，这里有一个Prism.js高亮样式生成器。

**Comment by huahuayu** [comment]
你好，我想给你演示一下行号的问题，但是好像我又发现一个问题，设置里面开启行号展示了，怎么[文章](https://liushiming.cn/2020/02/25/java-inner-class/)里面的代码不带行号的 
![image](https://user-images.githubusercontent.com/1725060/78109518-f0c3c900-742b-11ea-915f-42f8b0d58dbd.png)

![image](https://user-images.githubusercontent.com/1725060/78109620-223c9480-742c-11ea-953f-2a893989f706.png)

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/78110227-26b57d00-742d-11ea-95de-8940fec98171.png)

可能是因为这个资源加载失败导致的。

很奇怪的是Prism.js并不包含这个文件，请问有检查过和其他插件的兼容性吗？可以尝试一下分别关闭每个插件后看看问题是否还能复现。

**Comment by huahuayu** [comment]
> 你好，目前不支持。

> 你提到的没有行号的问题应该是主题字体覆盖了代码高亮的字体，方便的话可以给个示例链接，我帮你排查一下问题。

> 如果不喜欢自带的语法高亮样式，可以在 https://github.com/LuRenJiasWorld/Prism.js-style 找到更多的样式。此外只要是兼容Prism.js的样式都可以通过这个方法加载进去，Prism.js的生态还是非常庞大的。

谢谢提醒，我选用了一个自定义样式  

但是高亮关键字识别的问题麻烦看下  https://github.com/LuRenJiasWorld/WP-Editor.md/issues/442

**Comment by LuRenJiasWorld** [comment]
你好，我这边没能复现这个问题。

查看你的网站，发现Prism.js的行号插件已经成功加载，但不知道什么原因未能应用。

你可以先检查一下与其他插件或主题的兼容性，或是在WP Editor.md的设置中打开兼容模式试试看
