### ISSUE TITLE
代码块行号问题

### ISSUE THREAD

**Issue by huahuayu** [LuRenJiasWorld/WP-Editor.md#443]
## 问题描述
wp-editor.md设置hang'h行号已开启
![image](https://user-images.githubusercontent.com/1725060/78115475-726c2480-7435-11ea-9cdc-1bdbbb3e3d87.png)

有的文章不显示行号  
https://liushiming.cn/2020/03/21/use-selinux-port-labeling-to-allow-services-to-use-non-standard-ports/

有的显示了行号  
https://liushiming.cn/2020/02/25/java-inner-class/

这是怎么回事呢？

**Comment by LuRenJiasWorld** [comment]
> 有的文章不显示行号
> https://liushiming.cn/2020/03/21/use-selinux-port-labeling-to-allow-services-to-use-non-standard-ports/

![image](https://user-images.githubusercontent.com/29622423/78116329-b3b10400-7436-11ea-9159-ad265b33fe66.png)

这个没有标注`language-xxx`的class，请问在后台编辑器编辑这篇文章的时候，代码块部分是什么样子呢，可以给一个截图吗？

**Comment by huahuayu** [comment]
文章在这里
https://github.com/huahuayu/articles/blob/bb724fd835c3602105237e9b52f6b4c075cdbc02/2020/centos%E8%AE%BE%E7%BD%AE%E6%9C%8D%E5%8A%A1%E4%BD%BF%E7%94%A8%E9%9D%9E%E6%A0%87%E5%87%86%E7%AB%AF%E5%8F%A3.md

**Comment by LuRenJiasWorld** [comment]
> 文章在这里
> https://github.com/huahuayu/articles/blob/bb724fd835c3602105237e9b52f6b4c075cdbc02/2020/centos%E8%AE%BE%E7%BD%AE%E6%9C%8D%E5%8A%A1%E4%BD%BF%E7%94%A8%E9%9D%9E%E6%A0%87%E5%87%86%E7%AB%AF%E5%8F%A3.md

明白了。你在WordPress后台对这篇文章进行编辑（可以不用修改内容），然后点击更新，触发文章的重渲染试试看。

为了保障使用本插件之后页面的渲染性能，Markdown -> HTML只会在重新渲染的时候生效，也就是说如果之前没有启动代码高亮功能，就不会携带`language-xxx`的class。直接更新文章问题应该就能解决。

**Comment by huahuayu** [comment]
> > 文章在这里
> > https://github.com/huahuayu/articles/blob/bb724fd835c3602105237e9b52f6b4c075cdbc02/2020/centos%E8%AE%BE%E7%BD%AE%E6%9C%8D%E5%8A%A1%E4%BD%BF%E7%94%A8%E9%9D%9E%E6%A0%87%E5%87%86%E7%AB%AF%E5%8F%A3.md
> 
> 明白了。你在WordPress后台对这篇文章进行编辑（可以不用修改内容），然后点击更新，触发文章的重渲染试试看。
> 
> 为了保障使用本插件之后页面的渲染性能，Markdown -> HTML只会在重新渲染的时候生效，也就是说如果之前没有启动代码高亮功能，就不会携带`language-xxx`的class。直接更新文章问题应该就能解决。

这是不是有点太手动了？

**Comment by LuRenJiasWorld** [comment]
> > > 文章在这里
> > > https://github.com/huahuayu/articles/blob/bb724fd835c3602105237e9b52f6b4c075cdbc02/2020/centos%E8%AE%BE%E7%BD%AE%E6%9C%8D%E5%8A%A1%E4%BD%BF%E7%94%A8%E9%9D%9E%E6%A0%87%E5%87%86%E7%AB%AF%E5%8F%A3.md
> > 
> > 明白了。你在WordPress后台对这篇文章进行编辑（可以不用修改内容），然后点击更新，触发文章的重渲染试试看。
> > 
> > 为了保障使用本插件之后页面的渲染性能，Markdown -> HTML只会在重新渲染的时候生效，也就是说如果之前没有启动代码高亮功能，就不会携带`language-xxx`的class。直接更新文章问题应该就能解决。
> 
> 这是不是有点太手动了？

目前无法避免，因为PHP无法常驻后台执行定时任务。将来的版本可能会在设置菜单中新增一个一键全部更新的功能。

**Comment by huahuayu** [comment]
一键全部更新文章吗？那文章的lastUpdateTime都被更新了

**Comment by LuRenJiasWorld** [comment]
> 一键全部更新文章吗？那文章的lastUpdateTime都被更新了  

嗯，但是posttime应该不会变化。我尽量保证对文章本身没有影响吧。

**Comment by huahuayu** [comment]
postTime是没有变，但是只要save一次lastUpdateTime就会变化一次，不管有没有改

**Comment by LuRenJiasWorld** [comment]
> postTime是没有变，但是只要save一次lastUpdateTime就会变化一次，不管有没有改

我会想办法避免这个值变化的。
