### ISSUE TITLE
代码高亮 - 建议默认代码内容为text

### ISSUE THREAD

**Issue by huahuayu** [LuRenJiasWorld/WP-Editor.md#444]
## 问题描述
用```来写代码块的时候，如果没标识是java,html,c,bash等，展示起来就很丑，而且字体字号都好像不一样  

![image](https://user-images.githubusercontent.com/1725060/78116084-5f0d8900-7436-11ea-895c-588378dd9e4f.png)
https://liushiming.cn/2020/03/12/docker-cookbook/

我建议用户没写就自动当text渲染，虽然你说text识别不了，但好歹也经过渲染的，看起来会一致点

**Comment by LuRenJiasWorld** [comment]
因为涉及到上游代码，我这边不便修改。

但Prism.js官方仓库有用户提到过这个问题：https://github.com/PrismJS/prism/issues/344

最终的解决方案是引入了一门叫做`none`的”语言“，使用这个语言之后就能实现无代码高亮但依旧使用Prism.js，你可以试试看。

我会在将来的使用文档（正在撰写中）提到这个问题的。感谢反馈。

**Comment by huahuayu** [comment]
这个应该有办法解决的吧，实在是很难受的，我今天花了很多时间给我的文章逐一检查，有代码段的地方全部加上语言标识，如果是一般文字就标注text。如果不这么做展示风格就不统一。

不可能所有用户都会去标注语言的，就不能用户没标注的时候默认一个text吗。

**Comment by LuRenJiasWorld** [comment]
> 这个应该有办法解决的吧，实在是很难受的，我今天花了很多时间给我的文章逐一检查，有代码段的地方全部加上语言标识，如果是一般文字就标注text。如果不这么做展示风格就不统一。
> 
> 不可能所有用户都会去标注语言的，就不能用户没标注的时候默认一个text吗。

默认是可行的，但需要为none，理由同上，我抽空看一下如何实现。
