### ISSUE TITLE
代码过长，不要自动换行，用滚动条看更友好

### ISSUE THREAD

**Issue by huahuayu** [LuRenJiasWorld/WP-Editor.md#445]
## 问题描述
有时候一行代码过长，超出了文本框的范围，请不要自动换行，而是提供滚动条向右拉着看会比较好  

![image](https://user-images.githubusercontent.com/1725060/78264834-42f11100-7536-11ea-91c5-77dad46e93f8.png)

自动换行看起来代码好乱啊  
https://liushiming.cn/2020/03/05/drools-example-ecommerce-pricing/

**Comment by LuRenJiasWorld** [comment]
是否换行是由所使用的代码高亮主题决定的，因为这些主题属于他人的项目，不便直接修改。

你可以自行修改样式中关于换行的部分进行解决或更换其他代码高亮主题。
