### ISSUE TITLE
与Eaplayer等音乐插件冲突

### ISSUE THREAD

**Issue by imashen** [LuRenJiasWorld/WP-Editor.md#447]
未启用插件之前，音乐插件可以正常工作，启用后音乐插件（包括HermitX等）基本凉凉。。。无情啊
希望可以修复一下兼容性

**Comment by LuRenJiasWorld** [comment]
请问有尝试开启本插件的兼容模式吗？

**Comment by imashen** [comment]
哦，我试一下

**Comment by LuRenJiasWorld** [comment]
好的。

**Comment by imashen** [comment]
嗯，蟹蟹，兼容模式就好了，还有一个BUG，就是在插件列表直接点击设置的时候会显示“抱歉，您不能访问此页面。”

**Comment by LuRenJiasWorld** [comment]
> 嗯，蟹蟹，兼容模式就好了，还有一个BUG，就是在插件列表直接点击设置的时候会显示“抱歉，您不能访问此页面。”

嗯嗯，这个问题是一个已知的BUG，近期会发布新版本修复这一问题。

**Comment by imashen** [comment]
好的，感谢帮助，您忙
