### ISSUE TITLE
Katex does not work in the preview block

### ISSUE THREAD

**Issue by HilbertYu** [LuRenJiasWorld/WP-Editor.md#449]
The following picture is the capture from my homepage, it is a preview block (one of the recent posts).

![preview](https://user-images.githubusercontent.com/7413925/79041170-32205980-7c20-11ea-9244-cf71f770b25a.png)

The following picture is the post. 
![post](https://user-images.githubusercontent.com/7413925/79041211-8c211f00-7c20-11ea-949a-5379d21cb386.png)

It's seem to Katex does not work in the preview block.

I'm not sure that's a issue of this plugin. Maybe a theme's issue.

**Comment by LuRenJiasWorld** [comment]
It should be the theme's issue.

You can check it by using the DevTools of your browser, see if katex.min.js has loaded in the homepage.

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/79041643-e2439180-7c23-11ea-845b-345cdf355105.png)

Normally it should be loaded like this, and LaTeX will be displayed correctly.
