### ISSUE TITLE
图片上传完成之后，不会自动变成链接

### ISSUE THREAD

**Issue by 0xkjAlbert** [LuRenJiasWorld/WP-Editor.md#450]
## 问题描述
图片粘贴后，会显示图片上传中...然后就不变了，10.1.11和10.1.12两个版本都是这样的
在查看了服务器相应uploda文件夹后，发现图片上传成功了，直接访问链接也是可以的，但是[图片上传中...]几个字不变成链接，我用10.0.8版本是没问题的，CentOS7.6和Ubuntu1804的测试结果是一样的
## 配置图片
![1](https://blog.gaokejian.cn/wp-content/uploads/2020/04/2cb445897bc71ef2e87945e9597423cb.png)
配置图片地址：https://blog.gaokejian.cn/wp-content/uploads/2020/04/2cb445897bc71ef2e87945e9597423cb.png

## 一键安装脚本
一键安装脚本，和我的环境相同，方便搭建
[Ubuntu安装lnmp](https://www.gaokejian.cn/?p=8)
[CentOS安装lnmp](https://www.gaokejian.cn/?p=46)

**Comment by LuRenJiasWorld** [comment]
好的，我先测试下能否复现。

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/79060285-e3250380-7cb5-11ea-9d35-7f9068a19113.png)

你好，我这边的测试环境似乎没有复现这个问题。请问在出现此问题的时候浏览器控制台有报错吗？有的话麻烦截个图我看看。

**Comment by 0xkjAlbert** [comment]
![image](https://user-images.githubusercontent.com/29065575/79061274-01443100-7cc1-11ea-9bc6-3788ee4775b0.png)
控制台报错是这样的，谢谢

**Comment by LuRenJiasWorld** [comment]
500的话不太好判断，初步推测可能是权限问题或是上传文件体积问题，也有可能是缺失图片处理相关的PHP扩展。

建议你打开PHP的错误日志功能，然后查看Console报错时候的错误日志，根据错误日志的内容来决定该怎么做。

**Comment by 0xkjAlbert** [comment]
![image](https://user-images.githubusercontent.com/29065575/79063792-68201500-7cd6-11ea-91c5-e497216d64b4.png)
看起来是因为imagecreatefrompng函数引起的问题，查了一下要编译GD进去，我试试编译GD重新编译php怎么样

但是10.0.8版本是没有问题的，我查了一下，10.0.8这个版本里没有这个函数，是因为用了gd这个库的原因把

**Comment by LuRenJiasWorld** [comment]
是的，因为在之前的版本存在一个问题：粘贴后的图片上传到服务器压缩率非常低，一个原始体积500KB的文件直接保存后体积高达3.5MB。因此我引入了GD对图片进行压缩。

未来版本会加入该功能的开关，也会允许用户对压缩率、最小尺寸等进行调节，但目前建议还是安装一下GD库。

考虑到你使用的是一键安装包，推荐编译安装，这里有一篇[文档](https://www.jb51.net/article/171435.htm)可能会帮到你（仅供参考，注意版本号必须和你PHP版本号完全对应）。

**Comment by 0xkjAlbert** [comment]
非常感谢，尝试了一下手动编译有点麻烦，所以用yum和apt装了库重新编译了php就可以了
写了个博客[安装php gd库](https://www.gaokejian.cn/?p=56)
这个问题解决了

**Comment by LuRenJiasWorld** [comment]
> 非常感谢，尝试了一下手动编译有点麻烦，所以用yum和apt装了库重新编译了php就可以了
> 写了个博客[安装php gd库](https://www.gaokejian.cn/?p=56)
> 这个问题解决了

非常棒，我会在今后版本的文档中注明库依赖的。

**Comment by shengqiangzhang** [comment]
> 是的，因为在之前的版本存在一个问题：粘贴后的图片上传到服务器压缩率非常低，一个原始体积500KB的文件直接保存后体积高达3.5MB。因此我引入了GD对图片进行压缩。
> 
> 未来版本会加入该功能的开关，也会允许用户对压缩率、最小尺寸等进行调节，但目前建议还是安装一下GD库。
> 
> 考虑到你使用的是一键安装包，推荐编译安装，这里有一篇[文档](https://www.jb51.net/article/171435.htm)可能会帮到你（仅供参考，注意版本号必须和你PHP版本号完全对应）。

请问现在加入了该功能的开关了吗？

**Comment by LuRenJiasWorld** [comment]
> > 是的，因为在之前的版本存在一个问题：粘贴后的图片上传到服务器压缩率非常低，一个原始体积500KB的文件直接保存后体积高达3.5MB。因此我引入了GD对图片进行压缩。
> > 未来版本会加入该功能的开关，也会允许用户对压缩率、最小尺寸等进行调节，但目前建议还是安装一下GD库。
> > 考虑到你使用的是一键安装包，推荐编译安装，这里有一篇[文档](https://www.jb51.net/article/171435.htm)可能会帮到你（仅供参考，注意版本号必须和你PHP版本号完全对应）。
> 
> 请问现在加入了该功能的开关了吗？

抱歉暂时还没有，预计会在下一个版本加入。
