### ISSUE TITLE
是否考虑图片链接不带域名以便改改域名上证书

### ISSUE THREAD

**Issue by 0xkjAlbert** [LuRenJiasWorld/WP-Editor.md#451]
## 问题描述
原来没有域名的时候，使用ip访问图片地址格式为http://1.1.1.1/wp-content/uploads/2020/04/xxx.png
买了个域名，搭建了服务器之后，就变成了http://xxx.com/wp-content/uploads/2020/04/xxx.png
所有的图片都需要改掉域名才能正常显示
后来换了个域名，又要改域名
买了证书做https，有需要把图片改地址了

## 小建议
我发现可以使用/wp-content/uploads/2020/04/xxx.png的方式，就可以避免这个问题，方便迁移，直接把数据库备份然后迁移就可以了
所以，作者大佬有没有改下图片地址的计划？

**Comment by LuRenJiasWorld** [comment]
可以考虑。我先评估一下能否实现。

**Comment by LuRenJiasWorld** [comment]
你好，这个功能需要涉及到对WordPress文件上传机制的修改，可能不便实现。

但我推荐你尝试一下Velvet Blues Update URLs这个插件，只要设置旧域名和新域名，它就会自动修改所有的链接（原理是遍历数据库，将旧域名替换为新域名）。

如果这个插件对你有效，麻烦回复一下本Issue。未来我会在使用文档中提到该常见问题。

**Comment by 0xkjAlbert** [comment]
非常感谢，试了试这个插件，是可以改的，但是这个插件貌似有个小bug，可以更改文章的所有链接，但是在文章编辑页面是不更改的，也就是说，添加新内容的时候，会把改的链接改回原来的链接，这时候需要重新更新一下链接，不过没有多次测试，也有可能是环境问题

**Comment by LuRenJiasWorld** [comment]
> 添加新内容的时候，会把改的链接改回原来的链接，这时候需要重新更新一下链接

这句话不是很理解，你在迁移域名之后，有没有及时修改WordPress的站点域名呢？如果没有修改的话，那么地址还会是之前的地址。

**Comment by 0xkjAlbert** [comment]
就是查看那个页面的时候是改好了的，但是编辑页面还是原来的地址，这时候你想改动或者添加一些东西，点更新，由于编辑页面是原来的地址，所以就变成原来的地址了，需要再次使用插件改
![image](https://user-images.githubusercontent.com/29065575/79064215-918e7000-7cd9-11ea-9026-94ad6bcccd51.png)
![image](https://user-images.githubusercontent.com/29065575/79064234-c3073b80-7cd9-11ea-8723-41c75569387d.png)
![image](https://user-images.githubusercontent.com/29065575/79064255-e5995480-7cd9-11ea-883f-a560fc871211.png)
![image](https://user-images.githubusercontent.com/29065575/79064265-17aab680-7cda-11ea-821d-21147b1c9b22.png)
![image](https://user-images.githubusercontent.com/29065575/79064288-390ba280-7cda-11ea-8921-6a64414e1cfd.png)

你复现一下试试，应该是可以复现的
版本是这个
![image](https://user-images.githubusercontent.com/29065575/79064300-580a3480-7cda-11ea-94c8-aa096555c421.png)

**Comment by LuRenJiasWorld** [comment]
明白了，这个问题的确有些棘手，因为Markdown原文和转换后的HTML是分开的，所以说可能这个插件只修改了转换后的HTML。

你可以参考[这篇文章](https://www.yuanzifan.com/54048.html)了解如何手动执行SQL语句达到你的需求，需要注意的是：要同时对`post_content`和`post_content_filtered`两个字段进行替换，此处的`post_content_filtered`就是WP Editor.md插件存储Markdown原文的地址。

未来的版本可能依旧不会加入一键修改或自动适配的功能（可能会与其他插件存在潜在冲突），但我会在将来的文档中提到如何在安装本插件的前提下切换域名。

**Comment by 0xkjAlbert** [comment]
好的，非常感谢

**Comment by TianyiPeng** [comment]
> ## 问题描述
> 原来没有域名的时候，使用ip访问图片地址格式为http://1.1.1.1/wp-content/uploads/2020/04/xxx.png
> 买了个域名，搭建了服务器之后，就变成了http://xxx.com/wp-content/uploads/2020/04/xxx.png
> 所有的图片都需要改掉域名才能正常显示
> 后来换了个域名，又要改域名
> 买了证书做https，有需要把图片改地址了
> 
> ## 小建议
> 我发现可以使用/wp-content/uploads/2020/04/xxx.png的方式，就可以避免这个问题，方便迁移，直接把数据库备份然后迁移就可以了
> 所以，作者大佬有没有改下图片地址的计划？

感谢提问和作者的回答，我也遇到了类似的问题。不过我发现我要使用的链接是```![title](../wp-content/uploads/2020/04/xxx.png)```。需要往上一层到wp-content，比较神奇，有点好奇它默认的目录是在哪。

![image](https://user-images.githubusercontent.com/3522518/102696283-107d6600-41e2-11eb-81bc-ad0699c434f1.png)

但是，当我publish这个页面的时候，链接就失效了。似乎publish中用到的默认目录和在编辑器edit时用的不一样？我没有找到使publish页面work的relative path。
![image](https://user-images.githubusercontent.com/3522518/102696297-29861700-41e2-11eb-88a2-28eb9b233cbc.png)

**Comment by LuRenJiasWorld** [comment]
> > ## 问题描述
> > 原来没有域名的时候，使用ip访问图片地址格式为http://1.1.1.1/wp-content/uploads/2020/04/xxx.png
> > 买了个域名，搭建了服务器之后，就变成了http://xxx.com/wp-content/uploads/2020/04/xxx.png
> > 所有的图片都需要改掉域名才能正常显示
> > 后来换了个域名，又要改域名
> > 买了证书做https，有需要把图片改地址了
> > ## 小建议
> > 我发现可以使用/wp-content/uploads/2020/04/xxx.png的方式，就可以避免这个问题，方便迁移，直接把数据库备份然后迁移就可以了
> > 所以，作者大佬有没有改下图片地址的计划？
> 
> 感谢提问和作者的回答，我也遇到了类似的问题。不过我发现我要使用的链接是`![title](../wp-content/uploads/2020/04/xxx.png)`。需要往上一层到wp-content，比较神奇，有点好奇它默认的目录是在哪。
> 
> ![image](https://user-images.githubusercontent.com/3522518/102696283-107d6600-41e2-11eb-81bc-ad0699c434f1.png)
> 
> 但是，当我publish这个页面的时候，链接就失效了。似乎publish中用到的默认目录和在编辑器edit时用的不一样？我没有找到使publish页面work的relative path。
> ![image](https://user-images.githubusercontent.com/3522518/102696297-29861700-41e2-11eb-88a2-28eb9b233cbc.png)

你好，可以提供下图片链接挂掉的站点地址吗，我看看具体是什么情况。
