### ISSUE TITLE
editormd-html-textarea 文本标签中未生成高亮代码

### ISSUE THREAD

**Issue by beezen** [LuRenJiasWorld/WP-Editor.md#453]
![wp-editormd-debug-info](https://user-images.githubusercontent.com/13111739/79250781-cb19d380-7eb1-11ea-84e9-6648b99d64ec.png)
<img width="1260" alt="代码高亮问题" src="https://user-images.githubusercontent.com/13111739/79250797-d0771e00-7eb1-11ea-921e-d26b985e589c.png">

如上图所示，编辑器中显示了高亮代码，但并没有在editormd-html-textarea标签中显示完整，所以提交到数据库，以及到前台页面展示时，没有高亮效果。

不知道是哪一步操作有问题，希望指导一下，谢谢。

**Comment by LuRenJiasWorld** [comment]
可以提供一下你的Markdown原文和出现问题的示例链接吗？

**Comment by beezen** [comment]
不好意思 。   之前是我对使用方法理解有误，没有理解prism.js的使用原理  现在问题已经解决了 非常感谢
