### ISSUE TITLE
去掉勾选“显示代码言语” 设置，不居中显示了

### ISSUE THREAD

**Issue by xianyun666** [LuRenJiasWorld/WP-Editor.md#454]
![w1](https://user-images.githubusercontent.com/22339210/79731390-cd9e8200-8324-11ea-9027-b9e30f6a72ab.png)
如图，去掉勾选“显示代码言语” 不居中显示了，并且我“代码粘贴”是勾选的，也不显示 "copy"按钮了。

还有“显示代码言语”和“代码粘贴”是不是不合适？建议改成“显示代码语言”和“代码复制”

**Comment by LuRenJiasWorld** [comment]
居中显示这个取决于你的主题，你可以先切换到其他主题看看问题是否依旧存在。

关于本地化的问题我会考虑修改的，你也可以提交Pull Request帮助本项目提升本地化质量: )

**Comment by xianyun666** [comment]
> 居中显示这个取决于你的主题，你可以先切换到其他主题看看问题是否依旧存在。
> 
> 关于本地化的问题我会考虑修改的，你也可以提交Pull Request帮助本项目提升本地化质量: )

我使用的是wordpress的默认主题

**Comment by LuRenJiasWorld** [comment]
> > 居中显示这个取决于你的主题，你可以先切换到其他主题看看问题是否依旧存在。
> > 关于本地化的问题我会考虑修改的，你也可以提交Pull Request帮助本项目提升本地化质量: )
> 
> 我使用的是wordpress的默认主题

那麻烦提供一个测试的链接，我看看是什么情况吧。

**Comment by LuRenJiasWorld** [comment]
啊，不用提供了，我本地也复现出了你描述的问题。

**Comment by LuRenJiasWorld** [comment]
> 如图，去掉勾选“显示代码言语” 不居中显示了

临时的解决方法：使用自定义主题的自定义CSS功能，加入如下CSS样式：

```css
pre[class*="language-"].line-numbers {
        margin: auto;
}
```

然后保存，刷新页面看看现在能否居中。

这一行CSS我会在下个版本加入，之前的确没有考虑到会与这种布局的主题出现冲突。

> 并且我“代码粘贴”是勾选的，也不显示 "copy"按钮了

这个问题会略微复杂一点，我还在分析，稍后给你答复。

**Comment by LuRenJiasWorld** [comment]
你好，问题已查明，你所提到的两个BUG都来自于同一处错误，问题已修复，参考： https://github.com/LuRenJiasWorld/WP-Editor.md/commit/e0ff68163ac689571cdfcace75076b246cd4c1b8 

你提到的措辞/本地化问题也已经进行了微调：https://github.com/LuRenJiasWorld/WP-Editor.md/commit/a84bf22552145264c7fba600799c08441c045101

这些修复将于五月底的下一版本（10.2.0）进行更新，感谢反馈。
