### ISSUE TITLE
无法兼容主题Astra

### ISSUE THREAD

**Issue by leveychen** [LuRenJiasWorld/WP-Editor.md#455]
1.评论页面一直处于转圈圈，并且导致页面正文的代码高亮着色失效

![image](https://user-images.githubusercontent.com/3397361/79983216-016ed880-84da-11ea-84c5-139e0fa6f53a.png)

2.后台评论管理界面也是代码高亮着色异常

````config
系统环境	Linux
运行环境	Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.4.5
PHP版本	7.4.5
PHP运行环境	apache2handler
浏览器信息	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
WordPress版本	5.4
插件版本	10.1.2
jQuery版本	1.12.4
当前用户权限	administrator
WordPress地址	https://levey.cn
站点地址	https://levey.cn
常规设置	task_list => on
imagepaste => on
imagepaste_sm => on
image_link => on
open_in_new_tab => on
live_preview => on
sync_scrolling => on
html_decode => on
support_front => on
support_reply => on
support_other_text =>
编辑器设置	theme_style => default
code_style => default
editor_addres => https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.1.2
语法高亮设置	highlight_mode_auto => on
line_numbers => off
show_language => on
copy_clipboard => on
highlight_library_style => customize
customize_my_style => https://cdn.jsdelivr.net/wp/wp-editormd/assets/prismjs-style/darcula/prism-darcula.min.css
Emoji表情设置	support_emoji => on
文章目录设置	support_toc => off
科学公式设置	support_latex => katex
绘图设置	support_latex => katex
高级设置	jquery_compatible => on
hide_ads => off
启用插件列表	
0 => customizer-search/customizer-search.php
1 => no-category-base-wpml/no-category-base-wpml.php
2 => simple-tags/simple-tags.php
3 => uss-upyun/upyun-uss-wordpress.php
4 => wp-editormd/wp-editormd.php
5 => wp-mail-smtp/wp_mail_smtp.php
6 => wp-super-cache/wp-cache.php
````

**Comment by LuRenJiasWorld** [comment]
评论功能目前有较多的BUG，的确会出现一些问题，目前的计划是在下个版本予以修复。

请问可以截一下控制台的报错信息帮助跟踪问题吗？如果能提供一下复现故障的地址就更好了。

**Comment by leveychen** [comment]
[](url)https://levey.cn/1

![image](https://user-images.githubusercontent.com/3397361/80002532-57e81100-84f2-11ea-8d22-63b33e79aaaf.png)


在线地址在这，感谢跟进

**Comment by LuRenJiasWorld** [comment]
请问你有尝试过开启或关闭后台的思维导图功能吗？问题应该是出在这里。

具体我后面再分析一下，最近大部分时间在忙其他部分的功能更新，相关修复有进展后我会更新此Issue。

**Comment by leveychen** [comment]
对思维导图功能及其他功能反复横跳之后，评论界面UI正常的，但是代码高亮的主题失效了，切换会默认高亮主题，将就一下先 🍡

**Comment by LuRenJiasWorld** [comment]
> 对思维导图功能及其他功能反复横跳之后，评论界面UI正常的，但是代码高亮的主题失效了，切换会默认高亮主题，将就一下先 🍡

主题失效一般原因是CSS样式被当前使用的主题覆盖导致的，可以试试看自定义样式功能，或是对主题的CSS进行修改（一些主题会自带代码高亮的样式）。

**Comment by LuRenJiasWorld** [comment]
你好，这个问题已于 https://github.com/LuRenJiasWorld/WP-Editor.md/commit/6e3be1eef92a838584731bc763ad8457b82cefab 得以解决（是一个低级错误），将在月底发布的10.2.0版本予以修复。再次感谢对本插件的支持，如果遇到其他问题欢迎及时反馈: )

**Comment by leveychen** [comment]
好的，期待更新，稍后验证

**Comment by LuRenJiasWorld** [comment]
你好，该问题已于最新发布的 10.2.0 版本解决，再次感谢反馈，祝使用愉快。如果以后有其他问题也欢迎继续反馈~

Release：https://github.com/LuRenJiasWorld/WP-Editor.md/releases/tag/v10.2.0
