### ISSUE TITLE
“在新标签页中打开链接”功能不生效

### ISSUE THREAD

**Issue by Creling** [LuRenJiasWorld/WP-Editor.md#457]
作者大大：
我在 设置->常规设置 中点亮了“在新标签页中打开链接”，随后新建文章时，不论插入“链接”，还是“引用链接”，最终生成的页面中a标签均不包含target属性，即，无法在新标签页中打开插入的链接。望修复。
插件版本：10.1.2
wordpress版本：5.4.1

此致

**Comment by LuRenJiasWorld** [comment]
你好，可以提供一个示例地址吗？我看看是什么原因导致的。

**Comment by Creling** [comment]
抱歉未即时回复
文章示例链接如下
https://blog.azlith.com/archives/53/47

在文中搜索 `[1]` 或`[2]`即可看到外链

**Comment by LuRenJiasWorld** [comment]
好，目前似乎打不开这个站点，显示502。我明天再看看。

你也可以尝试一下更换其他主题，然后看看问题是否能复现。

**Comment by Creling** [comment]
我这里是可以打开的，由于是使用了cloudflare，可能的确在部分地区无法打开，如果方便的话可以麻烦作者挂一下梯子吗。
另，我切换为了默认主题后发现问题依然存在。

**Comment by LuRenJiasWorld** [comment]
好的，我现在可以打开了。我尽快排查一下情况，稍后给你回复。

**Comment by LuRenJiasWorld** [comment]
你好，可以上传一下你的调试信息吗？在WP Editor.md后台中可以生成对应图片，上传到这里我看看，便于复现。

我们使用的是同一个主题😄所以说应该不存在兼容性问题。

**Comment by Creling** [comment]
一直很喜欢maupassant主题的风格，但是我没有能够在wp官方市场上找到这个主题，所以说使用了GitHub上的maupassant主题 https://github.com/sdg32/maupassant 。或许底层实现和作者的主题不太一致。

调试信息如下。
![wp-editormd-debug-info](https://user-images.githubusercontent.com/43109504/81673818-c92a3c80-947e-11ea-91d1-1cc90db81a5c.png)

**Comment by LuRenJiasWorld** [comment]
好的，我这边能够复现出该问题。猜测是10.1.2版本引入的新BUG，我会尽快排查问题，予以修复。

有进展后我会更新此Issue，非常抱歉带来不便。

**Comment by LuRenJiasWorld** [comment]
你好，问题已定位，并已在 https://github.com/LuRenJiasWorld/WP-Editor.md/commit/f5a352126daea2d48b2cbb43bce0e327d4787d8a 予以解决。

---

以下是问题详情：

在之前引入该功能的时候，对应代码未对jQuery兼容模式进行区分： https://github.com/LuRenJiasWorld/WP-Editor.md/commit/0f268578b536c907ab372ba1da9db6f2876f3f9c ，导致开启兼容模式下（你这里就开启了）无法正常加载`assets/FrontStyle/frontstyle.min.js`。

该JS文件负责给文章中的`<a>`标签加上`target="_blank"`标记，因此在未能加载该文件的情况下，是无法实现在新窗口打开页面的。

类似的问题曾经在 https://github.com/LuRenJiasWorld/WP-Editor.md/commit/a14131dae60aa6295f21dfa2b9523f402c58efe6 也出现过，这部分代码过于繁琐，容易引起错漏，我会尽快优化。

再次抱歉带来不便，包含此修复的版本（10.2.0）将会于一个月后发布，发布版本后我会更新此Issue提醒你相关更新，目前无需Close。

此外，在新版本发布前你所撰写的文章只要是打开了『在新窗口打开链接』选项，修复后都能够直接支持在新窗口打开，无需额外设置。

**Comment by LuRenJiasWorld** [comment]
你好，该问题已于最新发布的 10.2.0 版本解决，再次感谢反馈，祝使用愉快。如果以后有其他问题也欢迎继续反馈~

Release：https://github.com/LuRenJiasWorld/WP-Editor.md/releases/tag/v10.2.0
