### ISSUE TITLE
在代码块中反斜线被转义的问题

### ISSUE THREAD

**Issue by Y4er** [LuRenJiasWorld/WP-Editor.md#459]
在我的文章中内容为
```
C:\Windows\System32\WSReset.exe
```
发布文章前台阅读时发现`\`被吃掉，只留下了`C:WindowsSystem32cmd.exe`。

涉及到的语法为
```
    ```
     C:\Windows\System32\cmd.exe
    ```
   以及
    `C:\Windows\System32\cmd.exe`
```

怎么解决？

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/81462608-69196900-91e6-11ea-8a33-a56078ef5c9c.png)

你好，我这边似乎未能复现这个问题。猜测应该是`\`符号被转义导致的。请问你有检查过与主题或其他插件的兼容性吗？方便的话顺便贴一下WP Editor.md设置菜单中的调试信息更好。

**Comment by Y4er** [comment]
经过多次尝试，在左右分别添加空格就好了- -

玄学问题，重新发布文章时也复现不了这个问题了。

待再遇到的时候重新打开issue，感谢！

**Comment by LuRenJiasWorld** [comment]
好的，如果下次再遇到类似的问题而且可以复现，欢迎提交Issue。此外，Markdown中空格与空行的使用的确有助于减小解析时的歧义，我最近购入了wp-editor.md域名，后续会撰写相关的文档，包括Markdown语法部分。

**Comment by Y4er** [comment]
额刚想着重新发文章试一试 发现又出现了这个问题。 这次我把所有插件全禁用了，仍然存在。

```
系统环境	Linux
运行环境	nginx/1.17.8
PHP版本	7.2.23
PHP运行环境	fpm-fcgi
浏览器信息	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
WordPress版本	5.4.1
插件版本	10.1.2
jQuery版本	1.12.4
当前用户权限	administrator
常规设置	task_list => on
imagepaste => off
imagepaste_sm => off
image_link => off
open_in_new_tab => off
live_preview => on
sync_scrolling => on
html_decode => off
support_front => off
support_reply => off
support_other_text =>
编辑器设置	theme_style => default
code_style => default
editor_addres => https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.1.2
语法高亮设置	highlight_mode_auto => on
line_numbers => off
show_language => on
copy_clipboard => on
highlight_library_style => default
customize_my_style =>
Emoji表情设置	support_emoji => on
文章目录设置	support_toc => off
科学公式设置	0 =>
绘图设置	support_katex => off
高级设置	jquery_compatible => on
hide_ads => on
启用插件列表	1 => wp-editormd/wp-editormd.php
```

[这个链接](https://gist.githubusercontent.com/Y4er/15816e73e7993ec29c8f9b80ea66e2e0/raw/e70579e4d6a9909975b56b2bc814dcdacce9b997/post.md)是我的markdown内容

具体问题表现为：
1. 私密文章及预览都正常，但是发布出来反斜线就被吃掉
2. 在更新文章的等待过程中，刷新文章正常，等待更新完成后再刷新又被吃掉

以前没有这个问题，今天发文章的时候才出现的，感谢！

**Comment by LuRenJiasWorld** [comment]
好，我尝试复现一下。

**Comment by Y4er** [comment]
补充：我原以为是cloudflare的问题，然后关闭了cloudflare仍然无效。

从回收站还原的文章中反斜线也被吃掉

![image](https://user-images.githubusercontent.com/40487319/81467230-fcb06100-9209-11ea-927b-46870d171c65.png)

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/81467238-0c2faa00-920a-11ea-9446-8288d129c2f8.png)

似乎还是未能重现你描述的问题，我这边测试环境也使用了CloudFlare。

如果你会使用MySQL数据库的话，麻烦看看WordPress数据库中wp_posts表中对应文章的记录是否反斜线也消失掉了。

**Comment by LuRenJiasWorld** [comment]
顺便提一下，感觉调试信息中存在一些不太正常的项目，10.1.2版本不应该存在`support_katex => off`，因为我在10.1.2版本已经将其改名为`support_latex`。

你也可以尝试一下重新安装（从WordPress官方商店）后，试试看能否解决你的问题。

**Comment by Y4er** [comment]
在我的数据库中，反引号已经被吃掉了，另外我重新安装了编辑器，仍然不行。

**Comment by Y4er** [comment]
解决了，问题出现在主题上，主题会自动替换远程图片资源，在替换的时候进行了自动转义😂，打扰了，感谢您的帮助。

**Comment by LuRenJiasWorld** [comment]
> 解决了，问题出现在主题上，主题会自动替换远程图片资源，在替换的时候进行了自动转义😂，打扰了，感谢您的帮助。

原来如此，那你修改主题相关的源码就OK了: )
