### ISSUE TITLE
在代码块很多的情况下不能够很好的识别各个代码块的部分

### ISSUE THREAD

**Issue by chenjiefeng2001** [LuRenJiasWorld/WP-Editor.md#460]
如果在一个文章中插入的代码块数量过多，则会出现识别代码块错误的情况。例如上下两个代码块之间隔有一个h4的标签，则编辑器会把上下两个代码块的的结束符和开始符之间看作是一个代码块，导致会标签被标记为代码块，而代码却并未被标记

**Comment by chenjiefeng2001** [comment]
```
代码块1
 ```
<h1>这是一个标签</h1>

 ```
代码块2
 ```
上述的代码如果叠加的比较多的话会导致中间的被标记

**Comment by LuRenJiasWorld** [comment]
这种情况下，建议在代码块上下均加入一个空行，否则解析器无法正常解析。你可以试试看能否解决你的问题。
