### ISSUE TITLE
一打开了插件，我的网站就进不去了。

### ISSUE THREAD

**Issue by Ripple-zjw** [LuRenJiasWorld/WP-Editor.md#461]
你好，最近在用编辑器的时候遇到了一些问题。只要一打开插件，网站就会无限加载，一直进不去，但是后台进得去。要把插件关掉网站才能进去。感觉也不可能是主题冲突，因为就是主题的作者推荐使用这个编辑器的，好像作者用着就没事。

**Comment by edmund-zhao** [comment]
我也是一样的，请问如何解决

**Comment by LuRenJiasWorld** [comment]
> 我也是一样的，请问如何解决

请问可以提供一下能复现故障的站点地址吗？

**Comment by edmund-zhao** [comment]
解决了，是WP-EDITOR与Themes不兼容问题

**Comment by LuRenJiasWorld** [comment]
好的，方便告知一下使用的是哪款主题吗？我看看能否在编辑器侧解决这个问题。

**Comment by hufenghuanyu** [comment]
我用这个模板，有类似问题：Maupassant 作者：cho, grafting by mufeng

**Comment by hufenghuanyu** [comment]
同样主题下，这个WP Githuber MD插件就没问题，但这个插件不如你这个好用

**Comment by LuRenJiasWorld** [comment]
你好，最近两年由于个人原因，没有跟进插件维护，现在开始继续维护，正在处理堆积的 Issue。
由于这个 Issue 没有进一步提供信息，或提供有效复现方法，或不确定您是否还在使用该插件，暂时先关闭处理。
如果您依然使用该插件，或希望继续推进该问题的解决，欢迎重新打开 Issue，我会尽力&尽快跟进。
感谢支持和理解。
