### ISSUE TITLE
请问我docker下的WordPress无法启用这个插件

### ISSUE THREAD

**Issue by sunerpy** [LuRenJiasWorld/WP-Editor.md#462]
Warning: require_once(/var/www/html/wp-content/plugins/WP-Editor.md-master/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/WP-Editor.md-master/wp-editormd.php on line 27 Fatal error: require_once(): Failed opening required '/var/www/html/wp-content/plugins/WP-Editor.md-master/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/WP-Editor.md-master/wp-editormd.php on line 27

上面这个报错   头大呀新手

**Comment by LuRenJiasWorld** [comment]
你好，请问你是直接从Git下载的吗？目前master分支并不直接可用，因为新版本还在开发中，你可以从release中下载最新版本zip包上传安装。

当然，最推荐的方式还是直接从WordPress插件商店一键安装。

**Comment by sunerpy** [comment]
不行呀   我从商店安装一直失败  用的是阿里的ECS  估计连接太慢了 我自己从git下载然后加压上传到服务器目录下  在插件商店启用就是上面那个失败报错
但是瞎鼓捣了鼓捣，就是在容器里执行了composer install之后，插件商店就可以启用了，但是估计还有问题，报错“PHP Fatal error：wp-editormd.php on line 28” ，不过好在可以用了现在，我慢慢学习学习再看

**Comment by LuRenJiasWorld** [comment]
在[release页面](https://github.com/LuRenJiasWorld/WP-Editor.md/releases)下载也会报错吗？这边应该是不需要composer install的。

**Comment by sunerpy** [comment]
是的呀  我下载的10.1.2的  解压上传到WordPress的plugins文件夹下面  启用就报错上面那个   在容器里执行composer install 才可以在WordPress的插件中启用

**Comment by LuRenJiasWorld** [comment]
> 是的呀 我下载的10.1.2的 解压上传到WordPress的plugins文件夹下面 启用就报错上面那个 在容器里执行composer install 才可以在WordPress的插件中启用

我先尝试一下能否在本地复现。

**Comment by LuRenJiasWorld** [comment]
我这边没有复现出你所描述的问题，环境也是容器，可以成功安装。

![image](https://user-images.githubusercontent.com/29622423/82463325-46912500-9aef-11ea-8136-bdce73851baa.png)

我复述一下我的操作过程，你看看是否和你的操作有出入：

1. 在这里下载zip包：

![image](https://user-images.githubusercontent.com/29622423/82463441-6d4f5b80-9aef-11ea-8780-2f9c22f0f6b5.png)

2. 将下载后的zip包在这里上传到服务器（不是拷贝到plugins目录后解压）：

![image](https://user-images.githubusercontent.com/29622423/82463581-97a11900-9aef-11ea-9865-cfffe58d1a9c.png)

3. 稍等片刻（本插件文件较多，时长取决于你的服务器配置），点击启动插件：

![image](https://user-images.githubusercontent.com/29622423/82463793-d8009700-9aef-11ea-997e-712f21c71dfb.png)

4. 在设置->WP Editor.md中检查本插件是否成功启用：

![image](https://user-images.githubusercontent.com/29622423/82463865-f070b180-9aef-11ea-9d7b-df136397a7b0.png)

**Comment by LuRenJiasWorld** [comment]
> 用的是阿里的ECS 估计连接太慢了

这个问题我会在将来的版本予以考虑，加入国内镜像源的支持。的确无论是下载zip包还是从WordPress商店，如果没有科学上网的环境都是很慢的。安装会很困难，版本更新也会很困难。

**Comment by sunerpy** [comment]
哎  我刚接触不久  不太懂嘿嘿   不过我在WordPress里面上传限制是2MB  我网上找了找修改限制的方法好像无效。。。所以就用的sftp解压传到目录里了。。。

**Comment by LuRenJiasWorld** [comment]
> 哎 我刚接触不久 不太懂嘿嘿 不过我在WordPress里面上传限制是2MB 我网上找了找修改限制的方法好像无效。。。所以就用的sftp解压传到目录里了。。。

2MB限制应该来源于你所使用的Web服务器或PHP，建议你都检查一下。

如果是解压传上去，记得修改文件夹名称为`wp-editormd`，并确保文件夹下面没有另一个子文件夹，目录结构如下所示：
```
plugins
- wp-editormd
- - assets
- - languages
- - src
- - vendor
- - LICENSE
- - readme.txt
- - wp-editormd.php
- - uninstall.php
```

**Comment by sunerpy** [comment]
嗯嗯  谢啦  我明天有空再试试去      睡觉了 晚安~~

**Comment by LuRenJiasWorld** [comment]
好，有什么其他问题欢迎继续反馈。我也去休息了。

**Comment by sunerpy** [comment]
Hello  我又来啦、、、  修改了上传大小限制后可以通过上传启用插件了~~我还有个问题哈   编辑器的预览效果和实际效果有点差别呀  这个好改嘛  如下图
这是预览编辑界面
![image](https://user-images.githubusercontent.com/30691040/82626412-56f1ee80-9c1a-11ea-938d-fccb54ea81c6.png)


实际界面是这样的

![image](https://user-images.githubusercontent.com/30691040/82626399-4c375980-9c1a-11ea-823e-5229fac297cb.png)

多出了一行代码空格和黑色条~

因为刚接触不久所以不太懂   我也慢慢去查资料~

**Comment by sunerpy** [comment]
我试了试觉得应该是WordPress自己的问题。。。只是还没定位到

**Comment by LuRenJiasWorld** [comment]
这个可能是因为你的主题自带代码高亮功能，和本插件的代码高亮冲突了，你可以先尝试一下换一个主题，看看问题是否依旧存在。

**Comment by sunerpy** [comment]
搞定啦！就是主题的事情  ~~

**Comment by LuRenJiasWorld** [comment]
好的，如果你对JS/CSS有一定的了解，可以修改主题，禁用主题自带的代码高亮功能。如果不太了解的话，换个主题是最简单的方法: )
