### ISSUE TITLE
插件资源包过时，使用默认的静态资源地址也是一样

### ISSUE THREAD

**Issue by Clloz** [LuRenJiasWorld/WP-Editor.md#463]
好像是刚出现没多久的，我换成默认的静态资源地址还是报错。
<img width="1414" alt="Screen Shot 2020-05-24 at 19 20 47" src="https://user-images.githubusercontent.com/17775199/82752935-4301e480-9df4-11ea-80ef-e414539e7825.png">

**Comment by LuRenJiasWorld** [comment]
你好，请问可以上传一下高级设置中的调试信息吗？

**Comment by potoo0** [comment]
我也有同样问题，我的调试信息:
```
系统环境	Linux
运行环境	nginx/1.10.3
PHP版本	7.0.33-0ubuntu0.16.04.14
PHP运行环境	fpm-fcgi
浏览器信息	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
WordPress版本	5.4.1
插件版本	10.1.2
jQuery版本	1.12.4
当前用户权限	administrator
WordPress地址	https://www.brothereye.cn
站点地址	https://www.brothereye.cn
常规设置	task_list => on
imagepaste => on
imagepaste_sm => off
live_preview => on
sync_scrolling => off
html_decode => on
support_front => off
support_reply => off
open_in_new_tab => off
编辑器设置	theme_style => default
code_style => solarized
editor_addres => https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.1.2
语法高亮设置	highlight_mode_auto => off
line_numbers => off
show_language => off
copy_clipboard => off
highlight_library_style => customize
customize_my_style => /scripts/prism-ghcolors.min.css
Emoji表情设置	support_emoji => off
文章目录设置	support_toc => on
科学公式设置	support_latex => katex
绘图设置	support_mermaid => off
mermaid_config => { "theme": "dark", "logLevel": 5, "arrowMarkerAbsolute": false, "startOnLoad": true, "flowchart": { "htmlLabels": true, "curve": "linear" }, "sequence": { "diagramMarginX": 50, "diagramMarginY": 10, "actorMargin": 50, "width": 150, "height": 65, "boxMargin": 10, "boxTextMargin": 5, "noteMargin": 10, "messageMargin": 35, "mirrorActors": true, "bottomMarginAdj": 1, "useMaxWidth": true }, "gantt": { "titleTopMargin": 25, "barHeight": 20, "barGap": 4, "topPadding": 50, "leftPadding": 75, "gridLineStartPadding": 35, "fontSize": 11, "fontFamily": "\"Open-Sans\", \"sans-serif\"", "numberSectionStyles": 4, "axisFormat": "%Y-%m-%d" }, "class": {}, "git": {} }
高级设置	jquery_compatible => on
hide_ads => on
启用插件列表	0 => google-sitemap-generator/sitemap.php
2 => really-simple-ssl/rlrsssl-really-simple-ssl.php
3 => w3-total-cache/w3-total-cache.php
4 => wordfence/wordfence.php
5 => wp-cerber/wp-cerber.php
6 => wp-editormd/wp-editormd.php
7 => wp-mail-smtp/wp_mail_smtp.php
8 => wpvivid-backuprestore/wpvivid-backuprestore.php
```

**Comment by LuRenJiasWorld** [comment]
@potoo0

你好，根据你所贴的调试信息，可以从`https://www.brothereye.cn/wp-content/plugins/wp-editormd/assets/version.json`地址看到你服务器中安装的插件对应资源版本的确是10.1.2，而CDN上的资源`https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.1.2/assets/version.json`同样没有问题，因此出现报错可能是因为服务器本身无法请求到这个资源导致的。

请问你能获取到服务器的访问权限（指Shell）吗？可以的话麻烦在服务器上测试一下以下两个命令是否能输出对应的文件：

```bash
curl -i https://www.brothereye.cn/wp-content/plugins/wp-editormd/assets/version.json
curi -i https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.1.2/assets/version.json
```

附上一份正常情况下的返回结果：

![image](https://user-images.githubusercontent.com/29622423/83400090-dced1100-a434-11ea-8cf8-81d61ecd7dcf.png)

![image](https://user-images.githubusercontent.com/29622423/83400103-e2e2f200-a434-11ea-8e35-b924c35bb39c.png)

**Comment by potoo0** [comment]
@LuRenJiasWorld 

你好，我在服务器上测试了下，发现提示该 cdn 的 ssl 证书过期，详细见下图:
![image](https://user-images.githubusercontent.com/34411681/83407246-e41b1b80-a442-11ea-9cad-d65fed1cb611.png)

**Comment by LuRenJiasWorld** [comment]
@potoo0 这个可能就是问题所在了。应该是Ubuntu某些版本默认开启了证书校验，但系统内置的根证书版本已经过时，无法识别这些站点上新的根证书是否可信（看调试信息你使用的还是Ubuntu 16.04），解决方法之一是将你自己站点或jsdelivr.net的证书加入信任目录。

https://blog.csdn.net/xinghun_4/article/details/50500331 这里有一篇文章可供你参考，将这些域名对应的根证书加入系统信任目录即可。

此外，我会在将来的版本考虑关闭证书校验，以避免出现此类情况。

**Comment by potoo0** [comment]
好的，明白了，谢谢啦。另外我使用的确实是 ubuntu16.04，(●—●)。


 
---原始邮件---
发件人: "Benjamin Chris"<notifications@github.com&gt;
发送时间: 2020年6月1日 21:03:53
收件人: "LuRenJiasWorld/WP-Editor.md"<WP-Editor.md@noreply.github.com&gt;;
抄送: "potoo"<1415615232@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [LuRenJiasWorld/WP-Editor.md] 插件资源包过时，使用默认的静态资源地址也是一样 (#463)




 
@potoo0 这个可能就是问题所在了。应该是Ubuntu某些版本默认开启了证书校验，但系统内置的根证书版本已经过时，无法识别这些站点上新的根证书是否可信（看调试信息你使用的还是Ubuntu 16.04），解决方法之一是将你自己站点或jsdelivr.net的证书加入信任目录。
 
https://blog.csdn.net/xinghun_4/article/details/50500331 这里有一篇文章可供你参考，将这些域名对应的根证书加入系统信任链即可。
 
此外，我会在将来的版本考虑关闭证书校验，以避免出现此类情况。

**Comment by LuRenJiasWorld** [comment]
@potoo0 好的，如果有什么其他问题欢迎继续反馈~

@Clloz 你也可以按照上面的讨论检查一下你的服务器是否也存在同样问题。

**Comment by potoo0** [comment]
谢谢 LuRenJiasWorld，参照上面的方法问题已经解决：保存 openssl 获取到的第二部分 CERTIFICATE 到 pem 文件中，verify 通过后，移动到 `/etc/ssl/certs` 下。

> 但是我发现在 `/etc/ssl/certs` 下删除刚放入的这个证书后，却依然可以正常访问，搞不明白了。

**Comment by LuRenJiasWorld** [comment]
> 谢谢 LuRenJiasWorld，参照上面的方法问题已经解决：保存 openssl 获取到的第二部分 CERTIFICATE 到 pem 文件中，verify 通过后，移动到 `/etc/ssl/certs` 下。
> 
> > 但是我发现在 `/etc/ssl/certs` 下删除刚放入的这个证书后，却依然可以正常访问，搞不明白了。

应该是因为对应的根证书之前就存在，只是过期了，和线上更新后的根证书不一样才提示错误。OpenSSL不会校验不存在的证书，所以说删除之后也能恢复正常。

**Comment by Clloz** [comment]
不好意思，之前一直没回复。我是`yum update`了一下，好像导致系统的证书出了什么问题，所有`https`请求都报错： `problem with the ssl ca cert (path? access rights?)`，`Google`上都是说重装`openssl ca-certificates`，试了没用，阿里云的客服也没解决，尝试了 `Google` 上的各种方法都没用，最后我只好回滚了一下快照，到最后也没找到问题在哪。

**Comment by LuRenJiasWorld** [comment]
> 不好意思，之前一直没回复。我是`yum update`了一下，好像导致系统的证书出了什么问题，所有`https`请求都报错： `problem with the ssl ca cert (path? access rights?)`，`Google`上都是说重装`openssl ca-certificates`，试了没用，阿里云的客服也没解决，尝试了 `Google` 上的各种方法都没用，最后我只好回滚了一下快照，到最后也没找到问题在哪。

这个我也没遇到过，不太清楚，不过解决了就好。
