### ISSUE TITLE
No Code Formatting

### ISSUE THREAD

**Issue by kayvanaarssen** [LuRenJiasWorld/WP-Editor.md#464]
Hi

I don't know if its because of a latest update of WordPress or something else but we now get this: 

![image](https://user-images.githubusercontent.com/672841/83030093-b8a7c380-a033-11ea-8a70-575f6f6446ee.png)

When we write a code block.
It should look like this:

![image](https://user-images.githubusercontent.com/672841/83030282-cbba9380-a033-11ea-94b9-8104d5322157.png)

Backend is looking fine:

![image](https://user-images.githubusercontent.com/672841/83030468-d9701900-a033-11ea-90a2-28d736dc50f6.png)

Maybe you will have a fix for this?

**Comment by LuRenJiasWorld** [comment]
Hello, I haven't received some other issues like this yet, so it may be something incompatible with your theme or other plugins.

Could you give me some example link to reproduce it ? In addition, please upload your debugging info at the Advanced Settings of this plugin for me to know more about your environment and configurations.
