### ISSUE TITLE
markdown公式不能显示

### ISSUE THREAD

**Issue by Tyux** [LuRenJiasWorld/WP-Editor.md#465]
我markdown这样写的：
$$W=(0.001 \cdot randn( , )) \sqrt{n}$$

文章显示出来是文本形式：
W=(0.001 \cdot randn( , )) \sqrt{n}]

我的文章是从mweb导入的
顺便问一下，我所有mweb导入的文章都是在wordpress文章编辑器里都是html格式的，这样正常吗

**Comment by LuRenJiasWorld** [comment]
> 我markdown这样写的：
> $$W=(0.001 .* randn( , ))./sqrt(n)$$
> 
> 文章显示出来是文本形式：
> [W=(0.001 .* randn( , ))./sqrt(n)]

可以提供一个示例页面的地址吗？我看看具体发生了什么。

> 我的文章是从mxweb导入的
> 顺便问一下，我所有mxweb导入的文章都是在wordpress文章编辑器里都是html格式的，这样正常吗

不清楚mxweb是什么，不过都是html格式属于正常情况，目前尚未支持HTML转换到Markdown的功能，如果之前没有使用本编辑器编辑的文章都会以HTML方式显示。你可以把这些旧文章使用Markdown重新排版，也可以等待后续版本支持这一功能。

**Comment by Tyux** [comment]
http://112.126.61.162/wp-blog/index.php/2020/05/30/shen-du-xue-xi-shi-jue-shi-jian/

**Comment by LuRenJiasWorld** [comment]
看样子LaTeX解析器并未将页面中的LaTeX语句转译为相关的HTML标签。

你可以换用如下的语句（任选其一）包裹LaTeX，再试试看问题是否复现：

```markdown
$ [W=(0.001 .* randn( , ))./sqrt(n)] $
```

![image](https://user-images.githubusercontent.com/29622423/83343070-aa55f200-a328-11ea-9aff-0410c50fdf95.png)

此外，如果单行LaTeX语句上下未空行，也会出现类似的问题，如下所示：

![image](https://user-images.githubusercontent.com/29622423/83343098-c8bbed80-a328-11ea-8c73-f16f55cadebb.png)

![image](https://user-images.githubusercontent.com/29622423/83343100-cf4a6500-a328-11ea-98f2-081450179a2d.png)

最后需要说明的一点是，如果你是从其他Markdown编辑器迁移到本编辑器，需要手动更新一下每篇文章，流程是在每篇文章的编辑页面点击右侧面板的更新按钮，触发手动更新（这部分会在接下来的版本自动化，目前需要手动处理）

**Comment by Tyux** [comment]
额，都试了还是不行。
但是直接在wordpress的WP-Editor编辑器里输入是可以正常显示的
在我的MWeb编辑器里也是可以正常显示
就是外部导入以后就显示不了了，可能是转换成html的时候有问题吧

**Comment by LuRenJiasWorld** [comment]
嗯，这个的确没有办法，因为本编辑器的公式渲染功能需要指定结构的HTML，直接从外部导入大概率是不能生效的。

如果需要使用本插件，还是建议导入之后编辑文本，按照上文提到的方法手动修改下已有的文章。
