### ISSUE TITLE
出现Fatal error，似乎来自wp-editormd

### ISSUE THREAD

**Issue by FrazierLei** [LuRenJiasWorld/WP-Editor.md#466]
Notice: 自4.5.0版本起，已不建议使用add_utility_page，请换用add_menu_page()。 in /var/www/html/wp-includes/functions.php on line 4648

Fatal error: Uncaught Error: Call to undefined function EditormdUtils\curl_init() in /var/www/html/wp-content/plugins/wp-editormd/src/Utils/Settings.php:116 Stack trace: #0 /var/www/html/wp-content/plugins/wp-editormd/src/Utils/Settings.php(130): EditormdUtils\Settings->file_get_content('https://cdn.jsd...') #1 /var/www/html/wp-content/plugins/wp-editormd/src/Utils/Settings.php(73): EditormdUtils\Settings->get_settings_sections() #2 /var/www/html/wp-includes/class-wp-hook.php(288): EditormdUtils\Settings->admin_init('') #3 /var/www/html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array) #4 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #5 /var/www/html/wp-admin/admin.php(170): do_action('admin_init') #6 /var/www/html/wp-admin/index.php(10): require_once('/var/www/html/w...') #7 {main} thrown in /var/www/html/wp-content/plugins/wp-editormd/src/Utils/Settings.php on line 116
您的站点遇到了致命错误，请查看您的站点的管理电子邮箱来获得指引。

了解更多在WordPress中调试的信息。

**Comment by LuRenJiasWorld** [comment]
你好，这似乎是因为你的PHP环境未安装cURL扩展导致的。请根据你当前的服务器环境，尝试安装相关扩展后再看看这个问题是否能复现。

**Comment by FrazierLei** [comment]
看来就是这个问题
sudo apt-get install php-curl
解决了，非常感谢！！！
能睡个好觉了，多谢！
