### ISSUE TITLE
可不可以增加下文本标记这个属性呀

### ISSUE THREAD

**Issue by sunerpy** [LuRenJiasWorld/WP-Editor.md#467]
就是这样的文本标记：  ==颜色标记==

跟typora渲染的一样
![image](https://user-images.githubusercontent.com/30691040/83335890-67712b80-a2e2-11ea-8d4a-062ddfb19eb5.png)

**Comment by LuRenJiasWorld** [comment]
你好，你指的是文本高亮功能吗？

**Comment by sunerpy** [comment]
算是吧应该，我PC使用的typora和joplin都支持这种渲染方式~
wp-editor插件的代码高亮我用着支持挺好的，就是不支持这种对普通文本的高亮方式，这个不需要在代码块里进行渲染，普通文本就可以

**Comment by LuRenJiasWorld** [comment]
明白了，我先参考一下Typora的具体实现，会考虑在接下来的版本加入此功能。

**Comment by sunerpy** [comment]
谢谢~~加油
&nbsp;





&nbsp;

**Comment by LuRenJiasWorld** [comment]
现在你可以使用这样的方法临时替代：

```html
<span style="background-color: #fffd38;">文本标记</span>
```

![image](https://user-images.githubusercontent.com/29622423/83343011-f8b6c100-a327-11ea-83b9-12e590867765.png)

**Comment by sunerpy** [comment]
OK~~感谢感谢~

**Comment by LuRenJiasWorld** [comment]
你好，目前我基本实现了相关功能，并完成了测试，预计会在本月底的10.2.0版本发布。

需要注意的是，因为目前浏览器兼容性的限制，无法对`===测试===`和`==测试==`进行精准区分，错误的语法依旧会被匹配，可以参考 https://github.com/LuRenJiasWorld/WP-Editor.md/commit/b12192282cd5d56020a0f746fde50744871bf871 的相关注释。

但我参考了一下Typora的实现，发现它有着同样的『BUG』，因此在主流浏览器支持更复杂的正则表达式规则之前，只能做到这样。

![image](https://user-images.githubusercontent.com/29622423/83513619-b1d1f280-a504-11ea-80e1-7a931f9a7167.png)
> 10.2.0版本WP Editor.md后台编辑器行内高亮样式

![image](https://user-images.githubusercontent.com/29622423/83513639-bb5b5a80-a504-11ea-854f-88bf8a766907.png)
> 10.2.0版本WP Editor.md前台预览行内高亮样式

![image](https://user-images.githubusercontent.com/29622423/83513926-3e7cb080-a505-11ea-85b0-3f481a7322e8.png)
> Typora所拥有的『BUG』，不过一般不会引起歧义（大多数情况下是用户不熟悉Markdown语法导致）

**Comment by sunerpy** [comment]
太棒了，这么快~~等待下个版本~

**Comment by LuRenJiasWorld** [comment]
你好，该功能已于最新发布的 10.2.0 版本实现，再次感谢反馈，祝使用愉快。如果以后有其他问题也欢迎继续反馈~

Release：https://github.com/LuRenJiasWorld/WP-Editor.md/releases/tag/v10.2.0

**Comment by 361way** [comment]
您好，请问如何关闭这个功能啊？因为很多编程语言里有 a==b，a!=b这种写法，遇到这种情况就会出现无法正常显示的问题。a==b变成了a  b(加黄底)
