### ISSUE TITLE
升级到10.1.2版本后前端代码展示最后多了一个空行

### ISSUE THREAD

**Issue by chenqin231** [LuRenJiasWorld/WP-Editor.md#468]
如图，后端编辑器预览展示正常：
![image](https://user-images.githubusercontent.com/7258271/83705063-78a19b80-a646-11ea-8e9b-85bb2a2b286c.png)
前端博客展示时多了一个换行

![image](https://user-images.githubusercontent.com/7258271/83705103-8fe08900-a646-11ea-8a0d-ae3f7358155c.png)

主题都是用的default

**Comment by LuRenJiasWorld** [comment]
这种问题一般是前台主题和代码高亮插件在CSS方面产生冲突导致的。

请问可以提供一个示例页面吗？我看看是什么情况，尽量给你一些主题上修改的建议。

**Comment by chenqin231** [comment]
这是升级编辑器后的文章情况：
http://www.guoziweb.com/html/lanmp/linux/2020/06/03/2678.html

非常感谢

**Comment by LuRenJiasWorld** [comment]
问题出在主题与本插件的CSS样式产生冲突，由于很多主题自带了基础的代码高亮功能，这种冲突极容易出现。

你可以先试试看注释掉主题中`style.css`关于`.single-content code`的部分，或在WordPress自定义功能的自定义CSS选项加入如下CSS代码：

```css
.single-content code {
    margin: 0 !important;
    padding: 0 !important;
}
```

![image](https://user-images.githubusercontent.com/29622423/83709996-4ac25400-a652-11ea-9ac4-bc80fbeb5431.png)

这样问题应该能解决。

**Comment by chenqin231** [comment]
问题解决了，非常棒的体验，作者水平高！

**Comment by LuRenJiasWorld** [comment]
解决了就好，感谢认可。
