### ISSUE TITLE
代码高亮文章页渲染问题

### ISSUE THREAD

**Issue by teiny** [LuRenJiasWorld/WP-Editor.md#469]
代码高亮在编辑预览的时候没有问题，但是在文章页面渲染的时候
1. 行内代码不能渲染样式，
2. 代码块不能根据对应的语言高亮显示，prism-bash.min.js 加载报404
版本：10.1.2
[https://www.jutil.net/archives/13](https://www.jutil.net/archives/13)

![temp-orig](https://user-images.githubusercontent.com/58910855/83937379-8ef25780-a7fe-11ea-8400-4a63efe5b0fa.png)
![temp-to](https://user-images.githubusercontent.com/58910855/83937381-931e7500-a7fe-11ea-9cad-881956f2e048.png)

**Comment by teiny** [comment]
发现问题2是缓存插件的问题，但问题1还是存在

**Comment by LuRenJiasWorld** [comment]
1. 请先检查一下和主题的兼容性。部分主题没有设定行内高亮的样式，你可以通过手动添加CSS的方式添加一下、
2. 目前已知本插件和AutoOptimize不兼容，原因正在排查中，短期内只能更换一个其他的优化/缓存插件。

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/83937518-cf060a00-a7ff-11ea-99dc-14ff9e74b78c.png)

我稍微写了几行CSS，如图所示，你可以大致参考一下。

**Comment by teiny** [comment]
谢谢大佬

**Comment by LuRenJiasWorld** [comment]
好的: ) 有其他问题欢迎继续反馈
