### ISSUE TITLE
前端不能正常解析Markdown语法

### ISSUE THREAD

**Issue by emperinter** [LuRenJiasWorld/WP-Editor.md#472]
后台能够正确识别Markdown语法，但前端就直接显示出来了。目前就知道> 和#  出现过问题。- 会错位，具体可以看我网站[https://www.emperinter.info/2020/06/16/now-you-see-me-2/](https://www.emperinter.info/2020/06/16/now-you-see-me-2/)和
[https://www.emperinter.info/2020/06/09/configure-flutter/](https://www.emperinter.info/2020/06
/09/configure-flutter/)

# **#**和**-**
![图片](https://user-images.githubusercontent.com/20177836/84733063-d2ec1600-afcf-11ea-8246-4d5a83b5178d.png)

# >
![图片](https://user-images.githubusercontent.com/20177836/84733210-324a2600-afd0-11ea-95f9-52b28e689c3a.png)

**Comment by LuRenJiasWorld** [comment]
请问你有检查过与其他插件或当前主题的兼容性吗？这种情况很少见，但一般都是兼容性问题引起的。

**Comment by emperinter** [comment]
额，这东西咋检查？一个一个的禁用然后查看？不过插件这东西除非必要基本都是能不用的就不用，禁用后替代产品也不好找呀！以下是我使用的插件（有一个也是markdwon插件，那一个是代码块有问题就禁用许久了！）
![图片](https://user-images.githubusercontent.com/20177836/84851219-43586d00-b08c-11ea-8dc3-6365ae9270c1.png)

**Comment by LuRenJiasWorld** [comment]
看你提供的链接，问题出在保存文章后的渲染过程出现问题，WordPress下各个流程（即钩子）都是允许任意插件/主题注入函数的，不排除有其他插件在保存过程中执行了其他操作，因此会产生冲突问题。

这里我推荐最小系统法排查兼容性问题，即禁用所有插件后逐一开启，直到定位到存在问题的插件。需要注意的是，因为问题出在保存的环节，开启插件后需要在文章编辑的页面触发一次保存操作。

此外，根据之前采集到的用户反馈，这种问题最有可能出现在一些优化插件上，你可以优先考虑与优化插件的兼容性，使用这样的思路看看能否找到是哪一个插件引起的问题。

如果能找到的话，目前建议先关闭掉，我会在未来的版本尽量尝试优化和特定插件的兼容性。

**Comment by LuRenJiasWorld** [comment]
顺便问下，这个『简易目录』是否必需？你也可以着重检查一下这个插件，因为本插件有提供toc功能，而这个『简易目录』插件应该也是在保存的时候执行其行为，不排除存在兼容性问题。

**Comment by emperinter** [comment]
**简易目录**禁用后问题还是存在，其它插件目前都不想折腾了，毕竟选和用都耗费了很长时间；如果你后续想优化的话建议你可以安装一下这些插件然后看看问题所在，个人而言就有点不想弄了！我看有一个什么导出调试信息的图片，我弄出来了，你可以看看！
![图片](https://user-images.githubusercontent.com/20177836/84996840-6106fe80-b180-11ea-8533-3692521b8631.png)

**Comment by LuRenJiasWorld** [comment]
你好，我这边使用了相同的配置，也安装了列表中的插件，还是没能复现出你所描述的问题。

之前帮助过其他用户解决此类问题，一般是通过检查插件兼容性来完成的，你只要先全部关闭，然后逐一打开，不会耽搁太久时间，最多五分钟就能定位问题。

你这边定位到有问题的插件之后我才能清楚问题出在哪，因为无法完全还原你这边的环境，仅靠我一个人复现是无法解决的。你如果有空的话，还是按照我上面说的试试看，否则我这边确实是帮不到你，抱歉哈。

**Comment by emperinter** [comment]
# 发现
> 用了这么久，发现如果编辑时像图中**红1**标注所示的话容易出现我之前说过的问题（不一定出现），但像如果**空一行（红圈**则基本没有出现过类似问题（印象中）;目前自己在编辑一篇文章后先预览如果发现排版有问题的话去**空一行**就基本没有问题了！

![image](https://user-images.githubusercontent.com/20177836/89375939-5cdb7400-d721-11ea-9195-d4f3cd3b9ad6.png)

# 示例
> 以我发现的一篇排版有问题作为示例在以往有问题的地方去**空一行**，以及修改后的情况如下：

## 修改前（13：48）
![image](https://user-images.githubusercontent.com/20177836/89376460-5b5e7b80-d722-11ea-84e2-d515d90d3a59.png)

## 修改后（13：50、13：52）
![image](https://user-images.githubusercontent.com/20177836/89376597-b2fce700-d722-11ea-91dc-a1b3042e27ea.png)
![image](https://user-images.githubusercontent.com/20177836/89376731-07a06200-d723-11ea-8f3f-dd1b44977610.png)

- [flutter配置](https://www.emperinter.info/2020/06/09/configure-flutter/)

**Comment by LuRenJiasWorld** [comment]
是的，其实标准的Markdown语法就是要求语法块前后各空一行的，但很多用户可能不太清楚这个情况，所以说在使用标准语法进行解析时候出现各种『问题』。

后续有时间我会尝试对大家的使用习惯进行兼容，尽量避免出现此类疑问。
