### ISSUE TITLE
启用插件之后文章目录不显示

### ISSUE THREAD

**Issue by r8ter** [LuRenJiasWorld/WP-Editor.md#476]
启用插件，在文章发布之后，正文浏览处，左侧栏的目录为空，不显示，关闭插件之后恢复正常。
文章已经发布，在下面演示过程中没有改动过文章内容。
启用插件之后：
![image](https://user-images.githubusercontent.com/48148334/87503633-4e0c1f00-c697-11ea-990b-1577358984bc.png)
关闭插件之后：
![image](https://user-images.githubusercontent.com/48148334/87503732-8875bc00-c697-11ea-8131-8a13475eafe7.png)
当前启用的插件就这一个，包括安装的插件也就这一个和wordpress自带的（你好多莉）插件，已关闭，所以排除其他插件的影响。请问这个怎么解决啊。
![image](https://user-images.githubusercontent.com/48148334/87503875-e1ddeb00-c697-11ea-820c-c6f7268fd07a.png)

**Comment by r8ter** [comment]
刚看了下，应该是主题不兼容的原因（主题Argon）。

**Comment by LuRenJiasWorld** [comment]
你好，https://github.com/LuRenJiasWorld/WP-Editor.md/issues/446 这个Issue提到了类似的问题，也是Argon主题。

很抱歉目前尚未针对Ajax加载的环境进行适配，请问下在启用插件（左侧目录为空）的时候在F12控制台能不能看到有报错呢？

可以的话提供一个能复现问题的链接最好，我看看这个问题是什么情况引起的，尽量给予修复或指导你如何解决此问题。

**Comment by r8ter** [comment]
有报错的，如图：
![image](https://user-images.githubusercontent.com/48148334/87560858-796e2880-c6ee-11ea-9cc4-050ca924d4c4.png)

**Comment by LuRenJiasWorld** [comment]
大概明白了。请问你有尝试过在WP Editor.md的高级设置中打开兼容模式吗？

**Comment by r8ter** [comment]
多谢，打开兼容模式解决了👍

**Comment by LuRenJiasWorld** [comment]
> 多谢，打开兼容模式解决了👍

好的，解决了就好。之后我会在插件中加入FAQ部分，避免其他使用本插件的用户遇到类似问题不知道如何解决。感谢反馈~
