### ISSUE TITLE
想问下这个md editor的工作原理是怎么样的呢？

### ISSUE THREAD

**Issue by ChrisZou** [LuRenJiasWorld/WP-Editor.md#477]
是会把输入的md内容转化成html，然后存在DB里面？然后下次编辑的时候再从html转化成md？
还是说md内容会另外存在一个地方，下次编辑的时候直接从那个地方把md内容读出来呢？

**Comment by LuRenJiasWorld** [comment]
你好，原理是将Markdown原文存储在`wp_posts`表的`post_content_filtered`字段内，每次在编辑页面点击保存/发布/更新时解析为对应的HTML到`post_content`字段，然后前台主题会从这个字段拿到对应的HTML。

基本的Markdown排版是直接在保存时期完成的，但LaTeX、Mermaid、代码高亮等扩展功能则是在保存时期进行标记，然后前台页面显示的时候根据标记识别类型，动态渲染。

顺便问下，了解原理是有什么特殊需求吗？

**Comment by ChrisZou** [comment]
是的，我有一个原来用jekyll做的博客，想迁移到wordpress，但是希望迁移过去之后，依然保留可以使用md编辑的能力。所以想了解下原理。
所以，像我这种需求，需要保存一份md源内容到post_content_filtered字段，然后再自己转化成html，保存一份到post_content字段是吗？

**Comment by LuRenJiasWorld** [comment]
> 是的，我有一个原来用jekyll做的博客，想迁移到wordpress，但是希望迁移过去之后，依然保留可以使用md编辑的能力。所以想了解下原理。
> 所以，像我这种需求，需要保存一份md源内容到post_content_filtered字段，然后再自己转化成html，保存一份到post_content字段是吗？

如果是迁移到WordPress的话，最好是先启用本插件，然后逐篇复制过来，一般情况下是没必要操作数据库的。

后续可能会加入Markdown批量导入导出的功能，但这个排期比较靠后，短时间内估计无法满足你的需求。

你这边文章数量多吗？如果数量较多的话可以试试看脚本化解决，即写一个简单的插件（其实就是一个PHP文件），插件里使用WordPress的`wp_insert_post()`函数插入文章内容，此时在安装了WP Editor.md并正确配置编辑器的情况下，应该会自动触发本编辑器的Markdown转换。

以上所述的手动/自动方法应该都是可行的，主要看你的文章规模，你可以自行决定使用哪一种，迁移过程中有问题的话欢迎继续反馈: )

**Comment by LuRenJiasWorld** [comment]
补充下，如果用`wp_insert_post()`函数插入数据，需要插入到`post_content`字段，这是为了保证和WordPress的兼容性（编辑文章的页面默认提交数据到这个字段，本插件将其取出，转换为HTML，再把md原文转储到`post_content_filtered`字段）

**Comment by ChrisZou** [comment]
是的，文章比较多，所以不想一篇一篇复制发布，同时也想保留当时的发布时间。之前的打算是写ruby个脚本，把信息（标题、内人、发布时间等）从文件解析出来，再使用一个library（gem）链接wordpress的db，把内容写到wp_posts table里面。
根据你的提示，我才知道还有wp_insert_post() 这种接口，谢谢！也感谢你写的这个插件！😄

**Comment by LuRenJiasWorld** [comment]
好的，迁移过程中如果遇到其他问题也欢迎继续反馈: )，如果是与本插件相关的内容我都会尽量给予帮助的。
