### ISSUE TITLE
点击更新后 编辑器内的MD文本变成HTML风格

### ISSUE THREAD

**Issue by sszxc** [LuRenJiasWorld/WP-Editor.md#478]
正常编辑、预览，点击更新文章后，编辑器内的MD文本就变成HTML风格，例如 “## 标题” → “&lt;h2&gt;标题&lt;/h2&gt;”，不太方便二次编辑。前段时间使用没有这个问题，今天印象中更新了几个插件（Featured Image from URL、Jetpack），就出现了这样的现象。

请问这是新功能还是bug？

**Comment by LuRenJiasWorld** [comment]
这种情况应该是一个BUG。你可以先尝试关闭所有插件，然后打开一个插件保存一次，通过这种方法来确定是哪个插件引起的。

**Comment by sszxc** [comment]
刚才完全卸载了之前安装的 Jetpack (8.7.1)，包括各种残留文件，问题解决了。不太确定是不是这个插件导致的冲突。因为这次刚好想卸载这个 Jetpack，所以我个人没其他问题了，如果其他用户遇到，您关注一下。

**Comment by LuRenJiasWorld** [comment]
> 刚才完全卸载了之前安装的 Jetpack (8.7.1)，包括各种残留文件，问题解决了。不太确定是不是这个插件导致的冲突。因为这次刚好想卸载这个 Jetpack，所以我个人没其他问题了，如果其他用户遇到，您关注一下。

好的，一般类似问题都可以通过排查插件兼容性解决。如果今后遇到什么常用插件与本插件产生冲突也欢迎反馈。
