### ISSUE TITLE
似乎不兼容pjax

### ISSUE THREAD

**Issue by xiaobaichengxuyuan** [LuRenJiasWorld/WP-Editor.md#479]
在pjax下公式不解析，只有再次刷新文章页才可以。

**Comment by LuRenJiasWorld** [comment]
> pjax

你好，目前本插件尚未支持pjax，只支持常规的页面加载方式，使用pjax的主题也会有同样问题，目前无解。

后续版本可以考虑加入此功能，抱歉带来不便，或者你也可以使用其他第三方LaTeX插件（如SimpleMathjax）替代本插件的LaTeX功能。
