### ISSUE TITLE
不支持wordpress相册地址自定义的问题，图片地址会一直是链接到附件地址！

### ISSUE THREAD

**Issue by jerfo0** [LuRenJiasWorld/WP-Editor.md#480]
通过代码对比，好像是不能解析英文状态下的""(双引号)这个字符。

但是调用相册的时候是有这个字符的。比如：[gallery link="file" size="large" ids="4115,4098,4096,4099,4100,4101,4102,4104,4114"]

停用插件编辑的相册就不会出现这个问题！

**Comment by LuRenJiasWorld** [comment]
你好，目前本编辑器尚未支持短代码功能，因此短代码可能会出现意料之外的问题，这一问题的根源是保存时Markdown解析过程中短代码语法与Markdown链接语法有所冲突导致的，我会在接下来的版本予以解决。

请问可以在本插件的高级设置中导出一份调试信息吗？我看看你这边目前的配置，以便在本地重现这个问题。

**Comment by LuRenJiasWorld** [comment]
而且非常奇怪的是，我这边测试相册功能或其他短代码都没有发现问题，方便的话也请提供一份能重现故障的链接便于分析具体是什么原因导致的。

![image](https://user-images.githubusercontent.com/29622423/88875644-32d30f00-d254-11ea-9717-0aeddc3ffa5a.png)

![image](https://user-images.githubusercontent.com/29622423/88875655-3797c300-d254-11ea-96c8-65cb6a423e3d.png)

**Comment by jerfo0** [comment]
这个是用了插件的：https://www.it520.org/2020/07/30/yingyuceshi/

这个是没用插件的：https://www.it520.org/2020/07/29/ceshi/

插件我是更新到了最新版本，但是点击设置弹出新页面‘抱歉，您不能访问此页面’。不知道为什么！！

**Comment by LuRenJiasWorld** [comment]
> 这个是用了插件的：https://www.it520.org/2020/07/30/yingyuceshi/
> 
> 这个是没用插件的：https://www.it520.org/2020/07/29/ceshi/

好的，我现在看看。

> 插件我是更新到了最新版本，但是点击设置弹出新页面‘抱歉，您不能访问此页面’。不知道为什么！！

这个BUG按道理说应该在上个版本予以修复，你可以先尝试重新安装本插件，看看能否解决这个问题，重新安装插件不会导致数据丢失。最新版本是10.1.2。

**Comment by LuRenJiasWorld** [comment]
我看了一下你这边的站点，目前安装的本插件版本为10.1.0，最新的版本是10.1.2，你可以尝试更新到最新版，即可打开设置。

出现你所描述问题的根源可能并不是Markdown解析阶段出现故障，而是本插件与你所使用主题的兼容性不佳。你可以在本插件的高级设置中勾选兼容模式，然后看看这个问题是否能得以解决。

**Comment by jerfo0** [comment]
我刚刚在重装了！但是显示是插件不兼容目前的wordpress的版本！而且我按照失败了！

提示是这样：
安装失败： 504 Gateway Time-out 504 Gateway Time-out nginx/1.8.1      

是因为我升级了版本的原因吗！还是说因为我没有更新到最新版本的原因，后台看有一个最新版本的wordpress提示安装

**Comment by LuRenJiasWorld** [comment]
> 我刚刚在重装了！但是显示是插件不兼容目前的wordpress的版本！而且我按照失败了！
> 
> 提示是这样：
> 安装失败： 504 Gateway Time-out 504 Gateway Time-out nginx/1.8.1
> 
> 是因为我升级了版本的原因吗！还是说因为我没有更新到最新版本的原因，后台看有一个最新版本的wordpress提示安装

是的，你需要更新到最新的WordPress版本。如果你有服务器的操作权限，请登录服务器，删除`wp-content/plugins/wp-editormd`目录，更新WordPress到最新版本，然后再重新安装本插件。

顺便问一下你是使用什么方式安装的呢？

**Comment by jerfo0** [comment]
我是先删除了之前的按照！然后搜索这个插件的名称，在后台进行安装的！

**Comment by LuRenJiasWorld** [comment]
> 我是先删除了之前的按照！然后搜索这个插件的名称，在后台进行安装的！

这样操作应该是没问题的，看了下你的服务器在国内，可能在访问WordPress插件服务器过程中超时导致504报错。

你可以尝试在服务器端使用科学上网，也可以在本GitHub仓库的Release中下载最新版本的插件包再上传至WordPress，效果是一样的。

**Comment by jerfo0** [comment]
是版本的原因！  安装最新的版本后！这个问题解决了！ 谢谢

**Comment by LuRenJiasWorld** [comment]
> 是版本的原因！ 安装最新的版本后！这个问题解决了！ 谢谢

好的，以后有类似问题也欢迎反馈: )
