### ISSUE TITLE
flowchart显示不了

### ISSUE THREAD

**Issue by fastchaser** [LuRenJiasWorld/WP-Editor.md#481]
已在设置里开启绘图设置，绘图配置用的如下默认参数
{
    "theme": "dark",
    "logLevel": 5,
    "arrowMarkerAbsolute": false,
    "startOnLoad": true,
    "flowchart": {
        "htmlLabels": true,
        "curve": "linear"
    },
    "sequence": {
        "diagramMarginX": 50,
        "diagramMarginY": 10,
        "actorMargin": 50,
        "width": 150,
        "height": 65,
        "boxMargin": 10,
        "boxTextMargin": 5,
        "noteMargin": 10,
        "messageMargin": 35,
        "mirrorActors": true,
        "bottomMarginAdj": 1,
        "useMaxWidth": true
    },
    "gantt": {
        "titleTopMargin": 25,
        "barHeight": 20,
        "barGap": 4,
        "topPadding": 50,
        "leftPadding": 75,
        "gridLineStartPadding": 35,
        "fontSize": 11,
        "fontFamily": "\"Open-Sans\", \"sans-serif\"",
        "numberSectionStyles": 4,
        "axisFormat": "%Y-%m-%d"
    },
    "class": {},
    "git": {}
}

gantt，sequenceDiagram，graph图都可以显示，就是flowchart不行，高级设置中打开兼容模式也不行。
```mermaid
flowchart

st=>start: 开始
e=>end: 结束
op=>operation: 我的操作
cond=>condition: 确认？
st->op->cond
cond(yes)->e
cond(no)->op
```

**Comment by fastchaser** [comment]
另外https://mermaidjs.github.io/flowchart.html 帮助文档用梯子也登陆不上

**Comment by LuRenJiasWorld** [comment]
> ```
> flowchart
> 
> st=>start: 开始
> e=>end: 结束
> op=>operation: 我的操作
> cond=>condition: 确认？
> st->op->cond
> cond(yes)->e
> cond(no)->op
> ```

这个语法不是Mermaid的语法，而是[flowchart.js](https://github.com/adrai/flowchart.js/) 的语法，本编辑器只支持Mermaid绘图。

此外Mermaid的官方文档地址为[https://mermaid-js.github.io/mermaid/#/](https://mermaid-js.github.io/mermaid/#/)，可以在这里看到所有的帮助文档。

**Comment by fastchaser** [comment]
收到，感谢大佬。

**Comment by LuRenJiasWorld** [comment]
好的，有其他问题欢迎继续反馈: )
