### ISSUE TITLE
WP5.5出现编辑器无法加载的问题

### ISSUE THREAD

**Issue by CreeperKong** [LuRenJiasWorld/WP-Editor.md#483]
![wp-editormd-debug-info](https://user-images.githubusercontent.com/28486081/90859587-16da0d80-e3bb-11ea-89e4-c607530aa1cb.png)

![image](https://user-images.githubusercontent.com/28486081/90859675-38d39000-e3bb-11ea-951f-0ae5ae9a6e23.png)

**Comment by LuRenJiasWorld** [comment]
你好，编辑器目前应该是兼容WordPress 5.5版本的。请问你可以尝试一下重新安装本插件吗？

![image](https://user-images.githubusercontent.com/29622423/90883128-d2ad3400-e3df-11ea-8f00-5a72b074e64a.png)

**Comment by CreeperKong** [comment]
我把Opcache禁用再重新启用了一下就好了。。。
