### ISSUE TITLE
文章代码块不能换行

### ISSUE THREAD

**Issue by lin-gy-1106089861** [LuRenJiasWorld/WP-Editor.md#484]

**Comment by lin-gy-1106089861** [comment]
![image](https://user-images.githubusercontent.com/69132513/91517731-109ae280-e921-11ea-83b3-c439b3abb939.png)
![image](https://user-images.githubusercontent.com/69132513/91517742-18f31d80-e921-11ea-8b9f-5486916081ed.png)
可以查看到编辑时候是换行，发布出去不是换行的

**Comment by LuRenJiasWorld** [comment]
你好，请问可以提供一个可复现问题的地址吗？我看看是什么原因导致。
