### ISSUE TITLE
将“添加媒体”按钮加入全屏视图工具栏中的建议

### ISSUE THREAD

**Issue by Yoorkin** [LuRenJiasWorld/WP-Editor.md#487]
![image](https://user-images.githubusercontent.com/29514144/92493678-60ce4a80-f227-11ea-9e45-1869c5daa310.png)
如图，全屏视图下编辑md更舒服，但是添加媒体时经常要退出去点那个按钮
建议将“添加媒体”按钮加入全屏视图工具栏，像这样：
![image](https://user-images.githubusercontent.com/29514144/92493556-3b414100-f227-11ea-9ecb-21ed4dc67616.png)
免去来回切换全屏的麻烦

**Comment by LuRenJiasWorld** [comment]
你好，这的确是个好建议，但如果安装有其他插件，上面的按钮不止添加媒体一项，如图所示：

![image](https://user-images.githubusercontent.com/29622423/92496041-35992a80-f22a-11ea-8e6b-bfa321b4977d.png)

由于按键数量、内容与按键行为的不可控性，这里可能没办法按照你的建议进行修改，非常抱歉。

如果是有上传图片的需求，我的建议是在设置中开启图片粘贴上传，这样就可以直接在图片上`ctrl+c`，再在编辑器里`ctrl+v`来实现便捷上传。

**Comment by Yoorkin** [comment]
之前没注意到可以直接粘贴，谢谢你的回复
