### ISSUE TITLE
标题颜色

### ISSUE THREAD

**Issue by HaoyueQiu** [LuRenJiasWorld/WP-Editor.md#489]
编辑时标题颜色能设置成纯黑而不是灰色么

**Comment by LuRenJiasWorld** [comment]
> 编辑时标题颜色能设置成纯黑而不是灰色么

你好，样式是由CSS控制的，目前暂不提供修改样式的入口，但在未来版本有计划加入自定义样式功能。

目前如果是想修改前台样式，可以通过WordPress的主题自定义功能实现，后台样式比较难解决，抱歉带来不便。

**Comment by LuRenJiasWorld** [comment]
你好，最近两年由于个人原因，没有跟进插件维护，现在开始继续维护，正在处理堆积的 Issue。
由于这个 Issue 没有进一步提供信息，或提供有效复现方法，或不确定您是否还在使用该插件，暂时先关闭处理。
如果您依然使用该插件，或希望继续推进该问题的解决，欢迎重新打开 Issue，我会尽力&尽快跟进。
感谢支持和理解。
