### ISSUE TITLE
检验到插件资源包已过时，请在设置页面中进行配置！

### ISSUE THREAD

**Issue by shellphy** [LuRenJiasWorld/WP-Editor.md#490]
我升级插件之后，在我的 wordpress 后台的每个页面顶部都提示这个：

检验到插件资源包已过时，请在设置页面中进行配置！

删除重装后还是提示这个

**Comment by LuRenJiasWorld** [comment]
> 我升级插件之后，在我的 wordpress 后台的每个页面顶部都提示这个：
> 
> 检验到插件资源包已过时，请在设置页面中进行配置！
> 
> 删除重装后还是提示这个

你好，出现此问题可能是因为升级不完整导致。你可以在本插件的设置中找到编辑器静态资源地址，然后任意点击两个按钮中的任何一个，再保存试试看呢？

![image](https://user-images.githubusercontent.com/29622423/93659681-8acf0a80-fa7a-11ea-98cb-565f65e85424.png)

**Comment by LuRenJiasWorld** [comment]
如果尝试之后问题依旧，请上传一下高级设置中的调试信息，谢谢~

**Comment by LuRenJiasWorld** [comment]
你好，经检查，是因为`jsdelivr`的CDN缓存没有及时刷新导致。我已经给他们发了邮件，请求更新缓存，目前这个提示是不影响使用的（因为实际资源版本没有错）。非常抱歉带来不便，修复后我会更新此Issue告知 :)


![image](https://user-images.githubusercontent.com/29622423/93665539-d64cdd00-faa9-11ea-867e-5b779faf4e9c.png)

**Comment by shellphy** [comment]
已经解决，感谢

**Comment by LuRenJiasWorld** [comment]
好的~
