### ISSUE TITLE
“编辑器静态资源地址”使用CDN资源时提示资源已过时，切换到本机资源后恢复正常

### ISSUE THREAD

**Issue by xkww3n** [LuRenJiasWorld/WP-Editor.md#491]
额，虽然说有解决方案吧，但毕竟能从服务器上省一点流量是一点嘛233
调试信息如下：

![image](https://user-images.githubusercontent.com/30206355/93663791-e3170400-fa9c-11ea-8481-2ff884f53aac.png)

**Comment by LuRenJiasWorld** [comment]
你好，这一问题可以复现，我先看看是什么原因导致的。

**Comment by LuRenJiasWorld** [comment]
经检查，是因为`jsdelivr`的CDN缓存没有及时刷新导致。我已经给他们发了邮件，请求更新缓存，目前这个提示是不影响使用的（因为实际资源版本没有错）。非常抱歉带来不便，修复后我会更新此Issue告知 :)


![image](https://user-images.githubusercontent.com/29622423/93665539-d64cdd00-faa9-11ea-867e-5b779faf4e9c.png)

**Comment by xkww3n** [comment]
> 经检查，是因为`jsdelivr`的CDN缓存没有及时刷新导致。我已经给他们发了邮件，请求更新缓存，目前这个提示是不影响使用的（因为实际资源版本没有错）。非常抱歉带来不便，修复后我会更新此Issue告知 :)
> 
> ![image](https://user-images.githubusercontent.com/29622423/93665539-d64cdd00-faa9-11ea-867e-5b779faf4e9c.png)

问题已解决了，感谢作者

**Comment by LuRenJiasWorld** [comment]
> > 经检查，是因为`jsdelivr`的CDN缓存没有及时刷新导致。我已经给他们发了邮件，请求更新缓存，目前这个提示是不影响使用的（因为实际资源版本没有错）。非常抱歉带来不便，修复后我会更新此Issue告知 :)
> > ![image](https://user-images.githubusercontent.com/29622423/93665539-d64cdd00-faa9-11ea-867e-5b779faf4e9c.png)
> 
> 问题已解决了，感谢作者

好的，没关系~
