### ISSUE TITLE
从10.2.0升级到10.2.1失败

### ISSUE THREAD

**Issue by qlmlove** [LuRenJiasWorld/WP-Editor.md#492]
从10.2.0升级到10.2.1失败，更新页面显示成功，但是一刷新页面又显示需要更新，版本还是10.2.0

**Comment by LuRenJiasWorld** [comment]
> 从10.2.0升级到10.2.1失败，更新页面显示成功，但是一刷新页面又显示需要更新，版本还是10.2.0

请问有尝试过卸载后重新安装吗？

**Comment by qlmlove** [comment]
> > 从10.2.0升级到10.2.1失败，更新页面显示成功，但是一刷新页面又显示需要更新，版本还是10.2.0
> 
> 请问有尝试过卸载后重新安装吗？

重新安装也是同样的旧版本

**Comment by LuRenJiasWorld** [comment]
可以提供一下站点首页地址吗？我看看加载的资源文件是否正常。

**Comment by qlmlove** [comment]
> 可以提供一下站点首页地址吗？我看看加载的资源文件是否正常。

www.qlm.life

**Comment by LuRenJiasWorld** [comment]
了解了，你的站点加载的静态资源文件还是10.2.0版本。可能是因为没有成功更新配置导致，你可以尝试一下在本插件的设置中手动设置一下静态资源地址试试看：

![image](https://user-images.githubusercontent.com/29622423/94360317-e20a5600-00de-11eb-9d97-17395fb92662.png)

**Comment by qlmlove** [comment]
> 了解了，你的站点加载的静态资源文件还是10.2.0版本。可能是因为没有成功更新配置导致，你可以尝试一下在本插件的设置中手动设置一下静态资源地址试试看：
> 
> ![image](https://user-images.githubusercontent.com/29622423/94360317-e20a5600-00de-11eb-9d97-17395fb92662.png)

直接修改版本号的话保存之后就又变成10.2.0了，点“使用本地资源“”也不能更新到新版本，导出的调试信息如下
[![0kUAMD.md.png](https://s1.ax1x.com/2020/09/27/0kUAMD.md.png)](https://imgchr.com/i/0kUAMD)

**Comment by LuRenJiasWorld** [comment]
这个非常奇怪，之前没有接到类似的用户反馈。你安装的是 https://github.com/LuRenJiasWorld/WP-Editor.md/releases/tag/v10.2.1 这里的版本吗？

**Comment by qlmlove** [comment]
> 这个非常奇怪，之前没有接到类似的用户反馈。你安装的是 https://github.com/LuRenJiasWorld/WP-Editor.md/releases/tag/v10.2.1 这里的版本吗？

插件商店搜索直接安装的，版本应该是这个版本。等我有空了去服务器上直接复制个新版本看看能不能成功，好久没登服务器，账号密码都不知道丢哪儿了！这两天有点忙，暂时没时间折腾，等我解决了再回复你吧！🤔

**Comment by LuRenJiasWorld** [comment]
好的，虽然有这个提示，但应该是不影响使用的。你先试试看删除插件后重新安装，如果还是有问题，我再具体检查一下。

**Comment by CHNhawk** [comment]
遇到同样问题了。V10.2.0到V10.2.1用WordPress的自动更新没成功。重新下载Release的文件覆盖好了
