### ISSUE TITLE
在表格中使用数学公式无法渲染

### ISSUE THREAD

**Issue by yingmanwumen** [LuRenJiasWorld/WP-Editor.md#494]
如题，在表格中使用数学公式，能够在预览中查看，但是在实际的页面中，并没有成功渲染数学公式

**Comment by LuRenJiasWorld** [comment]
你好，这个功能的确之前没有考虑过，我会在下个版本加入，到时候会更新此Issue告知的。感谢反馈！

**Comment by LuRenJiasWorld** [comment]
你好，该问题已于  https://github.com/LuRenJiasWorld/WP-Editor.md/commit/d3c0f07312760df4dd9712deb844ec3dc9a899fc 解决，将会在11月初发布的10.3.0版本加入，如果着急使用可以利用WordPress的插件编辑功能同步该修订到对应位置。再次感谢反馈，祝使用愉快。
