### ISSUE TITLE
关闭“使评论支持Markdown写作”

### ISSUE THREAD

**Issue by shellphy** [LuRenJiasWorld/WP-Editor.md#497]
我不想在评论中使用 Markdown，在设置中已经关闭了：

![Snipaste_2020-10-12_11-56-30](https://user-images.githubusercontent.com/12596198/95703961-17d44080-0c82-11eb-944f-5042386c45c6.png)

但是评论中仍然是 Markdown 编辑器：

![Snipaste_2020-10-12_11-57-35](https://user-images.githubusercontent.com/12596198/95704020-26225c80-0c82-11eb-83bb-4e39ebae8ca9.png)

**Comment by LuRenJiasWorld** [comment]
这里的选项只是禁用Markdown语法，如果需要关闭Markdown编辑器，请确保以下两个选项关闭：

![image](https://user-images.githubusercontent.com/29622423/95716409-fed98880-0c9d-11eb-9107-517669081c38.png)

**Comment by shellphy** [comment]
好的，知道了，谢谢了
