### ISSUE TITLE
[问题]Uncaught TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by xiebruce** [LuRenJiasWorld/WP-Editor.md#505]
**错误如下所示**
![image](https://user-images.githubusercontent.com/13575500/99646184-24bb2f80-2a8b-11eb-9bb4-dcb1f73c3bd8.png)

**复现方法：**
打开[www.xiebruce.top](https://www.xiebruce.top)，打开控制台，刷新页面，即可看到报错，这个应该不是插件的问题，只是我不知道因为我哪儿些写法不对导致这个报错，麻烦你帮忙看看，感谢！

**Comment by LuRenJiasWorld** [comment]
了解，我看看是什么原因导致的，尽量给你帮助。

**Comment by LuRenJiasWorld** [comment]
你好，这个问题应该是由于误加载编辑器语言文件（但其依赖的编辑器本体未被加载）导致。应该是编辑器引起的BUG，奇怪的是之前的确没有收到过用户反馈，不排除是你这边安装的环境问题。

根据你的站点来看，你使用的是本编辑器的10.0.3版本，已经是一年前的旧版本了，因此我的建议是先尝试更新到最新的10.2.1版本，更新后再看看报错是否消失。

**Comment by xiebruce** [comment]
@LuRenJiasWorld 最新版本不敢用啊，吞`$`问题应该还没有解决吧？

**Comment by LuRenJiasWorld** [comment]
> @LuRenJiasWorld 最新版本不敢用啊，吞`$`问题应该还没有解决吧？

可以先尝试一下，有问题再回退到旧版本。

这个问题目前我还在看，解决起来比较麻烦，不过据目前了解，并不是所有用户都会遇到这个问题（如果没有公式编辑需求，也可以直接关闭LaTeX解析解决此问题）。

**Comment by xiebruce** [comment]
哦，原来是Latex导致的呀
