### ISSUE TITLE
[BUG]代码块在多个缩进的情况下出现解析错误(```变成“`)的问题

### ISSUE THREAD

**Issue by yusian** [LuRenJiasWorld/WP-Editor.md#506]
**BUG描述 | Describe the bug**
在某些缩进的情况下，代码块无法正常解析，\`\`\`在页面上显示为"`。
相关说明：
1、数据库中是```，说明发布文章时存入数据的时候应该是没有问题的，读取出来后才变成这样的；
2、编写文章时实时预览是好的。

**复现方法 | To Reproduce**
查看链接：https://www.yusian.com/blog/java/2020/11/19/1125001586.html#more-1586

**截图 | Screenshots**
编辑文章时预览情况：
<img width="778" alt="截屏2020-11-25 下午5 07 18" src="https://user-images.githubusercontent.com/7299601/100206203-fe8d0800-2f40-11eb-9aee-ec92357e5381.png">
页面显示情况：
<img width="482" alt="截屏2020-11-25 下午5 06 43" src="https://user-images.githubusercontent.com/7299601/100206177-f634cd00-2f40-11eb-9049-65ae61349326.png">

**Comment by LuRenJiasWorld** [comment]
你好，该问题似乎会随机出现，但由于采集到样本不足，暂时无法判断是哪里的问题。请问可以先检查一下与第三方插件/主题的兼容性吗？

**Comment by yusian** [comment]
> 你好，该问题似乎会随机出现，但由于采集到样本不足，暂时无法判断是哪里的问题。请问可以先检查一下与第三方插件/主题的兼容性吗？

你好，感谢你的及时反馈，我有测试过，将其他插件都停用甚至卸载，问题依旧存在。

**Comment by LuRenJiasWorld** [comment]
> > 你好，该问题似乎会随机出现，但由于采集到样本不足，暂时无法判断是哪里的问题。请问可以先检查一下与第三方插件/主题的兼容性吗？
> 
> 你好，感谢你的及时反馈，我有测试过，将其他插件都停用甚至卸载，问题依旧存在。

好的，根据你的描述，数据库Markdown原文应该是没有问题的，不过数据库里应该还会存储一份转换后的HTML，请问那个HTML里的代码块符号有被正常解析吗？

此外，我看你贴出来的原文里，```符号前面带了缩进，这应该是不符合Markdown规则的，你可以尝试一下去除那个缩进（结尾的```也去掉），看看问题是否能够解决。

**Comment by yusian** [comment]
> > > 你好，该问题似乎会随机出现，但由于采集到样本不足，暂时无法判断是哪里的问题。请问可以先检查一下与第三方插件/主题的兼容性吗？
> > 
> > 
> > 你好，感谢你的及时反馈，我有测试过，将其他插件都停用甚至卸载，问题依旧存在。
> 
> 好的，根据你的描述，数据库Markdown原文应该是没有问题的，不过数据库里应该还会存储一份转换后的HTML，请问那个HTML里的代码块符号有被正常解析吗？
> 
> 此外，我看你贴出来的原文里，\`符号前面带了缩进，这应该是不符合Markdown规则的，你可以尝试一下去除那个缩进（结尾的`也去掉），看看问题是否能够解决。

------------------分隔线---------------------
1. 第一点说明

   * AAAAAAAAAA

   * BBBBBBBBBB

     ```java
     // coding1...
     ```

   * CCCCCCCCCC

2. 第二点说明

   ```java
   // coding2...
   ---------------
   // coding3...
   ```

3. 第三点说明


------------------分隔线---------------------
我的问题已经解决了，非常感谢，缩进本身应该是合规的，因为我的代码块属于子条目，如上所示。我是在Typora中编辑好后再粘源码到我们编辑器发表的，以上在github中能正常解析，在我们的编辑器能正常预览，但发布后会出现异常，我多次测试后发现如下规律：
1. coding1处的代码出现异常是因为前面的缩进是5个空格(Typora生成的)，如果改成4个就能正常显示，不明原因。
2. coding2与coding3这里不能正常显示是因为中间有“----------”，3个空格+三个“-”就会出现异常。我把源码发给你，研究一下。
[demo.zip](https://github.com/LuRenJiasWorld/WP-Editor.md/files/5603257/demo.zip)

**Comment by LuRenJiasWorld** [comment]
了解，这里我还是想办法尽量兼容一下，感谢反馈:)
