### ISSUE TITLE
[BUG] xss漏洞

### ISSUE THREAD

**Issue by hakuQAQ** [LuRenJiasWorld/WP-Editor.md#507]
**BUG描述 | Describe the bug**
> 请清晰描述BUG的行为
> A clear and concise description of what the bug is.

markdown代码块里的代码能逃逸出html编码，造成xss漏洞

**复现方法 | To Reproduce**
> 你是如何复现此BUG的，最好附带上能复现此BUG的文章地址或Markdown原文（建议使用[Pastebin](https://paste.ubuntu.com)或[Gist](https://gist.github.com)上传）
> Steps to reproduce the behavior: Attached with link address of the post or plain Markdown text (Recommend using [Pastebin](https://paste.ubuntu.com) or [Gist](https://gist.github.com)) will be better.

文章地址：http://47.110.251.39/wordpress/index.php/2020/11/25/test/

markdown原文如下
![image](https://user-images.githubusercontent.com/52093689/100230894-3ad06080-2f61-11eb-8fb9-c52613a308cb.png)

**期望行为 | Expected behavior**
> 请描述你认为该功能的期望行为
> A clear and concise description of what you expected to happen.

修复叭

**截图 | Screenshots**
> 详细的截图能帮助我们更好分析并重现此问题
> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/52093689/100230769-183e4780-2f61-11eb-9f8a-1bb47b5e6072.png)

**Comment by LuRenJiasWorld** [comment]
你好，这是一个已知问题，预计将于下一版本发布修复。我稍后尝试一下在最新版本和开发分支复现此问题。

**Comment by hakuQAQ** [comment]
okok
