### ISSUE TITLE
[BUG]文章内容超过 9400 字左右显示不完整

### ISSUE THREAD

**Issue by joyven** [LuRenJiasWorld/WP-Editor.md#509]
**BUG描述 | Describe the bug**
> 当文章内容大约在 9400 字左右的时候，文章就显示不完整。

**复现方法 | To Reproduce**
> 任意 9400 多字的长文。

**期望行为 | Expected behavior**
> 希望能够正常展示。测试了原生的文本编辑器，出现此问题。

**截图 | Screenshots**
> 文章地址为： https://www.zhoujunwen.com/2019/%e6%b7%b1%e5%85%a5%e7%90%86%e8%a7%a3%e7%b1%bb%e6%96%87%e4%bb%b6%e7%bb%93%e6%9e%84/ 
![image](https://user-images.githubusercontent.com/5885519/100863351-6908ef80-34cf-11eb-9de1-8765806a2cf2.png)

**Comment by LuRenJiasWorld** [comment]
你好，我也写过一些超过1万字的文章，但没有遇到过此问题。猜测应该是在解析LaTeX的过程中产生了错误导致。请问可以上传一下LaTeX原文吗？我在我这边的环境里测试一下。

**Comment by joyven** [comment]
内容粘贴上来就会被解析了，所以我把这篇文章的 markdown 文件上传到 git 仓库了。
https://github.com/joyven/jishuzhan/blob/master/%E6%96%87%E4%BB%B6%E8%A7%A3%E6%9E%90%E5%BC%82%E5%B8%B8.md
这个是链接。

**Comment by joyven** [comment]
> 你好，我也写过一些超过1万字的文章，但没有遇到过此问题。猜测应该是在解析LaTeX的过程中产生了错误导致。请问可以上传一下LaTeX原文吗？我在我这边的环境里测试一下。

原文章内容如上我粘贴的链接。麻烦查看。谢谢！

**Comment by LuRenJiasWorld** [comment]
> > 你好，我也写过一些超过1万字的文章，但没有遇到过此问题。猜测应该是在解析LaTeX的过程中产生了错误导致。请问可以上传一下LaTeX原文吗？我在我这边的环境里测试一下。
> 
> 原文章内容如上我粘贴的链接。麻烦查看。谢谢！

好的，我尽快看看是什么原因导致。

**Comment by LuRenJiasWorld** [comment]
你好，我这边无法复现你所描述的问题：https://untitled.pw/test-page-20201203 。

但解析过程的确耗时较长（大概4秒左右），这是建立在一台32核服务器的基准上，如果服务器配置较低，耗时会更长，因此我猜测可能是Markdown解析时间超过了你所设定的PHP脚本超时时间。

请尝试一下修改php.ini或者php-fpm（如果使用了fpm的话），将超时时间设置为60秒或更长，然后重启PHP和Web服务器，再尝试保存文章，看看问题是否还会出现？

此外，在解析Markdown过程中存在比较复杂的LaTeX公式解析，如果你没有此需求也可以在本插件的设置中关闭LaTeX解析，性能会有一定的提升。

**Comment by joyven** [comment]
> 你好，我这边无法复现你所描述的问题：https://untitled.pw/test-page-20201203 。
> 
> 但解析过程的确耗时较长（大概4秒左右），这是建立在一台32核服务器的基准上，如果服务器配置较低，耗时会更长，因此我猜测可能是Markdown解析时间超过了你所设定的PHP脚本超时时间。
> 
> 请尝试一下修改php.ini或者php-fpm（如果使用了fpm的话），将超时时间设置为60秒或更长，然后重启PHP和Web服务器，再尝试保存文章，看看问题是否还会出现？
> 
> 此外，在解析Markdown过程中存在比较复杂的LaTeX公式解析，如果你没有此需求也可以在本插件的设置中关闭LaTeX解析，性能会有一定的提升。

好的，我根据你说的配置试试看。
