### ISSUE TITLE
[Feature] 代码片段能不能加个选项不折叠

### ISSUE THREAD

**Issue by magicdmer** [LuRenJiasWorld/WP-Editor.md#510]
**该功能的缺失是否引起你的使用不便？**
> 有时候代码片段不是很长，直接显示全部要更加直观

**你认为该功能应该是什么样的？ | Describe the solution you'd like**
> 代码设置加个选项，可以设置多少行启用折叠（显示竖着的滑条）

**Comment by LuRenJiasWorld** [comment]
你好，请问可以提供一个代码片段被折叠的链接示例吗？我看看如何处理会比较适合。

**Comment by magicdmer** [comment]
> 你好，请问可以提供一个代码片段被折叠的链接示例吗？我看看如何处理会比较适合。

https://magicdmer.site/742.html
还是这个链接，我反馈的另一个行号问题也是这个链接

**Comment by LuRenJiasWorld** [comment]
![image](https://user-images.githubusercontent.com/29622423/102036957-05e85880-3dff-11eb-885c-45f36472b56c.png)

关于代码片段被折叠的问题，请删除主题中红框标记的这一行CSS，本插件目前还没有计划强制覆盖主题样式，所以实际渲染出来的样式是由主题决定的。

至于不显示行号的问题，请问可以上传一下本插件设置中调试信息吗？感谢。

**Comment by magicdmer** [comment]
感谢回复，关于行号分类我开了另一个issue，我看到你已经反馈了在调查
