### ISSUE TITLE
[BUG] 语法高亮设置启用行号后没显示

### ISSUE THREAD

**Issue by magicdmer** [LuRenJiasWorld/WP-Editor.md#511]
**BUG描述 | Describe the bug**
> 语法高亮设置启用行号，正文没显示行号

**问题文章示例**
https://magicdmer.site/742.html

**调试信息 | Debugging info**
![wp-editormd-debug-info.png](https://i.loli.net/2020/12/11/VKiysHa9YcRBx5L.png)

**Comment by LuRenJiasWorld** [comment]
好的，我现在看看，请稍等。

**Comment by magicdmer** [comment]
大佬有进展不？

**Comment by LuRenJiasWorld** [comment]
> 大佬有进展不？

暂时还在看，最近比较忙，可能需要再等等。非常抱歉带来不便。

**Comment by magicdmer** [comment]
> > 大佬有进展不？
> 
> 暂时还在看，最近比较忙，可能需要再等等。非常抱歉带来不便。

我可能知道啥原因了，貌似只要使用代码段的时候不指定具体的语言就不会出现行号
