### ISSUE TITLE
[BUG]编辑器短代码前台文章内容页显示异常

### ISSUE THREAD

**Issue by Arisono** [LuRenJiasWorld/WP-Editor.md#512]
**BUG描述 | Describe the bug**
>  短代码区域出现了字符：“<code class="language-javascrit "></code>”   不希望出现这些字符。

![image](https://user-images.githubusercontent.com/8653027/102057725-5674ab80-3e29-11eb-9f9a-7b7a656a533e.png)

**复现方法 | To Reproduce**
查看我的网址可以复现：https://www.yundashi168.com/130.html  

**期望行为 | Expected behavior**
不要出现这些字符串

**截图 | Screenshots**

问题描述：代码块区域出现了字符：<code class="language-javascript "></code>   
使用主题：https://github.com/Licoy/wordpress-theme-puock
问题截图：
![image](https://user-images.githubusercontent.com/8653027/102056529-7b681f00-3e27-11eb-815a-8bea3bd692f2.png)

**调试信息 | Debugging info**

![wp-editormd-debug-info](https://user-images.githubusercontent.com/8653027/102057061-4ad4b500-3e28-11eb-8fed-1748ef23e120.png)

**其他内容 | Additional context**
> 可以在这里提交其他你觉得可能会有帮助的内容
> Add any other context about the problem here.

**Comment by LuRenJiasWorld** [comment]
你好，请问在使用其他主题时存在此问题吗？

**Comment by Arisono** [comment]
其它主题没有这个问题，是不是主题兼容性问题？

**Comment by LuRenJiasWorld** [comment]
我这边大概查看了一下，问题出在主题自带了代码高亮功能，你可以看看有没有办法关闭这一功能，关闭后即可正常工作。

**Comment by Arisono** [comment]
非常感谢大牛，我知道怎么去做了。非常谢谢你的帮忙。

**Comment by LuRenJiasWorld** [comment]
嗯嗯，没关系，关闭主题自带的代码高亮之后应该就没问题了~
