### ISSUE TITLE
[BUG]代码块中，语言选择Delphi/pascal，代码不会高亮

### ISSUE THREAD

**Issue by xenli** [LuRenJiasWorld/WP-Editor.md#513]
**BUG描述 | Describe the bug**
> 请清晰描述BUG的行为
> A clear and concise description of what the bug is.
在Wordpress代码块中，语言选择Delphi/pascal，代码不会高亮，

![image](https://user-images.githubusercontent.com/49088145/103052171-70558180-45d3-11eb-9c4d-7f84bf710ba2.png)
![image](https://user-images.githubusercontent.com/49088145/103052206-87946f00-45d3-11eb-8f6d-5a746f4994cf.png)

而把delphi改成pascal则可以高亮
![image](https://user-images.githubusercontent.com/49088145/103052284-b7437700-45d3-11eb-9919-4ade26af773d.png)

我把code-block-dialog.js文件中的(delphi        : ["Delphi/Pascal", "pascal"],)  修改为(pascal        : ["Delphi/Pascal", "pascal"],)，再次选择该代码块，出来的还是Delphi
![image](https://user-images.githubusercontent.com/49088145/103052384-f5d93180-45d3-11eb-8359-8f93d4851014.png)

希望修正。

**Comment by xenli** [comment]
另外选择行内代码。超过一定长度，怎么自动换行或者出现滚动条？
![image](https://user-images.githubusercontent.com/49088145/103052585-6a13d500-45d4-11eb-8b8a-1e123d824077.png)

**Comment by LuRenJiasWorld** [comment]
你好，最近两年由于个人原因，没有跟进插件维护，现在开始继续维护，正在处理堆积的Issue。
由于这个 Issue 没有提供有效复现方法，且不确定您是否还在使用该插件，暂时先关闭处理。
如果您依然使用该插件，或希望继续推进该问题的解决，欢迎重新打开 Issue，我会尽力&尽快跟进。
感谢支持和理解。
