### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by QingYuanQu** [LuRenJiasWorld/WP-Editor.md#515]
**BUG描述 | Describe the bug**
> 与Blocksy theme冲突，启用插件，自定义theme时，无法编辑 页眉和底部。

**Comment by LuRenJiasWorld** [comment]
你好，最近两年由于个人原因，没有跟进插件维护，现在开始继续维护，正在处理堆积的Issue。
由于这个 Issue 没有提供有效复现方法，且不确定您是否还在使用该插件，暂时先关闭处理。
如果您依然使用该插件，或希望继续推进该问题的解决，欢迎重新打开 Issue，我会尽力&尽快跟进。
感谢支持和理解。
