### ISSUE TITLE
开启emoji后文章无限转圈 任务列表无法显示

### ISSUE THREAD

**Issue by Hellobaka** [LuRenJiasWorld/WP-Editor.md#517]
**BUG描述 | Describe the bug**
使用的主题：[Sakura](https://github.com/mashirozx/Sakura)
1. 问题描述：开启emoji选项后，文章无法成功加载，无限转圈，但PHP终端不报错以及不再显示正在加载的网页。关闭emoji选项后正常加载。
2. 问题描述：在编辑器写下MD代码`- [x] 文本文本`后, 实时预览显示正常.发布文章之后, 仍旧显示原文本`- [x] 文本文本`

**复现方法 | To Reproduce**
第二个bugMD代码:
```
- [x] Cookie需求
[查看json结果](https://gitee.com/xxxxx.json")
```

**期望行为 | Expected behavior**
正常显示任务列表的复选框

**截图 | Screenshots**
编辑器内展示如下: 
![image](https://user-images.githubusercontent.com/50934714/104020209-ce9b7a80-51f7-11eb-933d-9e039c5ed8c0.png)
文章发布后样式:
![image](https://user-images.githubusercontent.com/50934714/104020675-892b7d00-51f8-11eb-8d33-4b94fd365ef7.png)

**调试信息 | Debugging info**
![wp-editormd-debug-info](https://user-images.githubusercontent.com/50934714/104020791-b5df9480-51f8-11eb-9e55-d790f344615c.png)

**Comment by LuRenJiasWorld** [comment]
你好，最近两年由于个人原因，没有跟进插件维护，现在开始继续维护，正在处理堆积的Issue。
由于这个 Issue 没有提供有效复现方法，且不确定您是否还在使用该插件，暂时先关闭处理。
如果您依然使用该插件，或希望继续推进该问题的解决，欢迎重新打开 Issue，我会尽力&尽快跟进。
感谢支持和理解。
