### ISSUE TITLE
[BUG]在某些情况下输入“>”无法正确渲染数学公式

### ISSUE THREAD

**Issue by miniwater** [LuRenJiasWorld/WP-Editor.md#520]
**BUG描述 | Describe the bug**
> 请清晰描述BUG的行为
> A clear and concise description of what the bug is.

在某些情况下输入“>”无法正确渲染数学公式，前端页面无法显示公式，我无法排除具体哪个位置出了问题或者是我语法问题，但在typora中是能正常显示的。

**复现方法 | To Reproduce**
> 你是如何复现此BUG的，最好附带上能复现此BUG的文章地址或Markdown原文（建议使用[Pastebin](https://paste.ubuntu.com)或[Gist](https://gist.github.com)上传）
> Steps to reproduce the behavior: Attached with link address of the post or plain Markdown text (Recommend using [Pastebin](https://paste.ubuntu.com) or [Gist](https://gist.github.com)) will be better.

新建文章输入一下内容——————

# 测试

$$
\lim_{n \to +\infty} \frac{a_{0}n^k+a_{1}n^{k-1}+...}{b_{0}n^z+b_{1}n^{z-1}+...} =
\begin{cases}
0, & k<z \\\\
\frac{a_0}{b_0}, & k=z \\\\
\infty , & k>z \\\\
\end{cases}
$$

此时前端页面打印——————

z \\
\end{cases}
$$

但如果把“>”换成其他符号或者特殊符号如“＞”则正常渲染公式

**期望行为 | Expected behavior**
> 请描述你认为该功能的期望行为
> A clear and concise description of what you expected to happen.

我无法确实是我语法问题还是渲染方案问题

**截图 | Screenshots**
> 详细的截图能帮助我们更好分析并重现此问题
> If applicable, add screenshots to help explain your problem.

**调试信息 | Debugging info**
> 请在WP Editor.md的高级设置中导出调试信息，将图片上传到这里
> Please export debugging info at the advanced settings in WP Editor.md settings panel, then paste it here.

**其他内容 | Additional context**
> 可以在这里提交其他你觉得可能会有帮助的内容
> Add any other context about the problem here.

**Comment by LuRenJiasWorld** [comment]
你好，最近两年由于个人原因，没有跟进插件维护，现在开始继续维护，正在处理堆积的Issue。
由于这个 Issue 没有提供有效复现方法，且不确定您是否还在使用该插件，暂时先关闭处理。
如果您依然使用该插件，或希望继续推进该问题的解决，欢迎重新打开 Issue，我会尽力&尽快跟进。
感谢支持和理解。
