### ISSUE TITLE
[BUG] 表格無法正常顯示

### ISSUE THREAD

**Issue by howarder3** [LuRenJiasWorld/WP-Editor.md#526]
**BUG描述 | Describe the bug**
> 如下圖範例，雖然在編輯器中可以看到表格顏色，但實際顯示並沒有顏色，也沒有表格的框線顯示。

* 編輯器中的畫面:
![image](https://user-images.githubusercontent.com/8501084/109176229-8cd38d00-77c1-11eb-8e68-62a8ec12620a.png)
![image](https://user-images.githubusercontent.com/8501084/109176249-92c96e00-77c1-11eb-80f7-a0191f42218b.png)

* 實際畫面:

![image](https://user-images.githubusercontent.com/8501084/109176315-a543a780-77c1-11eb-86e0-bc2d0e508eea.png)

**期望行为 | Expected behavior**
> 期望可以依照編輯器的顏色正常顯示，以及表格的框線顯示。

**其他内容 | Additional context**
> 感謝作者開發，此外掛非常的實用。

**Comment by LuRenJiasWorld** [comment]
抱歉回复迟了一些。如果实际的页面没有表格，说明你使用的主题没有表格样式，你可以更换一个其他主题，看看能否正常显示表格。
如果确定是主题的问题，可以去网上搜索 “CSS 表格样式”，选你喜欢的，粘贴到 WordPress 的自定义 CSS 中，一般都可以生效。
