### ISSUE TITLE
[问题] 请问使用过程中需要将2（多）个图片并行显示如何设置呢。 

### ISSUE THREAD

**Issue by nebofeng** [LuRenJiasWorld/WP-Editor.md#528]
**问题描述 
> 请问在使用过程中如果需要将2（多）个图片并行显示如何设置呢。  我尝试了网上搜索的方法，img 标签等， ![]()并排等。但是都不起作用。 最终我是选择使用表格达到类似效果。请问有其他更好的方法吗。谢谢！

**Comment by LuRenJiasWorld** [comment]
你好，表格方式是最简单的方式，因为 Markdown 本身是没有排版能力的。
