### ISSUE TITLE
[BUG] 编辑器无法正确的显示超链接

### ISSUE THREAD

**Issue by magicdmer** [LuRenJiasWorld/WP-Editor.md#529]
**BUG描述**
在编辑器中直接贴入超链接url，然后点击发布，页面刷新后，编辑器中超链接的位置空了，图片如下：
![image](https://user-images.githubusercontent.com/5556368/113821484-bc0cef00-97ae-11eb-8553-bfe159767e04.png)
但是最终发布的显示的页面是正常的，https://magicdmer.com/924.html

**调试信息**
![image](https://user-images.githubusercontent.com/5556368/113821647-f5ddf580-97ae-11eb-9e32-f7e6230c95b4.png)

**其他内容**
如果输入\[https://www.baidu.com](https://www.baidu.com) 这种格式，不会转换为正常的 url，而是变成 \[https://www.baidu.com](https://www.baidu.com) 这种展示

是因为我是浏览器复制的url，贴入的不是纯文本？

**Comment by magicdmer** [comment]
另外如图所示，live view 实时预览我是关闭的，但是我写文章的时候，或者点击编辑文章的时候，右边的预览还是打开了

**Comment by LuRenJiasWorld** [comment]
你好，最近两年由于个人原因，没有跟进插件维护，现在开始继续维护，正在处理堆积的 Issue。
由于这个 Issue 没有进一步提供信息，或提供有效复现方法，或不确定您是否还在使用该插件，暂时先关闭处理。
如果您依然使用该插件，或希望继续推进该问题的解决，欢迎重新打开 Issue，我会尽力&尽快跟进。
感谢支持和理解。
