### ISSUE TITLE
[BUG]在WP 5.7.1里无法正常显示markdown编写的文章

### ISSUE THREAD

**Issue by zanyzhao** [LuRenJiasWorld/WP-Editor.md#530]
**BUG描述 | Describe the bug**
> 请清晰描述BUG的行为
> A clear and concise description of what the bug is.
在WP 5.7.1里无法正常显示markdown编写的文章

**复现方法 | To Reproduce**
> 你是如何复现此BUG的，最好附带上能复现此BUG的文章地址或Markdown原文（建议使用[Pastebin](https://paste.ubuntu.com)或[Gist](https://gist.github.com)上传）
> Steps to reproduce the behavior: Attached with link address of the post or plain Markdown text (Recommend using [Pastebin](https://paste.ubuntu.com) or [Gist](https://gist.github.com)) will be better.
原文：
```markdown
# 111

– 111
– 222
```
![image](https://user-images.githubusercontent.com/1629409/115726324-36e02780-a3b5-11eb-98be-b7ec20c2507d.png)

发布文档后显示为：
![image](https://user-images.githubusercontent.com/1629409/115726288-2e87ec80-a3b5-11eb-9f89-7fed6ef86009.png)

**期望行为 | Expected behavior**
> 请描述你认为该功能的期望行为
> A clear and concise description of what you expected to happen.
文档发布后可以正常渲染出HTML

**截图 | Screenshots**
> 详细的截图能帮助我们更好分析并重现此问题
> If applicable, add screenshots to help explain your problem.
见上
**调试信息 | Debugging info**
> 请在WP Editor.md的高级设置中导出调试信息，将图片上传到这里
> Please export debugging info at the advanced settings in WP Editor.md settings panel, then paste it here.
![debug](https://user-images.githubusercontent.com/1629409/115727003-cede1100-a3b5-11eb-90c4-dfc32acdd444.png)

**其他内容 | Additional context**
> 可以在这里提交其他你觉得可能会有帮助的内容
> Add any other context about the problem here.

**Comment by BrokenArrow1404** [comment]
遇到了相同问题，请问如何解决

**Comment by LuRenJiasWorld** [comment]
你好，最近两年由于个人原因，没有跟进插件维护，现在开始继续维护，正在处理堆积的 Issue。
由于这个 Issue 没有进一步提供信息，或提供有效复现方法，或不确定您是否还在使用该插件，暂时先关闭处理。
如果您依然使用该插件，或希望继续推进该问题的解决，欢迎重新打开 Issue，我会尽力&尽快跟进。
感谢支持和理解。
