### ISSUE TITLE
[BUG]首页加载js报错

### ISSUE THREAD

**Issue by yusian** [LuRenJiasWorld/WP-Editor.md#531]
# 问题描述
* 博客地址：[https://www.yusian.com/blog](https://www.yusian.com/blog)
* 打开首页时会有一个js文件加载失败，url地址为：[https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.2.1/assets/Prism.js/components/prism-mysql.min.js](https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.2.1/assets/Prism.js/components/prism-mysql.min.js)，将该地址直接贴到浏览器中也无法正常打开，报404错误，点击以上链接即可看到；
* 直接打开我的博客首页，F12中即可看到问题重现；
* 目前好像只有在首页会有这个错误信息，文章页面不会出现。
# 尝试方法
* 编辑器静态资源地址，使用本地资源，会报错`插件资源包已损坏，请在下面提示链接中重新下载！`
* 我重新**下载插件扩展资源包**然后覆盖assets目录，问题依旧；
* 本地资源中assets目录下的version.json是可以直接访问是到的：[https://www.yusian.com/blog/wp-content/plugins/wp-editormd/assets/version.json](https://www.yusian.com/blog/wp-content/plugins/wp-editormd/assets/version.json)
* 使用CDN资源，状态显示：资源为最新版！但首页会报这个js文件无法加载。

**Comment by LuRenJiasWorld** [comment]
你好，最近两年由于个人原因，没有跟进插件维护，现在开始继续维护，正在处理堆积的 Issue。
由于这个 Issue 没有进一步提供信息，或提供有效复现方法，或不确定您是否还在使用该插件，暂时先关闭处理。
如果您依然使用该插件，或希望继续推进该问题的解决，欢迎重新打开 Issue，我会尽力&尽快跟进。
感谢支持和理解。
