### ISSUE TITLE
[BUG] wedocs不兼容

### ISSUE THREAD

**Issue by lichnow** [LuRenJiasWorld/WP-Editor.md#532]
**BUG描述 | Describe the bug**
在wedocs插件中编辑页面是预览是正常的，一发布就直接显示md源码

**复现方法 | To Reproduce**

**期望行为 | Expected behavior**
在wedocs文档中显示正常

**截图 | Screenshots**
![image](https://user-images.githubusercontent.com/1695900/115980400-053aac80-a5bf-11eb-8604-1a3aaf08b53e.png)

**调试信息 | Debugging info**

**其他内容 | Additional context**

**Comment by LuRenJiasWorld** [comment]
你好，最近两年由于个人原因，没有跟进插件维护，现在开始继续维护，正在处理堆积的 Issue。
由于这个 Issue 没有进一步提供信息，或提供有效复现方法，或不确定您是否还在使用该插件，暂时先关闭处理。
如果您依然使用该插件，或希望继续推进该问题的解决，欢迎重新打开 Issue，我会尽力&尽快跟进。
感谢支持和理解。
