### ISSUE TITLE
[BUG]$符号依旧显示为空白

### ISSUE THREAD

**Issue by janrs-io** [LuRenJiasWorld/WP-Editor.md#537]
[调试信息地址：http://yangjianyong.cn/?p=284](http://yangjianyong.cn/?p=284)
[代码例子：http://yangjianyong.cn/?p=269](http://yangjianyong.cn/?p=269)
第一次使用issue，我不知道怎么上传图片。在这没有广告的意思

</div></div></div></div>

<div class="clear"></div></div>
<div class="clear"></div></div>
<div class="clear"></div></body></html>[](url)

**Comment by xiebruce** [comment]
看这：https://github.com/LuRenJiasWorld/WP-Editor.md/issues/504#issuecomment-731920664 ，亲测有效！

**Comment by janrs-io** [comment]
> 看这：[#504 (comment)](https://github.com/LuRenJiasWorld/WP-Editor.md/issues/504#issuecomment-731920664) ，亲测有效！

可以了。谢谢。烦了好久的问题解决了
