### ISSUE TITLE
[BUG]不指定代码语言时，代码框无法显示行号

### ISSUE THREAD

**Issue by apolloxie** [LuRenJiasWorld/WP-Editor.md#541]
首先感谢作者提供了一个好用的WP插件。但该插件在代码框方面存在一些问题：不指定代码所使用的语言（或指定为“其他语言”）时，代码框无法显示行号，也无法使用copy功能。

**Comment by LuRenJiasWorld** [comment]
你好，这个是预期行为，可以使用 `text` 语言来实现纯文本&有行号的需求。
