### ISSUE TITLE
[BUG]代码块指定语言后不换行

### ISSUE THREAD

**Issue by sunzhangchang** [LuRenJiasWorld/WP-Editor.md#543]
**BUG描述 | Describe the bug**
代码块指定语言后不换行

**截图 | Screenshots**
编辑页面的预览：
![87ea2a3afcee4e1cbc8f867f5cfad47f](https://user-images.githubusercontent.com/52880063/133965034-344185e5-f4ef-4edf-8a29-d8e7dc7ecb94.jpg)

文章中显示：
![image](https://user-images.githubusercontent.com/52880063/133965162-04081519-bda0-4f20-96d1-27a051d08c81.png)

**调试信息 | Debugging info*
![wp-editormd-debug-info](https://user-images.githubusercontent.com/52880063/133964945-820393b6-ceb9-44b1-a3c7-aaf3d81a6647.png)

**Comment by LuRenJiasWorld** [comment]
你好，看起来像是和主题不兼容导致的问题。方便的话麻烦发下文章地址，我看看是否可以通过新增CSS来解决。

**Comment by sunzhangchang** [comment]
文章地址： http://fun.wczo.cn/index.php/archives/20

但是好像是添加指定语言后所有的换行都变成空格了

**Comment by sunzhangchang** [comment]
不指定语言是可以换行的

**Comment by debuTV** [comment]
遇见相同的问题了，请问具体该怎么处理，需要我做什么吗？

**Comment by LuRenJiasWorld** [comment]
你好，最近两年由于个人原因，没有跟进插件维护，现在开始继续维护，正在处理堆积的 Issue。
由于这个 Issue 没有进一步提供信息，或提供有效复现方法，或不确定您是否还在使用该插件，暂时先关闭处理。
如果您依然使用该插件，或希望继续推进该问题的解决，欢迎重新打开 Issue，我会尽力&尽快跟进。
感谢支持和理解。
