### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by real-jiakai** [LuRenJiasWorld/WP-Editor.md#550]
![image](https://user-images.githubusercontent.com/82650452/146921854-3f79f674-69f6-41f4-b42c-4d558fbaf23c.png)
![image](https://user-images.githubusercontent.com/82650452/146921891-84652392-6456-4df9-874a-21cf1944ceca.png)

作者，你好，请问这个插件显示目录如何隐藏编号。我一般自己markdown会标注编号，显示编号对于我来说是多余的。我翻遍了这个插件的所有位置，没有找到隐藏编号的选项。:sweat_smile:

**Comment by real-jiakai** [comment]
目前我是用其他插件来弥补这一点的缺失的，因为我没学过php，所以对于修改toc.php文件有困难。

**Comment by LuRenJiasWorld** [comment]
你好，因为这个插件是第三方开发的，暂时没有办法解决这个问题，我先记录下来，如果有其他用户也反馈类似问题，我提一个Issue给他们。

**Comment by real-jiakai** [comment]
嗯嗯:smile::smile::smile:
其实自动生成目录还是存在bug的，不只是没有`取消序号`按钮这么简单，自动生成目录还会将文章最后的作者也作为目录显示。因此我已经不打算用该插件的目录了。这个插件满足了我用markdown写作的偏好。感谢你们的付出。:thumbsup::thumbsup::thumbsup:
