### ISSUE TITLE
[Feature] 图片显示的优化建议

### ISSUE THREAD

**Issue by luhuadong** [LuRenJiasWorld/WP-Editor.md#552]
**该功能的缺失是否引起你的使用不便？ | Is your feature request related to a problem?**
> 图片默认左对齐，我在设置里也没有找到对齐方式的设置功能，我不知道是没找到还是没有这个功能？
> 这个功能对排版来说挺重要的，另外，如果图片描述能自动添加到图片下方显示出来就更好了！

**你认为该功能应该是什么样的？ | Describe the solution you'd like**
> 比如这样：

![](https://static.getiot.tech/image-align-center-and-description.png)

**有类似功能的产品可供参考吗？ | Is there some similar software?**
> Typora 中添加图片默认会居中

**其他信息 | Additional context**
> 无

**Comment by LuRenJiasWorld** [comment]
你好，Markdown是不支持图片对齐方式修改的，不过你可以通过自定义网站CSS样式的方式，让图片默认居中。

**Comment by luhuadong** [comment]
好的吧
