### ISSUE TITLE
[BUG]WP-Editor.md 10.2.1预览与实际显示不一样的问题。

### ISSUE THREAD

**Issue by zyftank** [LuRenJiasWorld/WP-Editor.md#559]
问题：安装了WP-Editor.md10.2.1插件后，编辑预览与实际显示不一样，主要问题是不换行、代码块显示不高亮。在更换wordpress自带的主题后，问题依然存在。

问题展示：
![this is an image](https://gitee.com/zyyhhh/image/raw/master/123.PNG)
这是在编辑器里预览的状态

![this is an image](https://gitee.com/zyyhhh/image/raw/master/124.PNG)
这是最终在博客里显示的效果。

debug信息：
![this is an image](https://gitee.com/zyyhhh/image/raw/master/wp-editormd-debug-info.png)

**Comment by Azathoth-NyarlathoTep** [comment]
我也有这样的问题，这是怎么解决的
