### ISSUE TITLE
升级插件之后，变成以下情况了，帮忙看下【已解决】

### ISSUE THREAD

**Issue by xxxit** [LuRenJiasWorld/WP-Editor.md#561]
### 问题
插件升级以后，编辑框变成下面的情况了，右边的实时预览也没了，比如以前左边框输入：## 标题，右边预览会变大现在没了实时预览很不习惯，不知道是不是哪里设置的问题,并且实时预览是开启状态，之前提示资源过时，根据文档使用了本地资源
### 版本
10.2.1版本
### 示例图
![测试写入](https://user-images.githubusercontent.com/50447766/174922739-a29f636e-604e-4cf1-b6dc-7f0ca60d3547.png)
![md](https://user-images.githubusercontent.com/50447766/174923192-32a14fb8-cde2-4594-8d06-ca5cd27b80f8.png)
![实时预览](https://user-images.githubusercontent.com/50447766/174924214-1c3f1b8a-d1c6-4908-9bd0-52b1eebb9ae6.png)

**Comment by czcxwe** [comment]
您好，这里是蔡治成，邮件已经收到，会在两日内回复（如有必要）。感谢来信！蔡治成Hello, This is Zhicheng Cai's mailbox. I got your email and I will reply it within 2 days if necessary.regards，Zhicheng Cai

**Comment by xxxit** [comment]
###  已解决
1.先是使用本地资源，状态提示为：资源为最新，此时依旧不能用
2.把地址栏中本地资源路径删掉，然后点击：使用CDN资源
3.保存，md就恢复正常了
