### ISSUE TITLE
[BUG] 无法启用插件，因为它引起了一个致命错误（fatal error）。

### ISSUE THREAD

**Issue by Dominic-KK** [LuRenJiasWorld/WP-Editor.md#568]
Warning: require_once(/home/ftp/d/username/wwwroot/wp-content/plugins/WP-Editor.md-master/vendor/autoload.php): failed to open stream: No such file or directory in /home/ftp/d/username/wwwroot/wp-content/plugins/WP-Editor.md-master/wp-editormd.php on line 33 Fatal error: require_once(): Failed opening required '/home/ftp/d/username/wwwroot/wp-content/plugins/WP-Editor.md-master/vendor/autoload.php' (include_path='.:/vhs/kangle/ext/php74/lib/php') in /home/ftp/d/username/wwwroot/wp-content/plugins/WP-Editor.md-master/wp-editormd.php on line 33

**Comment by LuRenJiasWorld** [comment]
你好，请安装 release 的最新版本。master 分支上只是源码，没有带依赖，需要构建后才能使用哦。

**Comment by Dominic-KK** [comment]
好的感谢，尝试后再给您反馈
