### ISSUE TITLE
如何居中显示图片

### ISSUE THREAD

**Issue by jingling2000** [LuRenJiasWorld/WP-Editor.md#570]
不知道有没有图片居中显示功能

**Comment by LuRenJiasWorld** [comment]
最近确实了解到有一些扩展语法（如 Obsidian / Logseq 等）给图片加上排版能力，不过本插件目前只支持基础的 Markdown 语法：https://daringfireball.net/projects/markdown/。

**Comment by LuRenJiasWorld** [comment]
如果有居中的需求，有两个办法：
1. 使用 WordPress 的自定义功能对图片新增居中的 CSS 样式
2. 在本编辑器里使用 `<img>` 标签添加图片：https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Comment by wintertee** [comment]
可以在图片前后添加html标签
```html
<center>
![]()
</center>
```
