### ISSUE TITLE
[BUG] Markdown渲染问题

### ISSUE THREAD

**Issue by CryingObsidian-CO** [LuRenJiasWorld/WP-Editor.md#575]
**BUG描述 | Describe the bug**
> 我在尝试将无序列表于标题放在同一行时在文章页面无法渲染出标题，仅能渲染出无序列表的点(但在预览页面却可以正常显示)，我不清楚是我设置的问题还是其它导致的

**复现方法 | To Reproduce**
>使用无序列表后跟随任意大小标题(我尝试了标题3与标题4，存在同样问题)

**截图 | Screenshots**
>这是编辑器页面的截图:
![image](https://user-images.githubusercontent.com/54172963/216077900-6b37f3b4-9088-4336-9ba6-3ebda5deb38c.png)
>这是预览框的截图(可以正常渲染):
![image](https://user-images.githubusercontent.com/54172963/216079568-a2909f12-be29-4a5f-bd5b-00c8c6923f79.png)
>这事文章显示页面的截图(渲染异常):
![image](https://user-images.githubusercontent.com/54172963/216079812-9f36d3ec-8b78-41de-916d-fdfa8f6d14da.png)

**调试信息 | Debugging info**
> 
![image](https://user-images.githubusercontent.com/54172963/216081554-9f0e33f3-382c-46c8-b9b8-07c69dad1a12.png)
![image](https://user-images.githubusercontent.com/54172963/216081608-3083a4bf-71a2-41a0-ae4e-ad1835c8394f.png)

**其他内容 | Additional context**
> 目前已在默认主题(Twenty Twenty-Three)测试，问题可以复现，我并没有关闭其他插件进行测试，因为我认为其余插件并没有可以改变前端渲染的，除了一个缓存插件(我有尝试删除缓存后重新加载)

**Comment by CryingObsidian-CO** [comment]
非常抱歉我在向下翻动时一不小心点到了Close with comment

**Comment by CryingObsidian-CO** [comment]
我发现当
![image](https://user-images.githubusercontent.com/54172963/216331315-722cbb77-5893-4530-8db3-c9a13371f605.png)
我将他们如此排放是，并不能正确渲染
但当这样时
![image](https://user-images.githubusercontent.com/54172963/216331551-882de5ae-1cd2-4f96-8232-7ff26f5b2909.png)
便正常，所以这似乎时我没有正确输入标题的下一行导致的

**Comment by LuRenJiasWorld** [comment]
可以复现，原因为编辑器预览和后台渲染使用的是不同的 Markdown 实现，后台渲染的 Markdown 库支持语法有限，难以扩展。

有机会打算彻底弃用掉这个后台库，换成前端预览+渲染提交到数据库。

**Comment by CryingObsidian-CO** [comment]
> 可以复现，原因为编辑器预览和后台渲染使用的是不同的 Markdown 实现，后台渲染的 Markdown 库支持语法有限，难以扩展。
> 
> 有机会打算彻底弃用掉这个后台库，换成前端预览+渲染提交到数据库。

好的谢谢，我发现如果我非常严格的按照Markdown的语法似乎不会出太大问题，我准备就先这么用着啦😁
