### ISSUE TITLE
[BUG]不是BUG，使用咨询

### ISSUE THREAD

**Issue by chunbo007** [LuRenJiasWorld/WP-Editor.md#595]
1. 我在后台编辑好内容后，发现并不会在前台生成 <p> 标签，但是我切换其他主题发现有p标签，我当前使用的主题是我自制的。但是输出文章内容都是用的the_content()

2. 请问我需要在主题里面手动引入某些css吗？

**Comment by czcxwe** [comment]
您好，这里是蔡治成，邮件已经收到，会在两日内回复（如有必要）。感谢来信！蔡治成Hello, This is Zhicheng Cai's mailbox. I got your email and I will reply it within 2 days if necessary.Regards，Zhicheng Cai

**Comment by chunbo007** [comment]
主题问题，已自行解决，感谢作者的插件
